export const MAPS = [
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 60 06 74 06 6A 06 8D 42 8D 42 73 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 73 06 8D 42 8E 42 8D 42 8D 42 73 06 8D 42 8D 42 73 06 8D 42 8D 42 68 06 74 06 72 06 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE01",
  "name": "BattlePyramidSquare01",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE01",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_NINJA_BOY",
      "x": 2,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 5,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 2,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_2",
      "x": 6,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 4,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 68 06 74 06 74 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 73 06 8D 42 8D 42 8E 02 8D 42 8D 42 71 06 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 70 06 74 06 6A 06 8D 42 68 06 6A 06 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE02",
  "name": "BattlePyramidSquare02",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE02",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_3",
      "x": 2,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 5,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_FAT_MAN",
      "x": 2,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_TWIN",
      "x": 5,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 6,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 68 06 6B 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 60 06 74 06 74 06 74 06 74 06 72 06 8D 42 8E 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE03",
  "name": "BattlePyramidSquare03",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE03",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_1",
      "x": 2,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_BOY",
      "x": 6,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_FISHERMAN",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_MAN_3",
      "x": 3,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 4,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 2,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 60 06 74 06 74 06 74 06 74 06 6A 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8E 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE04",
  "name": "BattlePyramidSquare04",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE04",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_WOMAN_2",
      "x": 7,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_1",
      "x": 7,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 1,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 2,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 5,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 3,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 62 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8E 02 8D 42 8D 42 70 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE05",
  "name": "BattlePyramidSquare05",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE05",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_2",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_2",
      "x": 3,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_2",
      "x": 3,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_BOY_2",
      "x": 6,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 4,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 68 06 6A 06 8D 42 61 06 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8E 02 8D 42 8D 42 61 06 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 71 06 8D 42 68 06 6A 06 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE06",
  "name": "BattlePyramidSquare06",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE06",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_2",
      "x": 5,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_2",
      "x": 2,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_2",
      "x": 5,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_2",
      "x": 2,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 4,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8E 02 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 61 06 8D 42 61 06 8D 42 68 06 72 06 8D 42 8D 42 71 06 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 68 06 74 06 74 06 74 06 74 06 72 06 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 71 06",
  "id": "MAP_BATTLE_PYRAMID_SQUARE07",
  "name": "BattlePyramidSquare07",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE07",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_BOY",
      "x": 0,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_BOY",
      "x": 4,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_BOY",
      "x": 6,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_BOY",
      "x": 4,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 3,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 74 06 74 06 74 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 73 06 8D 42 8D 42 8E 02 8D 42 8D 42 8D 42 73 06 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 71 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 68 06 74 06 74 06 6A 06 8D 02 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE08",
  "name": "BattlePyramidSquare08",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE08",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 1,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 6,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 1,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 6,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 4,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 3,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 60 06 72 06 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 68 06 72 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 02 8D 42 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 42 61 06 60 06 72 06 8D 42 8D 42 61 06 8D 42 60 06 72 06 71 06 8D 42 8D 42 60 06 72 06 8D 42 71 06 8D 42 8E 02 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE09",
  "name": "BattlePyramidSquare09",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE09",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 3,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 6,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_LITTLE_GIRL",
      "x": 3,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 68 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 6A 06 8D 42 68 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 74 06 6A 06 8E 42 68 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE10",
  "name": "BattlePyramidSquare10",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE10",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 3,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 0,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 6,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_GIRL_3",
      "x": 0,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "7",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 3,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 5,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 68 06 6A 06 8D 42 8D 42 8D 42 60 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 73 06 8D 42 8D 42 61 06 8D 42 8D 42 68 06 74 06 72 06 8D 42 8D 42 70 06 74 06 62 06 8D 42 8D 42 8D 42 8D 02 8E 02 8D 42 8D 42 71 06 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 8D 42 8D 02 8D 42 68 06 72 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 6A 06 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE11",
  "name": "BattlePyramidSquare11",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE11",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 3,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 3,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_LEFT_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_RICH_BOY",
      "x": 6,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 6,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"68 06 74 06 6A 06 8D 42 68 06 74 06 6A 06 8E 02 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 6A 06 8D 42 68 06 74 06 74 06 6A 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 68 06 74 06 74 06 74 06 74 06 74 06 6A 06 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE12",
  "name": "BattlePyramidSquare12",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE12",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_WOMAN_1",
      "x": 7,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "7",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_WOMAN_1",
      "x": 0,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "7",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_WOMAN_1",
      "x": 3,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_WOMAN_1",
      "x": 3,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "3",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"61 06 8D 42 8D 42 8D 42 61 06 8D 42 8D 42 8D 42 73 06 8D 42 61 06 8D 42 73 06 8D 42 61 06 8D 42 71 06 8D 42 71 06 8D 42 73 06 8D 42 73 06 8D 42 8D 42 8D 42 8D 42 8D 42 71 06 8D 42 71 06 8D 42 8D 02 8D 42 8D 02 8D 42 8E 42 8D 42 8D 42 8D 42 73 06 8D 42 73 06 8D 42 61 06 8D 02 61 06 8D 42 71 06 8D 42 73 06 8D 42 71 06 8D 42 73 06 8D 42 8D 42 8D 42 71 06 8D 42 8D 42 8D 42 71 06 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE13",
  "name": "BattlePyramidSquare13",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE13",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_FAT_MAN",
      "x": 5,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_FAT_MAN",
      "x": 5,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_FAT_MAN",
      "x": 1,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_FAT_MAN",
      "x": 1,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 3,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8E 02 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE14",
  "name": "BattlePyramidSquare14",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE14",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 7,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "7",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 1,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 6,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 0,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "7",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 5,
      "y": 3,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8E 02 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 8D 42 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 65 06 8D 42 8D 42 8D 42 65 06 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE15",
  "name": "BattlePyramidSquare15",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE15",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 2,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "5",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 2,
      "y": 1,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 6,
      "y": 4,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 6,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "4",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 5,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 1,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
},
{
  "layoutContent":"8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8E 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42 8D 42",
  "id": "MAP_BATTLE_PYRAMID_SQUARE16",
  "name": "BattlePyramidSquare16",
  "layout": "LAYOUT_BATTLE_PYRAMID_SQUARE16",
  "music": "MUS_NONE",
  "region_map_section": "MAPSEC_DYNAMIC",
  "requires_flash": false,
  "weather": "WEATHER_NONE",
  "map_type": "MAP_TYPE_INDOOR",
  "allow_cycling": false,
  "allow_escaping": false,
  "allow_running": false,
  "show_map_name": false,
  "battle_scene": "MAP_BATTLE_SCENE_GYM",
  "connections": null,
  "shared_scripts_map": "BattlePyramidSquare01",
  "object_events": [
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 0,
      "y": 6,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 1,
      "y": 0,
      "elevation": 0,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 6,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_UP_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_POKEFAN_F",
      "x": 6,
      "y": 0,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_FACE_DOWN_AND_LEFT",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NORMAL",
      "trainer_sight_or_berry_tree_id": "6",
      "script": "BattlePyramid_TrainerBattle",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 0,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 7,
      "y": 7,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_ITEM_BALL",
      "x": 5,
      "y": 2,
      "elevation": 4,
      "movement_type": "MOVEMENT_TYPE_LOOK_AROUND",
      "movement_range_x": 1,
      "movement_range_y": 1,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "BattlePyramid_FindItemBall",
      "flag": "0"
    }
  ],
  "warp_events": [],
  "coord_events": [],
  "bg_events": []
}
]
