
import { renameIfNeeded } from "../data/renameList";

export const MOVES = [
{"name":"","pp":0,"priority":0},
{"name":"Pound","pp":35,"priority":0},
{"name":"Karate Chop","pp":25,"priority":0},
{"name":"DoubleSlap","pp":10,"priority":0},
{"name":"Comet Punch","pp":15,"priority":0},
{"name":"Mega Punch","pp":20,"priority":0},
{"name":"Pay Day","pp":20,"priority":0},
{"name":"Fire Punch","pp":15,"priority":0},
{"name":"Ice Punch","pp":15,"priority":0},
{"name":"ThunderPunch","pp":15,"priority":0},
{"name":"Scratch","pp":35,"priority":0},
{"name":"ViceGrip","pp":30,"priority":0},
{"name":"Guillotine","pp":5,"priority":0},
{"name":"Razor Wind","pp":10,"priority":0},
{"name":"Swords Dance","pp":30,"priority":0},
{"name":"Cut","pp":30,"priority":0},
{"name":"Gust","pp":35,"priority":0},
{"name":"Wing Attack","pp":35,"priority":0},
{"name":"Whirlwind","pp":20,"priority":-6},
{"name":"Fly","pp":15,"priority":0},
{"name":"Bind","pp":20,"priority":0},
{"name":"Slam","pp":20,"priority":0},
{"name":"Vine Whip","pp":10,"priority":0},
{"name":"Stomp","pp":20,"priority":0},
{"name":"Double Kick","pp":30,"priority":0},
{"name":"Mega Kick","pp":5,"priority":0},
{"name":"Jump Kick","pp":25,"priority":0},
{"name":"Rolling Kick","pp":15,"priority":0},
{"name":"Sand-Attack","pp":15,"priority":0},
{"name":"Headbutt","pp":15,"priority":0},
{"name":"Horn Attack","pp":25,"priority":0},
{"name":"Fury Attack","pp":20,"priority":0},
{"name":"Horn Drill","pp":5,"priority":0},
{"name":"Tackle","pp":35,"priority":0},
{"name":"Body Slam","pp":15,"priority":0},
{"name":"Wrap","pp":20,"priority":0},
{"name":"Take Down","pp":20,"priority":0},
{"name":"Thrash","pp":20,"priority":0},
{"name":"Double-Edge","pp":15,"priority":0},
{"name":"Tail Whip","pp":30,"priority":0},
{"name":"Poison Sting","pp":35,"priority":0},
{"name":"Twineedle","pp":20,"priority":0},
{"name":"Pin Missile","pp":20,"priority":0},
{"name":"Leer","pp":30,"priority":0},
{"name":"Bite","pp":25,"priority":0},
{"name":"Growl","pp":40,"priority":0},
{"name":"Roar","pp":20,"priority":-6},
{"name":"Sing","pp":15,"priority":0},
{"name":"Supersonic","pp":20,"priority":0},
{"name":"SonicBoom","pp":20,"priority":0},
{"name":"Disable","pp":20,"priority":0},
{"name":"Acid","pp":30,"priority":0},
{"name":"Ember","pp":25,"priority":0},
{"name":"Flamethrower","pp":15,"priority":0},
{"name":"Mist","pp":30,"priority":0},
{"name":"Water Gun","pp":25,"priority":0},
{"name":"Hydro Pump","pp":5,"priority":0},
{"name":"Surf","pp":15,"priority":0},
{"name":"Ice Beam","pp":10,"priority":0},
{"name":"Blizzard","pp":5,"priority":0},
{"name":"Psybeam","pp":20,"priority":0},
{"name":"BubbleBeam","pp":20,"priority":0},
{"name":"Aurora Beam","pp":20,"priority":0},
{"name":"Hyper Beam","pp":5,"priority":0},
{"name":"Peck","pp":35,"priority":0},
{"name":"Drill Peck","pp":20,"priority":0},
{"name":"Submission","pp":25,"priority":0},
{"name":"Low Kick","pp":20,"priority":0},
{"name":"Counter","pp":20,"priority":-5},
{"name":"Seismic Toss","pp":20,"priority":0},
{"name":"Strength","pp":15,"priority":0},
{"name":"Absorb","pp":20,"priority":0},
{"name":"Mega Drain","pp":10,"priority":0},
{"name":"Leech Seed","pp":10,"priority":0},
{"name":"Growth","pp":40,"priority":0},
{"name":"Razor Leaf","pp":25,"priority":0},
{"name":"SolarBeam","pp":10,"priority":0},
{"name":"Poisonpowder","pp":35,"priority":0},
{"name":"Stun Spore","pp":30,"priority":0},
{"name":"Sleep Powder","pp":15,"priority":0},
{"name":"Petal Dance","pp":20,"priority":0},
{"name":"String Shot","pp":40,"priority":0},
{"name":"Dragon Rage","pp":10,"priority":0},
{"name":"Fire Spin","pp":15,"priority":0},
{"name":"Thundershock","pp":30,"priority":0},
{"name":"Thunderbolt","pp":15,"priority":0},
{"name":"Thunder Wave","pp":20,"priority":0},
{"name":"Thunder","pp":10,"priority":0},
{"name":"Rock Throw","pp":15,"priority":0},
{"name":"Earthquake","pp":10,"priority":0},
{"name":"Fissure","pp":5,"priority":0},
{"name":"Dig","pp":10,"priority":0},
{"name":"Toxic","pp":10,"priority":0},
{"name":"Confusion","pp":25,"priority":0},
{"name":"Psychic","pp":10,"priority":0},
{"name":"Hypnosis","pp":20,"priority":0},
{"name":"Meditate","pp":40,"priority":0},
{"name":"Agility","pp":30,"priority":0},
{"name":"Quick Attack","pp":30,"priority":1},
{"name":"Rage","pp":20,"priority":0},
{"name":"Teleport","pp":20,"priority":0},
{"name":"Night Shade","pp":15,"priority":0},
{"name":"Mimic","pp":10,"priority":0},
{"name":"Screech","pp":40,"priority":0},
{"name":"Double Team","pp":15,"priority":0},
{"name":"Recover","pp":20,"priority":0},
{"name":"Harden","pp":30,"priority":0},
{"name":"Minimize","pp":20,"priority":0},
{"name":"SmokeScreen","pp":20,"priority":0},
{"name":"Confuse Ray","pp":10,"priority":0},
{"name":"Withdraw","pp":40,"priority":0},
{"name":"Defense Curl","pp":40,"priority":0},
{"name":"Barrier","pp":30,"priority":0},
{"name":"Light Screen","pp":30,"priority":0},
{"name":"Haze","pp":30,"priority":0},
{"name":"Reflect","pp":20,"priority":0},
{"name":"Focus Energy","pp":30,"priority":0},
{"name":"Bide","pp":10,"priority":0},
{"name":"Metronome","pp":10,"priority":0},
{"name":"Mirror Move","pp":20,"priority":0},
{"name":"Selfdestruct","pp":5,"priority":0},
{"name":"Egg Bomb","pp":10,"priority":0},
{"name":"Lick","pp":30,"priority":0},
{"name":"Smog","pp":20,"priority":0},
{"name":"Sludge","pp":20,"priority":0},
{"name":"Bone Club","pp":20,"priority":0},
{"name":"Fire Blast","pp":5,"priority":0},
{"name":"Waterfall","pp":15,"priority":0},
{"name":"Clamp","pp":10,"priority":0},
{"name":"Swift","pp":20,"priority":0},
{"name":"Skull Bash","pp":15,"priority":0},
{"name":"Spike Cannon","pp":15,"priority":0},
{"name":"Constrict","pp":35,"priority":0},
{"name":"Amnesia","pp":20,"priority":0},
{"name":"Kinesis","pp":15,"priority":0},
{"name":"Softboiled","pp":10,"priority":0},
{"name":"Hi Jump Kick","pp":20,"priority":0},
{"name":"Glare","pp":30,"priority":0},
{"name":"Dream Eater","pp":15,"priority":0},
{"name":"Poison Gas","pp":40,"priority":0},
{"name":"Barrage","pp":20,"priority":0},
{"name":"Leech Life","pp":15,"priority":0},
{"name":"Lovely Kiss","pp":10,"priority":0},
{"name":"Sky Attack","pp":5,"priority":0},
{"name":"Transform","pp":10,"priority":0},
{"name":"Bubble","pp":30,"priority":0},
{"name":"Dizzy Punch","pp":10,"priority":0},
{"name":"Spore","pp":15,"priority":0},
{"name":"Flash","pp":20,"priority":0},
{"name":"Psywave","pp":15,"priority":0},
{"name":"Splash","pp":40,"priority":0},
{"name":"Acid Armor","pp":40,"priority":0},
{"name":"Crabhammer","pp":10,"priority":0},
{"name":"Explosion","pp":5,"priority":0},
{"name":"Fury Swipes","pp":15,"priority":0},
{"name":"Bonemerang","pp":10,"priority":0},
{"name":"Rest","pp":10,"priority":0},
{"name":"Rock Slide","pp":10,"priority":0},
{"name":"Hyper Fang","pp":15,"priority":0},
{"name":"Sharpen","pp":30,"priority":0},
{"name":"Conversion","pp":30,"priority":0},
{"name":"Tri Attack","pp":10,"priority":0},
{"name":"Super Fang","pp":10,"priority":0},
{"name":"Slash","pp":20,"priority":0},
{"name":"Substitute","pp":10,"priority":0},
{"name":"Struggle","pp":1,"priority":0},
{"name":"Sketch","pp":1,"priority":0},
{"name":"Triple Kick","pp":10,"priority":0},
{"name":"Thief","pp":10,"priority":0},
{"name":"Spider Web","pp":10,"priority":0},
{"name":"Mind Reader","pp":5,"priority":0},
{"name":"Nightmare","pp":15,"priority":0},
{"name":"Flame Wheel","pp":25,"priority":0},
{"name":"Snore","pp":15,"priority":0},
{"name":"Curse","pp":10,"priority":0},
{"name":"Flail","pp":15,"priority":0},
{"name":"Conversion 2","pp":30,"priority":0},
{"name":"Aeroblast","pp":5,"priority":0},
{"name":"Cotton Spore","pp":40,"priority":0},
{"name":"Reversal","pp":15,"priority":0},
{"name":"Spite","pp":10,"priority":0},
{"name":"Powder Snow","pp":25,"priority":0},
{"name":"Protect","pp":10,"priority":3},
{"name":"Mach Punch","pp":30,"priority":1},
{"name":"Scary Face","pp":10,"priority":0},
{"name":"Faint Attack","pp":20,"priority":0},
{"name":"Sweet Kiss","pp":10,"priority":0},
{"name":"Belly Drum","pp":10,"priority":0},
{"name":"Sludge Bomb","pp":10,"priority":0},
{"name":"Mud-Slap","pp":10,"priority":0},
{"name":"Octazooka","pp":10,"priority":0},
{"name":"Spikes","pp":20,"priority":0},
{"name":"Zap Cannon","pp":5,"priority":0},
{"name":"Foresight","pp":40,"priority":0},
{"name":"Destiny Bond","pp":5,"priority":0},
{"name":"Perish Song","pp":5,"priority":0},
{"name":"Icy Wind","pp":15,"priority":0},
{"name":"Detect","pp":5,"priority":3},
{"name":"Bone Rush","pp":10,"priority":0},
{"name":"Lock-on","pp":5,"priority":0},
{"name":"Outrage","pp":15,"priority":0},
{"name":"Sandstorm","pp":10,"priority":0},
{"name":"Giga Drain","pp":5,"priority":0},
{"name":"Endure","pp":10,"priority":3},
{"name":"Charm","pp":20,"priority":0},
{"name":"Rollout","pp":20,"priority":0},
{"name":"False Swipe","pp":40,"priority":0},
{"name":"Swagger","pp":15,"priority":0},
{"name":"Milk Drink","pp":10,"priority":0},
{"name":"Spark","pp":20,"priority":0},
{"name":"Fury Cutter","pp":20,"priority":0},
{"name":"Steel Wing","pp":25,"priority":0},
{"name":"Mean Look","pp":5,"priority":0},
{"name":"Attract","pp":15,"priority":0},
{"name":"Sleep Talk","pp":10,"priority":0},
{"name":"Heal Bell","pp":5,"priority":0},
{"name":"Return","pp":20,"priority":0},
{"name":"Present","pp":15,"priority":0},
{"name":"Frustration","pp":20,"priority":0},
{"name":"Safeguard","pp":25,"priority":0},
{"name":"Pain Split","pp":20,"priority":0},
{"name":"Sacred Fire","pp":5,"priority":0},
{"name":"Magnitude","pp":30,"priority":0},
{"name":"DynamicPunch","pp":5,"priority":0},
{"name":"Megahorn","pp":10,"priority":0},
{"name":"DragonBreath","pp":20,"priority":0},
{"name":"Baton Pass","pp":40,"priority":0},
{"name":"Encore","pp":5,"priority":0},
{"name":"Pursuit","pp":20,"priority":0},
{"name":"Rapid Spin","pp":40,"priority":0},
{"name":"Sweet Scent","pp":20,"priority":0},
{"name":"Iron Tail","pp":15,"priority":0},
{"name":"Metal Claw","pp":35,"priority":0},
{"name":"Vital Throw","pp":10,"priority":-1},
{"name":"Morning Sun","pp":5,"priority":0},
{"name":"Synthesis","pp":5,"priority":0},
{"name":"Moonlight","pp":5,"priority":0},
{"name":"Hidden Power","pp":15,"priority":0},
{"name":"Cross Chop","pp":5,"priority":0},
{"name":"Twister","pp":20,"priority":0},
{"name":"Rain Dance","pp":5,"priority":0},
{"name":"Sunny Day","pp":5,"priority":0},
{"name":"Crunch","pp":15,"priority":0},
{"name":"Mirror Coat","pp":20,"priority":-5},
{"name":"Psych Up","pp":10,"priority":0},
{"name":"ExtremeSpeed","pp":5,"priority":1},
{"name":"AncientPower","pp":5,"priority":0},
{"name":"Shadow Ball","pp":15,"priority":0},
{"name":"Future Sight","pp":15,"priority":0},
{"name":"Rock Smash","pp":15,"priority":0},
{"name":"Whirlpool","pp":15,"priority":0},
{"name":"Beat Up","pp":10,"priority":0},
{"name":"Fake Out","pp":10,"priority":1},
{"name":"Uproar","pp":10,"priority":0},
{"name":"Stockpile","pp":10,"priority":0},
{"name":"Spit Up","pp":10,"priority":0},
{"name":"Swallow","pp":10,"priority":0},
{"name":"Heat Wave","pp":10,"priority":0},
{"name":"Hail","pp":10,"priority":0},
{"name":"Torment","pp":15,"priority":0},
{"name":"Flatter","pp":15,"priority":0},
{"name":"Will-O-Wisp","pp":15,"priority":0},
{"name":"Memento","pp":10,"priority":0},
{"name":"Facade","pp":20,"priority":0},
{"name":"Focus Punch","pp":20,"priority":-3},
{"name":"SmellingSalt","pp":10,"priority":0},
{"name":"Follow Me","pp":20,"priority":3},
{"name":"Nature Power","pp":20,"priority":0},
{"name":"Charge","pp":20,"priority":0},
{"name":"Taunt","pp":20,"priority":0},
{"name":"Helping Hand","pp":20,"priority":5},
{"name":"Trick","pp":10,"priority":0},
{"name":"Role Play","pp":10,"priority":0},
{"name":"Wish","pp":10,"priority":0},
{"name":"Assist","pp":20,"priority":0},
{"name":"Ingrain","pp":20,"priority":0},
{"name":"Superpower","pp":5,"priority":0},
{"name":"Magic Coat","pp":15,"priority":4},
{"name":"Recycle","pp":10,"priority":0},
{"name":"Revenge","pp":10,"priority":-4},
{"name":"Brick Break","pp":15,"priority":0},
{"name":"Yawn","pp":10,"priority":0},
{"name":"Knock Off","pp":20,"priority":0},
{"name":"Endeavor","pp":5,"priority":0},
{"name":"Eruption","pp":5,"priority":0},
{"name":"Skill Swap","pp":10,"priority":0},
{"name":"Imprison","pp":10,"priority":0},
{"name":"Refresh","pp":20,"priority":0},
{"name":"Grudge","pp":5,"priority":0},
{"name":"Snatch","pp":10,"priority":4},
{"name":"Secret Power","pp":20,"priority":0},
{"name":"Dive","pp":10,"priority":0},
{"name":"Arm Thrust","pp":20,"priority":0},
{"name":"Camouflage","pp":20,"priority":0},
{"name":"Tail Glow","pp":20,"priority":0},
{"name":"Luster Purge","pp":5,"priority":0},
{"name":"Mist Ball","pp":5,"priority":0},
{"name":"FeatherDance","pp":15,"priority":0},
{"name":"Teeter Dance","pp":20,"priority":0},
{"name":"Blaze Kick","pp":10,"priority":0},
{"name":"Mud Sport","pp":15,"priority":0},
{"name":"Ice Ball","pp":20,"priority":0},
{"name":"Needle Arm","pp":15,"priority":0},
{"name":"Slack Off","pp":10,"priority":0},
{"name":"Hyper Voice","pp":10,"priority":0},
{"name":"Poison Fang","pp":15,"priority":0},
{"name":"Crush Claw","pp":10,"priority":0},
{"name":"Blast Burn","pp":5,"priority":0},
{"name":"Hydro Cannon","pp":5,"priority":0},
{"name":"Meteor Mash","pp":10,"priority":0},
{"name":"Astonish","pp":15,"priority":0},
{"name":"Weather Ball","pp":10,"priority":0},
{"name":"Aromatherapy","pp":5,"priority":0},
{"name":"Fake Tears","pp":20,"priority":0},
{"name":"Air Cutter","pp":25,"priority":0},
{"name":"Overheat","pp":5,"priority":0},
{"name":"Odor Sleuth","pp":40,"priority":0},
{"name":"Rock Tomb","pp":10,"priority":0},
{"name":"Silver Wind","pp":5,"priority":0},
{"name":"Metal Sound","pp":40,"priority":0},
{"name":"GrassWhistle","pp":15,"priority":0},
{"name":"Tickle","pp":20,"priority":0},
{"name":"Cosmic Power","pp":20,"priority":0},
{"name":"Water Spout","pp":5,"priority":0},
{"name":"Signal Beam","pp":15,"priority":0},
{"name":"Shadow Punch","pp":20,"priority":0},
{"name":"Extrasensory","pp":30,"priority":0},
{"name":"Sky Uppercut","pp":15,"priority":0},
{"name":"Sand Tomb","pp":15,"priority":0},
{"name":"Sheer Cold","pp":5,"priority":0},
{"name":"Muddy Water","pp":10,"priority":0},
{"name":"Bullet Seed","pp":30,"priority":0},
{"name":"Aerial Ace","pp":20,"priority":0},
{"name":"Icicle Spear","pp":30,"priority":0},
{"name":"Iron Defense","pp":15,"priority":0},
{"name":"Block","pp":5,"priority":0},
{"name":"Howl","pp":40,"priority":0},
{"name":"Dragon Claw","pp":15,"priority":0},
{"name":"Frenzy Plant","pp":5,"priority":0},
{"name":"Bulk Up","pp":20,"priority":0},
{"name":"Bounce","pp":5,"priority":0},
{"name":"Mud Shot","pp":15,"priority":0},
{"name":"Poison Tail","pp":25,"priority":0},
{"name":"Covet","pp":40,"priority":0},
{"name":"Volt Tackle","pp":15,"priority":0},
{"name":"Magical Leaf","pp":20,"priority":0},
{"name":"Water Sport","pp":15,"priority":0},
{"name":"Calm Mind","pp":20,"priority":0},
{"name":"Leaf Blade","pp":15,"priority":0},
{"name":"Dragon Dance","pp":20,"priority":0},
{"name":"Rock Blast","pp":10,"priority":0},
{"name":"Shock Wave","pp":20,"priority":0},
{"name":"Water Pulse","pp":20,"priority":0},
{"name":"Doom Desire","pp":5,"priority":0},
{"name":"Psycho Boost","pp":5,"priority":0}
].map(a => {
  a.name = renameIfNeeded(a.name);
  return a;
});

export const SPECIES_INTERNAL_ID_TO_NAME = `??????????,Bulbasaur,Ivysaur,Venusaur,Charmander,Charmeleon,Charizard,Squirtle,Wartortle,Blastoise,Caterpie,Metapod,Butterfree,Weedle,Kakuna,Beedrill,Pidgey,Pidgeotto,Pidgeot,Rattata,Raticate,Spearow,Fearow,Ekans,Arbok,Pikachu,Raichu,Sandshrew,Sandslash,Nidoran♀,Nidorina,Nidoqueen,Nidoran♂,Nidorino,Nidoking,Clefairy,Clefable,Vulpix,Ninetales,Jigglypuff,Wigglytuff,Zubat,Golbat,Oddish,Gloom,Vileplume,Paras,Parasect,Venonat,Venomoth,Diglett,Dugtrio,Meowth,Persian,Psyduck,Golduck,Mankey,Primeape,Growlithe,Arcanine,Poliwag,Poliwhirl,Poliwrath,Abra,Kadabra,Alakazam,Machop,Machoke,Machamp,Bellsprout,Weepinbell,Victreebel,Tentacool,Tentacruel,Geodude,Graveler,Golem,Ponyta,Rapidash,Slowpoke,Slowbro,Magnemite,Magneton,Farfetch'd,Doduo,Dodrio,Seel,Dewgong,Grimer,Muk,Shellder,Cloyster,Gastly,Haunter,Gengar,Onix,Drowzee,Hypno,Krabby,Kingler,Voltorb,Electrode,Exeggcute,Exeggutor,Cubone,Marowak,Hitmonlee,Hitmonchan,Lickitung,Koffing,Weezing,Rhyhorn,Rhydon,Chansey,Tangela,Kangaskhan,Horsea,Seadra,Goldeen,Seaking,Staryu,Starmie,Mr. Mime,Scyther,Jynx,Electabuzz,Magmar,Pinsir,Tauros,Magikarp,Gyarados,Lapras,Ditto,Eevee,Vaporeon,Jolteon,Flareon,Porygon,Omanyte,Omastar,Kabuto,Kabutops,Aerodactyl,Snorlax,Articuno,Zapdos,Moltres,Dratini,Dragonair,Dragonite,Mewtwo,Mew,Chikorita,Bayleef,Meganium,Cyndaquil,Quilava,Typhlosion,Totodile,Croconaw,Feraligatr,Sentret,Furret,Hoothoot,Noctowl,Ledyba,Ledian,Spinarak,Ariados,Crobat,Chinchou,Lanturn,Pichu,Cleffa,Igglybuff,Togepi,Togetic,Natu,Xatu,Mareep,Flaaffy,Ampharos,Bellossom,Marill,Azumarill,Sudowoodo,Politoed,Hoppip,Skiploom,Jumpluff,Aipom,Sunkern,Sunflora,Yanma,Wooper,Quagsire,Espeon,Umbreon,Murkrow,Slowking,Misdreavus,Unown,Wobbuffet,Girafarig,Pineco,Forretress,Dunsparce,Gligar,Steelix,Snubbull,Granbull,Qwilfish,Scizor,Shuckle,Heracross,Sneasel,Teddiursa,Ursaring,Slugma,Magcargo,Swinub,Piloswine,Corsola,Remoraid,Octillery,Delibird,Mantine,Skarmory,Houndour,Houndoom,Kingdra,Phanpy,Donphan,Porygon2,Stantler,Smeargle,Tyrogue,Hitmontop,Smoochum,Elekid,Magby,Miltank,Blissey,Raikou,Entei,Suicune,Larvitar,Pupitar,Tyranitar,Lugia,Ho-Oh,Celebi,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,Treecko,Grovyle,Sceptile,Torchic,Combusken,Blaziken,Mudkip,Marshtomp,Swampert,Poochyena,Mightyena,Zigzagoon,Linoone,Wurmple,Silcoon,Beautifly,Cascoon,Dustox,Lotad,Lombre,Ludicolo,Seedot,Nuzleaf,Shiftry,Nincada,Ninjask,Shedinja,Taillow,Swellow,Shroomish,Breloom,Spinda,Wingull,Pelipper,Surskit,Masquerain,Wailmer,Wailord,Skitty,Delcatty,Kecleon,Baltoy,Claydol,Nosepass,Torkoal,Sableye,Barboach,Whiscash,Luvdisc,Corphish,Crawdaunt,Feebas,Milotic,Carvanha,Sharpedo,Trapinch,Vibrava,Flygon,Makuhita,Hariyama,Electrike,Manectric,Numel,Camerupt,Spheal,Sealeo,Walrein,Cacnea,Cacturne,Snorunt,Glalie,Lunatone,Solrock,Azurill,Spoink,Grumpig,Plusle,Minun,Mawile,Meditite,Medicham,Swablu,Altaria,Wynaut,Duskull,Dusclops,Roselia,Slakoth,Vigoroth,Slaking,Gulpin,Swalot,Tropius,Whismur,Loudred,Exploud,Clamperl,Huntail,Gorebyss,Absol,Shuppet,Banette,Seviper,Zangoose,Relicanth,Aron,Lairon,Aggron,Castform,Volbeat,Illumise,Lileep,Cradily,Anorith,Armaldo,Ralts,Kirlia,Gardevoir,Bagon,Shelgon,Salamence,Beldum,Metang,Metagross,Regirock,Regice,Registeel,Kyogre,Groudon,Rayquaza,Latias,Latios,Jirachi,Deoxys,Chimecho`.split(',').map(a => renameIfNeeded(a));

export const SPECIES_INTERNAL_ID_TO_NATIONAL_DEX = `??????????,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,290,291,292,276,277,285,286,327,278,279,283,284,320,321,300,301,352,343,344,299,324,302,339,340,370,341,342,349,350,318,319,328,329,330,296,297,309,310,322,323,363,364,365,331,332,361,362,337,338,298,325,326,311,312,303,307,308,333,334,360,355,356,315,287,288,289,316,317,357,293,294,295,366,367,368,359,353,354,336,335,369,304,305,306,351,313,314,345,346,347,348,280,281,282,371,372,373,374,375,376,377,378,379,382,383,384,380,381,385,386,358`.split(',').map(a => +a);

export const SPECIES_NATIONAL_DEX_TO_INTERNAL_ID = function(nat:number){
  return SPECIES_INTERNAL_ID_TO_NATIONAL_DEX.indexOf(nat);
}

export const SPECIES_NAME_TO_NATIONAL_DEX = function(name:string){
  const internalId = SPECIES_INTERNAL_ID_TO_NAME.indexOf(name);
  return SPECIES_INTERNAL_ID_TO_NATIONAL_DEX[internalId];
}

export const NATURE_NAMES = `Hardy,Lonely,Brave,Adamant,Naughty,Bold,Docile,Relaxed,Impish,Lax,Timid,Hasty,Serious,Jolly,Naive,Modest,Mild,Quiet,Bashful,Rash,Calm,Gentle,Sassy,Careful,Quirky`.split(',');

export const ITEM_NAMES = `,Master Ball,Ultra Ball,Great Ball,Poké Ball,Safari Ball,Net Ball,Dive Ball,Nest Ball,Repeat Ball,Timer Ball,Luxury Ball,Premier Ball,Potion,Antidote,Burn Heal,Ice Heal,Awakening,Parlyz Heal,Full Restore,Max Potion,Hyper Potion,Super Potion,Full Heal,Revive,Max Revive,Fresh Water,Soda Pop,Lemonade,Moomoo Milk,EnergyPowder,Energy Root,Heal Powder,Revival Herb,Ether,Max Ether,Elixir,Max Elixir,Lava Cookie,Blue Flute,Yellow Flute,Red Flute,Black Flute,White Flute,Berry Juice,Sacred Ash,Shoal Salt,Shoal Shell,Red Shard,Blue Shard,Yellow Shard,Green Shard,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,HP Up,Protein,Iron,Carbos,Calcium,Rare Candy,PP Up,Zinc,PP Max,unknown,Guard Spec.,Dire Hit,X Attack,X Defend,X Speed,X Accuracy,X Special,Poké Doll,Fluffy Tail,unknown,Super Repel,Max Repel,Escape Rope,Repel,unknown,unknown,unknown,unknown,unknown,unknown,Sun Stone,Moon Stone,Fire Stone,Thunderstone,Water Stone,Leaf Stone,unknown,unknown,unknown,unknown,TinyMushroom,Big Mushroom,unknown,Pearl,Big Pearl,Stardust,Star Piece,Nugget,Heart Scale,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,Orange Mail,Harbor Mail,Glitter Mail,Mech Mail,Wood Mail,Wave Mail,Bead Mail,Shadow Mail,Tropic Mail,Dream Mail,Fab Mail,Retro Mail,Cheri Berry,Chesto Berry,Pecha Berry,Rawst Berry,Aspear Berry,Leppa Berry,Oran Berry,Persim Berry,Lum Berry,Sitrus Berry,Figy Berry,Wiki Berry,Mago Berry,Aguav Berry,Iapapa Berry,Razz Berry,Bluk Berry,Nanab Berry,Wepear Berry,Pinap Berry,Pomeg Berry,Kelpsy Berry,Qualot Berry,Hondew Berry,Grepa Berry,Tamato Berry,Cornn Berry,Magost Berry,Rabuta Berry,Nomel Berry,Spelon Berry,Pamtre Berry,Watmel Berry,Durin Berry,Belue Berry,Liechi Berry,Ganlon Berry,Salac Berry,Petaya Berry,Apicot Berry,Lansat Berry,Starf Berry,Enigma Berry,unknown,unknown,unknown,BrightPowder,White Herb,Macho Brace,Exp. Share,Quick Claw,Soothe Bell,Mental Herb,Choice Band,King's Rock,SilverPowder,Amulet Coin,Cleanse Tag,Soul Dew,DeepSeaTooth,DeepSeaScale,Smoke Ball,Everstone,Focus Band,Lucky Egg,Scope Lens,Metal Coat,Leftovers,Dragon Scale,Light Ball,Soft Sand,Hard Stone,Miracle Seed,BlackGlasses,Black Belt,Magnet,Mystic Water,Sharp Beak,Poison Barb,NeverMeltIce,Spell Tag,TwistedSpoon,Charcoal,Dragon Fang,Silk Scarf,Up-Grade,Shell Bell,Sea Incense,Lax Incense,Lucky Punch,Metal Powder,Thick Club,Stick,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,Red Scarf,Blue Scarf,Pink Scarf,Green Scarf,Yellow Scarf,Mach Bike,Coin Case,Itemfinder,Old Rod,Good Rod,Super Rod,S.S. Ticket,Contest Pass,unknown,Wailmer Pail,Devon Goods,Soot Sack,Basement Key,Acro Bike,Pokéblock Case,Letter,Eon Ticket,Red Orb,Blue Orb,Scanner,Go-Goggles,Meteorite,Rm. 1 Key,Rm. 2 Key,Rm. 4 Key,Rm. 6 Key,Storage Key,Root Fossil,Claw Fossil,Devon Scope,TM01 - Focus Punch,TM02 - Dragon Claw,TM03 - Water Pulse,TM04 - Calm Mind,TM05 - Roar,TM06 - Toxic,TM07 - Hail,TM08 - Bulk Up,TM09 - Bullet Seed,TM10 - Hidden Power,TM11 - Sunny Day,TM12 - Taunt,TM13 - Ice Beam,TM14 - Blizzard,TM15 - Hyper Beam,TM16 - Light Screen,TM17 - Protect,TM18 - Rain Dance,TM19 - Giga Drain,TM20 - Safeguard,TM21 - Frustration,TM22 - Solarbeam,TM23 - Iron Tail,TM24 - Thunderbolt,TM25 - Thunder,TM26 - Earthquake,TM27 - Return,TM28 - Dig,TM29 - Psychic,TM30 - Shadow Ball,TM31 - Brick Break,TM32 - Double Team,TM33 - Reflect,TM34 - Shock Wave,TM35 - Flamethrower,TM36 - Sludge Bomb,TM37 - Sandstorm,TM38 - Fire Blast,TM39 - Rock Tomb,TM40 - Aerial Ace,TM41 - Torment,TM42 - Facade,TM43 - Secret Power,TM44 - Rest,TM45 - Attract,TM46 - Thief,TM47 - Steel Wing,TM48 - Skill Swap,TM49 - Snatch,TM50 - Overheat,HM01 - Cut,HM02 - Fly,HM03 - Surf,HM04 - Strength,HM05 - Flash,HM06 - Rock Smash,HM07 - Waterfall,HM08 - Dive,unknown,unknown,Oak's Parcel,Poké Flute,Secret Key,Bike Voucher,Gold Teeth,Old Amber,Card Key,Lift Key,Helix Fossil,Dome Fossil,Silph Scope,Bicycle,Town Map,VS Seeker,Fame Checker,TM Case,Berry Pouch,Teachy TV,Tri-Pass,Rainbow Pass,Tea,MysticTicket,AuroraTicket,Powder Jar,Ruby,Sapphire,Magma Emblem,Old Sea Map`.split(',');

export const ABILITIES_BY_MON_INTERNAL_ID = ["","Overgrow","Overgrow","Overgrow","Blaze","Blaze","Blaze","Torrent","Torrent","Torrent","Shield Dust","Shed Skin","Compound Eyes","Shield Dust","Shed Skin","Swarm","Keen Eye","Keen Eye","Keen Eye","Run Away,Guts","Run Away,Guts","Keen Eye","Keen Eye","Intimidate,Shed Skin","Intimidate,Shed Skin","Static","Static","Sand Veil","Sand Veil","Poison Point","Poison Point","Poison Point","Poison Point","Poison Point","Poison Point","Cute Charm","Cute Charm","Flash Fire","Flash Fire","Cute Charm","Cute Charm","Inner Focus","Inner Focus","Chlorophyll","Chlorophyll","Chlorophyll","Effect Spore","Effect Spore","Compound Eyes","Shield Dust","Sand Veil,Arena Trap","Sand Veil,Arena Trap","Pickup","Limber","Damp,Cloud Nine","Damp,Cloud Nine","Vital Spirit","Vital Spirit","Intimidate,Flash Fire","Intimidate,Flash Fire","Water Absorb,Damp","Water Absorb,Damp","Water Absorb,Damp","Synchronize,Inner Focus","Synchronize,Inner Focus","Synchronize,Inner Focus","Guts","Guts","Guts","Chlorophyll","Chlorophyll","Chlorophyll","Clear Body,Liquid Ooze","Clear Body,Liquid Ooze","Rock Head,Sturdy","Rock Head,Sturdy","Rock Head,Sturdy","Run Away,Flash Fire","Run Away,Flash Fire","Oblivious,Own Tempo","Oblivious,Own Tempo","Magnet Pull,Sturdy","Magnet Pull,Sturdy","Keen Eye,Inner Focus","Run Away,Early Bird","Run Away,Early Bird","Thick Fat","Thick Fat","Stench,Sticky Hold","Stench,Sticky Hold","Shell Armor","Shell Armor","Levitate","Levitate","Levitate","Rock Head,Sturdy","Insomnia","Insomnia","Hyper Cutter,Shell Armor","Hyper Cutter,Shell Armor","Soundproof,Static","Soundproof,Static","Chlorophyll","Chlorophyll","Rock Head,Lightning Rod","Rock Head,Lightning Rod","Limber","Keen Eye","Own Tempo,Oblivious","Levitate","Levitate","Lightning Rod,Rock Head","Lightning Rod,Rock Head","Natural Cure,Serene Grace","Chlorophyll","Early Bird","Swift Swim","Poison Point","Swift Swim,Water Veil","Swift Swim,Water Veil","Illuminate,Natural Cure","Illuminate,Natural Cure","Soundproof","Swarm","Oblivious","Static","Flame Body","Hyper Cutter","Intimidate","Swift Swim","Intimidate","Water Absorb,Shell Armor","Limber","Run Away","Water Absorb","Volt Absorb","Flash Fire","Trace","Swift Swim,Shell Armor","Swift Swim,Shell Armor","Swift Swim,Battle Armor","Swift Swim,Battle Armor","Rock Head,Pressure","Immunity,Thick Fat","Pressure","Pressure","Pressure","Shed Skin","Shed Skin","Inner Focus","Pressure","Synchronize","Overgrow","Overgrow","Overgrow","Blaze","Blaze","Blaze","Torrent","Torrent","Torrent","Run Away,Keen Eye","Run Away,Keen Eye","Insomnia,Keen Eye","Insomnia,Keen Eye","Swarm,Early Bird","Swarm,Early Bird","Swarm,Insomnia","Swarm,Insomnia","Inner Focus","Volt Absorb,Illuminate","Volt Absorb,Illuminate","Static","Cute Charm","Cute Charm","Hustle,Serene Grace","Hustle,Serene Grace","Synchronize,Early Bird","Synchronize,Early Bird","Static","Static","Static","Chlorophyll","Thick Fat,Huge Power","Thick Fat,Huge Power","Sturdy,Rock Head","Water Absorb,Damp","Chlorophyll","Chlorophyll","Chlorophyll","Run Away,Pickup","Chlorophyll","Chlorophyll","Speed Boost,Compound Eyes","Damp,Water Absorb","Damp,Water Absorb","Synchronize","Synchronize","Insomnia","Oblivious,Own Tempo","Levitate","Levitate","Shadow Tag","Inner Focus,Early Bird","Sturdy","Sturdy","Serene Grace,Run Away","Hyper Cutter,Sand Veil","Rock Head,Sturdy","Intimidate,Run Away","Intimidate,Intimidate","Poison Point,Swift Swim","Swarm","Sturdy","Swarm,Guts","Inner Focus,Keen Eye","Pickup","Guts","Magma Armor,Flame Body","Magma Armor,Flame Body","Oblivious","Oblivious","Hustle,Natural Cure","Hustle","Suction Cups","Vital Spirit,Hustle","Swift Swim,Water Absorb","Keen Eye,Sturdy","Early Bird,Flash Fire","Early Bird,Flash Fire","Swift Swim","Pickup","Sturdy","Trace","Intimidate","Own Tempo","Guts","Intimidate","Oblivious","Static","Flame Body","Thick Fat","Natural Cure,Serene Grace","Pressure","Pressure","Pressure","Guts","Shed Skin","Sand Stream","Pressure","Pressure","Natural Cure","","","","","","","","","","","","","","","","","","","","","","","","","","Overgrow","Overgrow","Overgrow","Blaze","Blaze","Blaze","Torrent","Torrent","Torrent","Run Away","Intimidate","Pickup","Pickup","Shield Dust","Shed Skin","Swarm","Shed Skin","Shield Dust","Swift Swim,Rain Dish","Swift Swim,Rain Dish","Swift Swim,Rain Dish","Chlorophyll,Early Bird","Chlorophyll,Early Bird","Chlorophyll,Early Bird","Compound Eyes","Speed Boost","Wonder Guard","Guts","Guts","Effect Spore","Effect Spore","Own Tempo","Keen Eye","Keen Eye","Swift Swim","Intimidate","Water Veil,Oblivious","Water Veil,Oblivious","Cute Charm","Cute Charm","Color Change","Levitate","Levitate","Sturdy,Magnet Pull","White Smoke","Keen Eye","Oblivious","Oblivious","Swift Swim","Hyper Cutter,Shell Armor","Hyper Cutter,Shell Armor","Swift Swim","Marvel Scale","Rough Skin","Rough Skin","Hyper Cutter,Arena Trap","Levitate,Levitate","Levitate,Levitate","Thick Fat,Guts","Thick Fat,Guts","Static,Lightning Rod","Static,Lightning Rod","Oblivious","Magma Armor","Thick Fat","Thick Fat","Thick Fat","Sand Veil","Sand Veil","Inner Focus","Inner Focus","Levitate","Levitate","Thick Fat,Huge Power","Thick Fat,Own Tempo","Thick Fat,Own Tempo","Plus","Minus","Hyper Cutter,Intimidate","Pure Power","Pure Power","Natural Cure","Natural Cure","Shadow Tag","Levitate","Pressure","Natural Cure,Poison Point","Truant","Vital Spirit","Truant","Liquid Ooze,Sticky Hold","Liquid Ooze,Sticky Hold","Chlorophyll","Soundproof","Soundproof","Soundproof","Shell Armor","Swift Swim","Swift Swim","Pressure","Insomnia","Insomnia","Shed Skin","Immunity","Swift Swim,Rock Head","Sturdy,Rock Head","Sturdy,Rock Head","Sturdy,Rock Head","Forecast","Illuminate,Swarm","Oblivious","Suction Cups","Suction Cups","Battle Armor","Battle Armor","Synchronize,Trace","Synchronize,Trace","Synchronize,Trace","Rock Head","Rock Head","Intimidate","Clear Body","Clear Body","Clear Body","Clear Body","Clear Body","Clear Body","Drizzle","Drought","Air Lock","Levitate","Levitate","Serene Grace","Pressure","Levitate"];

export const GENDER_RATIO_BY_SPECIES_NAME:[string,number|null][] = [["???",null],["Bulbasaur",12.5],["Ivysaur",12.5],["Venusaur",12.5],["Charmander",12.5],["Charmeleon",12.5],["Charizard",12.5],["Squirtle",12.5],["Wartortle",12.5],["Blastoise",12.5],["Caterpie",50],["Metapod",50],["Butterfree",50],["Weedle",50],["Kakuna",50],["Beedrill",50],["Pidgey",50],["Pidgeotto",50],["Pidgeot",50],["Rattata",50],["Raticate",50],["Spearow",50],["Fearow",50],["Ekans",50],["Arbok",50],["Pikachu",50],["Raichu",50],["Sandshrew",50],["Sandslash",50],["Nidoran♀",100],["Nidoran-F",100],["Nidorina",100],["Nidoqueen",100],["Nidoran♂",0],["Nidoran-M",0],["Nidorino",0],["Nidoking",0],["Clefairy",75],["Clefable",75],["Vulpix",75],["Ninetales",75],["Jigglypuff",75],["Wigglytuff",75],["Zubat",50],["Golbat",50],["Oddish",50],["Gloom",50],["Vileplume",50],["Paras",50],["Parasect",50],["Venonat",50],["Venomoth",50],["Diglett",50],["Dugtrio",50],["Meowth",50],["Persian",50],["Psyduck",50],["Golduck",50],["Mankey",50],["Primeape",50],["Growlithe",25],["Arcanine",25],["Poliwag",50],["Poliwhirl",50],["Poliwrath",50],["Abra",25],["Kadabra",25],["Alakazam",25],["Machop",25],["Machoke",25],["Machamp",25],["Bellsprout",50],["Weepinbell",50],["Victreebel",50],["Tentacool",50],["Tentacruel",50],["Geodude",50],["Graveler",50],["Golem",50],["Ponyta",50],["Rapidash",50],["Slowpoke",50],["Slowbro",50],["Magnemite",null],["Magneton",null],["Farfetch'd",50],["Doduo",50],["Dodrio",50],["Seel",50],["Dewgong",50],["Grimer",50],["Muk",50],["Shellder",50],["Cloyster",50],["Gastly",50],["Haunter",50],["Gengar",50],["Onix",50],["Drowzee",50],["Hypno",50],["Krabby",50],["Kingler",50],["Voltorb",null],["Electrode",null],["Exeggcute",50],["Exeggutor",50],["Cubone",50],["Marowak",50],["Hitmonlee",0],["Hitmonchan",0],["Lickitung",50],["Koffing",50],["Weezing",50],["Rhyhorn",50],["Rhydon",50],["Chansey",100],["Tangela",50],["Kangaskhan",100],["Horsea",50],["Seadra",50],["Goldeen",50],["Seaking",50],["Staryu",null],["Starmie",null],["Mr. Mime",50],["Scyther",50],["Jynx",100],["Electabuzz",25],["Magmar",25],["Pinsir",50],["Tauros",0],["Magikarp",50],["Gyarados",50],["Lapras",50],["Ditto",null],["Eevee",12.5],["Vaporeon",12.5],["Jolteon",12.5],["Flareon",12.5],["Porygon",null],["Omanyte",12.5],["Omastar",12.5],["Kabuto",12.5],["Kabutops",12.5],["Aerodactyl",12.5],["Snorlax",12.5],["Articuno",null],["Zapdos",null],["Moltres",null],["Dratini",50],["Dragonair",50],["Dragonite",50],["Mewtwo",null],["Mew",null],["Chikorita",12.5],["Bayleef",12.5],["Meganium",12.5],["Cyndaquil",12.5],["Quilava",12.5],["Typhlosion",12.5],["Totodile",12.5],["Croconaw",12.5],["Feraligatr",12.5],["Sentret",50],["Furret",50],["Hoothoot",50],["Noctowl",50],["Ledyba",50],["Ledian",50],["Spinarak",50],["Ariados",50],["Crobat",50],["Chinchou",50],["Lanturn",50],["Pichu",50],["Cleffa",75],["Igglybuff",75],["Togepi",12.5],["Togetic",12.5],["Natu",50],["Xatu",50],["Mareep",50],["Flaaffy",50],["Ampharos",50],["Bellossom",50],["Marill",50],["Azumarill",50],["Sudowoodo",50],["Politoed",50],["Hoppip",50],["Skiploom",50],["Jumpluff",50],["Aipom",50],["Sunkern",50],["Sunflora",50],["Yanma",50],["Wooper",50],["Quagsire",50],["Espeon",12.5],["Umbreon",12.5],["Murkrow",50],["Slowking",50],["Misdreavus",50],["Unown",null],["Wobbuffet",50],["Girafarig",50],["Pineco",50],["Forretress",50],["Dunsparce",50],["Gligar",50],["Steelix",50],["Snubbull",75],["Granbull",75],["Qwilfish",50],["Scizor",50],["Shuckle",50],["Heracross",50],["Sneasel",50],["Teddiursa",50],["Ursaring",50],["Slugma",50],["Magcargo",50],["Swinub",50],["Piloswine",50],["Corsola",75],["Remoraid",50],["Octillery",50],["Delibird",50],["Mantine",50],["Skarmory",50],["Houndour",50],["Houndoom",50],["Kingdra",50],["Phanpy",50],["Donphan",50],["Porygon2",null],["Stantler",50],["Smeargle",50],["Tyrogue",0],["Hitmontop",0],["Smoochum",100],["Elekid",25],["Magby",25],["Miltank",100],["Blissey",100],["Raikou",null],["Entei",null],["Suicune",null],["Larvitar",50],["Pupitar",50],["Tyranitar",50],["Lugia",null],["Ho-Oh",null],["Celebi",null],["Treecko",12.5],["Grovyle",12.5],["Sceptile",12.5],["Torchic",12.5],["Combusken",12.5],["Blaziken",12.5],["Mudkip",12.5],["Marshtomp",12.5],["Swampert",12.5],["Poochyena",50],["Mightyena",50],["Zigzagoon",50],["Linoone",50],["Wurmple",50],["Silcoon",50],["Beautifly",50],["Cascoon",50],["Dustox",50],["Lotad",50],["Lombre",50],["Ludicolo",50],["Seedot",50],["Nuzleaf",50],["Shiftry",50],["Taillow",50],["Swellow",50],["Wingull",50],["Pelipper",50],["Ralts",50],["Kirlia",50],["Gardevoir",50],["Surskit",50],["Masquerain",50],["Shroomish",50],["Breloom",50],["Slakoth",50],["Vigoroth",50],["Slaking",50],["Nincada",50],["Ninjask",50],["Shedinja",null],["Whismur",50],["Loudred",50],["Exploud",50],["Makuhita",25],["Hariyama",25],["Azurill",75],["Nosepass",50],["Skitty",75],["Delcatty",75],["Sableye",50],["Mawile",50],["Aron",50],["Lairon",50],["Aggron",50],["Meditite",50],["Medicham",50],["Electrike",50],["Manectric",50],["Plusle",50],["Minun",50],["Volbeat",0],["Illumise",100],["Roselia",50],["Gulpin",50],["Swalot",50],["Carvanha",50],["Sharpedo",50],["Wailmer",50],["Wailord",50],["Numel",50],["Camerupt",50],["Torkoal",50],["Spoink",50],["Grumpig",50],["Spinda",50],["Trapinch",50],["Vibrava",50],["Flygon",50],["Cacnea",50],["Cacturne",50],["Swablu",50],["Altaria",50],["Zangoose",50],["Seviper",50],["Lunatone",null],["Solrock",null],["Barboach",50],["Whiscash",50],["Corphish",50],["Crawdaunt",50],["Baltoy",null],["Claydol",null],["Lileep",12.5],["Cradily",12.5],["Anorith",12.5],["Armaldo",12.5],["Feebas",50],["Milotic",50],["Castform",50],["Kecleon",50],["Shuppet",50],["Banette",50],["Duskull",50],["Dusclops",50],["Tropius",50],["Chimecho",50],["Absol",50],["Wynaut",50],["Snorunt",50],["Glalie",50],["Spheal",50],["Sealeo",50],["Walrein",50],["Clamperl",50],["Huntail",50],["Gorebyss",50],["Relicanth",12.5],["Luvdisc",75],["Bagon",50],["Shelgon",50],["Salamence",50],["Beldum",null],["Metang",null],["Metagross",null],["Regirock",null],["Regice",null],["Registeel",null],["Latias",100],["Latios",0],["Kyogre",null],["Groudon",null],["Rayquaza",null],["Jirachi",null],["Deoxys",null]];

export const getGenderRatio = function(n:string){
  const d = GENDER_RATIO_BY_SPECIES_NAME.find(g => g[0] === n);
  if (!d)
    throw new Error('invalid name ' + n);
  return d[1];
}