JSON.stringify([
    {"id":"3E2","flag":"EVENT_BEAT_ROUTE_3_TRAINER_0","name":"Youngster #1","location":"Route 3"},
    {"id":"3E3","flag":"EVENT_BEAT_ROUTE_3_TRAINER_1","name":"Youngster #2","location":"Route 3"},
    {"id":"572","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_1","name":"Youngster #3","location":"Mt. Moon 1F"},
    {"id":"542","flag":"EVENT_BEAT_ROUTE_24_TRAINER_0","name":"Youngster #4","location":"Route 24"},
    {"id":"551","flag":"EVENT_BEAT_ROUTE_25_TRAINER_0","name":"Youngster #5","location":"Route 25"},
    {"id":"552","flag":"EVENT_BEAT_ROUTE_25_TRAINER_1","name":"Youngster #6","location":"Route 25"},
    {"id":"555","flag":"EVENT_BEAT_ROUTE_25_TRAINER_4","name":"Youngster #7","location":"Route 25"},
    {"id":"5F1","flag":"EVENT_BEAT_SS_ANNE_8_TRAINER_0","name":"Youngster #8","location":"S.S. Anne 1F Rooms"},
    {"id":"471","flag":"EVENT_BEAT_ROUTE_11_TRAINER_0","name":"Youngster #9","location":"Route 11"},
    {"id":"472","flag":"EVENT_BEAT_ROUTE_11_TRAINER_1","name":"Youngster #10","location":"Route 11"},
    {"id":"473","flag":"EVENT_BEAT_ROUTE_11_TRAINER_2","name":"Youngster #11","location":"Route 11"},
    {"id":"474","flag":"EVENT_BEAT_ROUTE_11_TRAINER_3","name":"Youngster #12","location":"Route 11"},
    {"name":"Youngster Unused #1","obtainable":-1},
    {"id":"442","flag":"EVENT_BEAT_ROUTE_9_TRAINER_1","name":"Youngster #13","location":"Route 9"},
    {"id":"562","flag":"EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_0","name":"Bug Catcher #1","location":"Viridian Forest"},
    {"id":"563","flag":"EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_1","name":"Bug Catcher #2","location":"Viridian Forest"},
    {"id":"564","flag":"EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_2","name":"Bug Catcher #3","location":"Viridian Forest"},
    {"id":"3E4","flag":"EVENT_BEAT_ROUTE_3_TRAINER_2","name":"Bug Catcher #4","location":"Route 3"},
    {"id":"3E5","flag":"EVENT_BEAT_ROUTE_3_TRAINER_3","name":"Bug Catcher #5","location":"Route 3"},
    {"id":"3E6","flag":"EVENT_BEAT_ROUTE_3_TRAINER_4","name":"Bug Catcher #6","location":"Route 3"},
    {"id":"576","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_5","name":"Bug Catcher #7","location":"Mt. Moon 1F"},
    {"id":"577","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_6","name":"Bug Catcher #8","location":"Mt. Moon 1F"},
    {"id":"543","flag":"EVENT_BEAT_ROUTE_24_TRAINER_1","name":"Bug Catcher #9","location":"Route 24"},
    {"id":"411","flag":"EVENT_BEAT_ROUTE_6_TRAINER_0","name":"Bug Catcher #10","location":"Route 6"},
    {"id":"412","flag":"EVENT_BEAT_ROUTE_6_TRAINER_1","name":"Bug Catcher #11","location":"Route 6"},
    {"name":"Bug Catcher Unused #1","obtainable":-1},
    {"id":"447","flag":"EVENT_BEAT_ROUTE_9_TRAINER_6","name":"Bug Catcher #12","location":"Route 9"},
    {"id":"449","flag":"EVENT_BEAT_ROUTE_9_TRAINER_8","name":"Bug Catcher #13","location":"Route 9"},
    {"id":"565","flag":"EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_3","name":"Bug Catcher #14","location":"Viridian Forest"},
    {"id":"3E7","flag":"EVENT_BEAT_ROUTE_3_TRAINER_5","name":"Lass #1","location":"Route 3"},
    {"id":"3E8","flag":"EVENT_BEAT_ROUTE_3_TRAINER_6","name":"Lass #2","location":"Route 3"},
    {"id":"3E9","flag":"EVENT_BEAT_ROUTE_3_TRAINER_7","name":"Lass #3","location":"Route 3"},
    {"id":"3F2","flag":"EVENT_BEAT_ROUTE_4_TRAINER_0","name":"Lass #4","location":"Route 4"},
    {"id":"573","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_2","name":"Lass #5","location":"Mt. Moon 1F"},
    {"id":"575","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_4","name":"Lass #6","location":"Mt. Moon 1F"},
    {"id":"544","flag":"EVENT_BEAT_ROUTE_24_TRAINER_2","name":"Lass #7","location":"Route 24"},
    {"id":"545","flag":"EVENT_BEAT_ROUTE_24_TRAINER_3","name":"Lass #8","location":"Route 24"},
    {"id":"554","flag":"EVENT_BEAT_ROUTE_25_TRAINER_3","name":"Lass #9","location":"Route 25"},
    {"id":"556","flag":"EVENT_BEAT_ROUTE_25_TRAINER_5","name":"Lass #10","location":"Route 25"},
    {"id":"5F2","flag":"EVENT_BEAT_SS_ANNE_8_TRAINER_1","name":"Lass #11","location":"S.S. Anne 1F Rooms"},
    {"id":"601","flag":"EVENT_BEAT_SS_ANNE_9_TRAINER_0","name":"Lass #12","location":"S.S. Anne 2F Rooms"},
    {"id":"431","flag":"EVENT_BEAT_ROUTE_8_TRAINER_0","name":"Lass #13","location":"Route 8"},
    {"id":"432","flag":"EVENT_BEAT_ROUTE_8_TRAINER_1","name":"Lass #14","location":"Route 8"},
    {"id":"433","flag":"EVENT_BEAT_ROUTE_8_TRAINER_2","name":"Lass #15","location":"Route 8"},
    {"id":"434","flag":"EVENT_BEAT_ROUTE_8_TRAINER_3","name":"Lass #16","location":"Route 8"},
    {"id":"1AA","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_0","name":"Lass #17","location":"Celadon Gym"},
    {"id":"1AB","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_1","name":"Lass #18","location":"Celadon Gym"},
    {"id":"566","flag":"EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_4","name":"Lass #19","location":"Viridian Forest"},
    {"id":"5C4","flag":"EVENT_BEAT_SS_ANNE_5_TRAINER_0","name":"Sailor #1","location":"S.S. Anne Stern"},
    {"id":"5C5","flag":"EVENT_BEAT_SS_ANNE_5_TRAINER_1","name":"Sailor #2","location":"S.S. Anne Stern"},
    {"id":"611","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_0","name":"Sailor #3","location":"S.S. Anne B1F Rooms"},
    {"id":"612","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_1","name":"Sailor #4","location":"S.S. Anne B1F Rooms"},
    {"id":"613","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_2","name":"Sailor #5","location":"S.S. Anne B1F Rooms"},
    {"id":"614","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_3","name":"Sailor #6","location":"S.S. Anne B1F Rooms"},
    {"id":"615","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_4","name":"Sailor #7","location":"S.S. Anne B1F Rooms"},
    {"id":"162","flag":"EVENT_BEAT_VERMILION_GYM_TRAINER_0","name":"Sailor #8","location":"Vermilion Gym"},
    {"id":"072","flag":"EVENT_BEAT_PEWTER_GYM_TRAINER_0","name":"Jr Trainer (M) #1","location":"Pewter Gym"},
    {"id":"553","flag":"EVENT_BEAT_ROUTE_25_TRAINER_2","name":"Jr Trainer (M) #2","location":"Route 25"},
    {"id":"546","flag":"EVENT_BEAT_ROUTE_24_TRAINER_4","name":"Jr Trainer (M) #3","location":"Route 24"},
    {"name":"Jr Trainer (M) Unused #1","obtainable":-1},
    {"id":"413","flag":"EVENT_BEAT_ROUTE_6_TRAINER_2","name":"Jr Trainer (M) #4","location":"Route 6"},
    {"name":"Jr Trainer (M) Unused #2","obtainable":-1},
    {"name":"Jr Trainer (M) Unused #3","obtainable":-1},
    {"id":"443","flag":"EVENT_BEAT_ROUTE_9_TRAINER_2","name":"Jr Trainer (M) #5","location":"Route 9"},
    {"id":"482","flag":"EVENT_BEAT_ROUTE_12_TRAINER_0","name":"Jr Trainer (M) #6","location":"Route 12"},
    {"id":"414","flag":"EVENT_BEAT_ROUTE_6_TRAINER_3","name":"Jr Trainer (M) #7","location":"Route 6"},
    {"id":"547","flag":"EVENT_BEAT_ROUTE_24_TRAINER_5","name":"Jr Trainer (M) #8","location":"Route 24"},
    {"id":"0BA","flag":"EVENT_BEAT_CERULEAN_GYM_TRAINER_0","name":"Jr Trainer (F) #1","location":"Cerulean Gym"},
    {"name":"Jr Trainer (F) Unused #1","obtainable":-1},
    {"id":"415","flag":"EVENT_BEAT_ROUTE_6_TRAINER_4","name":"Jr Trainer (F) #2","location":"Route 6"},
    {"name":"Jr Trainer (F) Unused #2","obtainable":-1},
    {"id":"444","flag":"EVENT_BEAT_ROUTE_9_TRAINER_3","name":"Jr Trainer (F) #3","location":"Route 9"},
    {"id":"441","flag":"EVENT_BEAT_ROUTE_9_TRAINER_0","name":"Jr Trainer (F) #4","location":"Route 9"},
    {"id":"451","flag":"EVENT_BEAT_ROUTE_10_TRAINER_0","name":"Jr Trainer (F) #5","location":"Route 10"},
    {"id":"452","flag":"EVENT_BEAT_ROUTE_10_TRAINER_1","name":"Jr Trainer (F) #6","location":"Route 10"},
    {"id":"9B1","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_0","name":"Jr Trainer (F) #7","location":"Rock Tunnel B1F"},
    {"id":"9B2","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_1","name":"Jr Trainer (F) #8","location":"Rock Tunnel B1F"},
    {"id":"1AC","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_2","name":"Jr Trainer (F) #9","location":"Celadon Gym"},
    {"id":"491","flag":"EVENT_BEAT_ROUTE_13_TRAINER_0","name":"Jr Trainer (F) #10","location":"Route 13"},
    {"id":"492","flag":"EVENT_BEAT_ROUTE_13_TRAINER_1","name":"Jr Trainer (F) #11","location":"Route 13"},
    {"id":"493","flag":"EVENT_BEAT_ROUTE_13_TRAINER_2","name":"Jr Trainer (F) #12","location":"Route 13"},
    {"id":"494","flag":"EVENT_BEAT_ROUTE_13_TRAINER_3","name":"Jr Trainer (F) #13","location":"Route 13"},
    {"id":"501","flag":"EVENT_BEAT_ROUTE_20_TRAINER_0","name":"Jr Trainer (F) #14","location":"Route 20"},
    {"id":"459","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_0","name":"Jr Trainer (F) #15","location":"Rock Tunnel 1F"},
    {"id":"45A","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_1","name":"Jr Trainer (F) #16","location":"Rock Tunnel 1F"},
    {"id":"45B","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_2","name":"Jr Trainer (F) #17","location":"Rock Tunnel 1F"},
    {"id":"4B1","flag":"EVENT_BEAT_ROUTE_15_TRAINER_0","name":"Jr Trainer (F) #18","location":"Route 15"},
    {"id":"4B2","flag":"EVENT_BEAT_ROUTE_15_TRAINER_1","name":"Jr Trainer (F) #19","location":"Route 15"},
    {"id":"4B3","flag":"EVENT_BEAT_ROUTE_15_TRAINER_2","name":"Jr Trainer (F) #20","location":"Route 15"},
    {"id":"4B4","flag":"EVENT_BEAT_ROUTE_15_TRAINER_3","name":"Jr Trainer (F) #21","location":"Route 15"},
    {"id":"502","flag":"EVENT_BEAT_ROUTE_20_TRAINER_1","name":"Jr Trainer (F) #22","location":"Route 20"},
    {"id":"416","flag":"EVENT_BEAT_ROUTE_6_TRAINER_5","name":"Jr Trainer (F) #23","location":"Route 6"},
    {"id":"453","flag":"EVENT_BEAT_ROUTE_10_TRAINER_2","name":"Pokemaniac #1","location":"Route 10"},
    {"id":"454","flag":"EVENT_BEAT_ROUTE_10_TRAINER_3","name":"Pokemaniac #2","location":"Route 10"},
    {"id":"9B3","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_2","name":"Pokemaniac #3","location":"Rock Tunnel B1F"},
    {"id":"9B4","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_3","name":"Pokemaniac #4","location":"Rock Tunnel B1F"},
    {"id":"9B5","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_4","name":"Pokemaniac #5","location":"Rock Tunnel B1F"},
    {"id":"53C","flag":"EVENT_BEAT_VICTORY_ROAD_2_TRAINER_3","name":"Pokemaniac #6","location":"Victory Road 2F"},
    {"id":"45C","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_3","name":"Pokemaniac #7","location":"Rock Tunnel 1F"},
    {"id":"574","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_3","name":"SuperNerd #1","location":"Mt. Moon 1F"},
    {"id":"579","flag":"EVENT_BEAT_MT_MOON_EXIT_SUPER_NERD","name":"SuperNerd #2","location":"Mt. Moon B2F"},
    {"id":"435","flag":"EVENT_BEAT_ROUTE_8_TRAINER_4","name":"SuperNerd #3","location":"Route 8"},
    {"id":"436","flag":"EVENT_BEAT_ROUTE_8_TRAINER_5","name":"SuperNerd #4","location":"Route 8"},
    {"id":"437","flag":"EVENT_BEAT_ROUTE_8_TRAINER_6","name":"SuperNerd #5","location":"Route 8"},
    {"name":"SuperNerd Unused #1","obtainable":-1},
    {"name":"SuperNerd Unused #2","obtainable":-1},
    {"name":"SuperNerd Unused #3","obtainable":-1},
    {"id":"29A","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_0","name":"SuperNerd #6","location":"Cinnabar Gym"},
    {"id":"29B","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_1","name":"SuperNerd #7","location":"Cinnabar Gym"},
    {"id":"29C","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_2","name":"SuperNerd #8","location":"Cinnabar Gym"},
    {"id":"29D","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_3","name":"SuperNerd #9","location":"Cinnabar Gym"},
    {"id":"571","flag":"EVENT_BEAT_MT_MOON_1_TRAINER_0","name":"Hiker #1","location":"Mt. Moon 1F"},
    {"id":"557","flag":"EVENT_BEAT_ROUTE_25_TRAINER_6","name":"Hiker #2","location":"Route 25"},
    {"id":"558","flag":"EVENT_BEAT_ROUTE_25_TRAINER_7","name":"Hiker #3","location":"Route 25"},
    {"id":"559","flag":"EVENT_BEAT_ROUTE_25_TRAINER_8","name":"Hiker #4","location":"Route 25"},
    {"id":"445","flag":"EVENT_BEAT_ROUTE_9_TRAINER_4","name":"Hiker #5","location":"Route 9"},
    {"id":"446","flag":"EVENT_BEAT_ROUTE_9_TRAINER_5","name":"Hiker #6","location":"Route 9"},
    {"id":"455","flag":"EVENT_BEAT_ROUTE_10_TRAINER_4","name":"Hiker #7","location":"Route 10"},
    {"id":"456","flag":"EVENT_BEAT_ROUTE_10_TRAINER_5","name":"Hiker #8","location":"Route 10"},
    {"id":"9B6","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_5","name":"Hiker #9","location":"Rock Tunnel B1F"},
    {"id":"9B7","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_6","name":"Hiker #10","location":"Rock Tunnel B1F"},
    {"id":"9B8","flag":"EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_7","name":"Hiker #11","location":"Rock Tunnel B1F"},
    {"id":"45D","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_4","name":"Hiker #12","location":"Rock Tunnel 1F"},
    {"id":"45E","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_5","name":"Hiker #13","location":"Rock Tunnel 1F"},
    {"id":"45F","flag":"EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_6","name":"Hiker #14","location":"Rock Tunnel 1F"},
    {"id":"448","flag":"EVENT_BEAT_ROUTE_9_TRAINER_7","name":"Hiker #15","location":"Route 9"},
    {"id":"495","flag":"EVENT_BEAT_ROUTE_13_TRAINER_4","name":"Biker #1","location":"Route 13"},
    {"id":"4A1","flag":"EVENT_BEAT_ROUTE_14_TRAINER_0","name":"Biker #2","location":"Route 14"},
    {"id":"4B5","flag":"EVENT_BEAT_ROUTE_15_TRAINER_4","name":"Biker #3","location":"Route 15"},
    {"id":"4B6","flag":"EVENT_BEAT_ROUTE_15_TRAINER_5","name":"Biker #4","location":"Route 15"},
    {"id":"4C1","flag":"EVENT_BEAT_ROUTE_16_TRAINER_0","name":"Biker #5","location":"Route 16"},
    {"id":"4C2","flag":"EVENT_BEAT_ROUTE_16_TRAINER_1","name":"Biker #6","location":"Route 16"},
    {"id":"4C3","flag":"EVENT_BEAT_ROUTE_16_TRAINER_2","name":"Biker #7","location":"Route 16"},
    {"id":"4D1","flag":"EVENT_BEAT_ROUTE_17_TRAINER_0","name":"Biker #8","location":"Route 17"},
    {"id":"4D2","flag":"EVENT_BEAT_ROUTE_17_TRAINER_1","name":"Biker #9","location":"Route 17"},
    {"id":"4D3","flag":"EVENT_BEAT_ROUTE_17_TRAINER_2","name":"Biker #10","location":"Route 17"},
    {"id":"4D4","flag":"EVENT_BEAT_ROUTE_17_TRAINER_3","name":"Biker #11","location":"Route 17"},
    {"id":"4D5","flag":"EVENT_BEAT_ROUTE_17_TRAINER_4","name":"Biker #12","location":"Route 17"},
    {"id":"4A2","flag":"EVENT_BEAT_ROUTE_14_TRAINER_1","name":"Biker #13","location":"Route 14"},
    {"id":"4A3","flag":"EVENT_BEAT_ROUTE_14_TRAINER_2","name":"Biker #14","location":"Route 14"},
    {"id":"4A4","flag":"EVENT_BEAT_ROUTE_14_TRAINER_3","name":"Biker #15","location":"Route 14"},
    {"name":"Burglar Unused #1","obtainable":-1},
    {"name":"Burglar Unused #2","obtainable":-1},
    {"name":"Burglar Unused #3","obtainable":-1},
    {"id":"29E","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_4","name":"Burglar #1","location":"Cinnabar Gym"},
    {"id":"29F","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_5","name":"Burglar #2","location":"Cinnabar Gym"},
    {"id":"2A0","flag":"EVENT_BEAT_CINNABAR_GYM_TRAINER_6","name":"Burglar #3","location":"Cinnabar Gym"},
    {"id":"801","flag":"EVENT_BEAT_MANSION_2_TRAINER_0","name":"Burglar #4","location":"Mansion 2F"},
    {"id":"811","flag":"EVENT_BEAT_MANSION_3_TRAINER_0","name":"Burglar #5","location":"Mansion 3F"},
    {"id":"821","flag":"EVENT_BEAT_MANSION_4_TRAINER_0","name":"Burglar #6","location":"Mansion B1F"},
    {"name":"Engineer Unused #1","obtainable":-1},
    {"id":"475","flag":"EVENT_BEAT_ROUTE_11_TRAINER_4","name":"Engineer #1","location":"Route 11"},
    {"id":"476","flag":"EVENT_BEAT_ROUTE_11_TRAINER_5","name":"Engineer #2","location":"Route 11"},
    {"id":"602","flag":"EVENT_BEAT_SS_ANNE_9_TRAINER_1","name":"Fisher #1","location":"S.S. Anne 2F Rooms"},
    {"id":"616","flag":"EVENT_BEAT_SS_ANNE_10_TRAINER_5","name":"Fisher #2","location":"S.S. Anne B1F Rooms"},
    {"id":"483","flag":"EVENT_BEAT_ROUTE_12_TRAINER_1","name":"Fisher #3","location":"Route 12"},
    {"id":"484","flag":"EVENT_BEAT_ROUTE_12_TRAINER_2","name":"Fisher #4","location":"Route 12"},
    {"id":"485","flag":"EVENT_BEAT_ROUTE_12_TRAINER_3","name":"Fisher #5","location":"Route 12"},
    {"id":"486","flag":"EVENT_BEAT_ROUTE_12_TRAINER_4","name":"Fisher #6","location":"Route 12"},
    {"id":"511","flag":"EVENT_BEAT_ROUTE_21_TRAINER_0","name":"Fisher #7","location":"Route 21"},
    {"id":"512","flag":"EVENT_BEAT_ROUTE_21_TRAINER_1","name":"Fisher #8","location":"Route 21"},
    {"id":"513","flag":"EVENT_BEAT_ROUTE_21_TRAINER_2","name":"Fisher #9","location":"Route 21"},
    {"id":"514","flag":"EVENT_BEAT_ROUTE_21_TRAINER_3","name":"Fisher #10","location":"Route 21"},
    {"id":"487","flag":"EVENT_BEAT_ROUTE_12_TRAINER_5","name":"Fisher #11","location":"Route 12"},
    {"id":"0BB","flag":"EVENT_BEAT_CERULEAN_GYM_TRAINER_1","name":"Swimmer #1","location":"Cerulean Gym"},
    {"id":"4F1","flag":"EVENT_BEAT_ROUTE_19_TRAINER_0","name":"Swimmer #2","location":"Route 19"},
    {"id":"4F2","flag":"EVENT_BEAT_ROUTE_19_TRAINER_1","name":"Swimmer #3","location":"Route 19"},
    {"id":"4F3","flag":"EVENT_BEAT_ROUTE_19_TRAINER_2","name":"Swimmer #4","location":"Route 19"},
    {"id":"4F4","flag":"EVENT_BEAT_ROUTE_19_TRAINER_3","name":"Swimmer #5","location":"Route 19"},
    {"id":"4F5","flag":"EVENT_BEAT_ROUTE_19_TRAINER_4","name":"Swimmer #6","location":"Route 19"},
    {"id":"4F6","flag":"EVENT_BEAT_ROUTE_19_TRAINER_5","name":"Swimmer #7","location":"Route 19"},
    {"id":"4F7","flag":"EVENT_BEAT_ROUTE_19_TRAINER_6","name":"Swimmer #8","location":"Route 19"},
    {"id":"503","flag":"EVENT_BEAT_ROUTE_20_TRAINER_2","name":"Swimmer #9","location":"Route 20"},
    {"id":"504","flag":"EVENT_BEAT_ROUTE_20_TRAINER_3","name":"Swimmer #10","location":"Route 20"},
    {"id":"505","flag":"EVENT_BEAT_ROUTE_20_TRAINER_4","name":"Swimmer #11","location":"Route 20"},
    {"id":"515","flag":"EVENT_BEAT_ROUTE_21_TRAINER_4","name":"Swimmer #12","location":"Route 21"},
    {"id":"516","flag":"EVENT_BEAT_ROUTE_21_TRAINER_5","name":"Swimmer #13","location":"Route 21"},
    {"id":"517","flag":"EVENT_BEAT_ROUTE_21_TRAINER_6","name":"Swimmer #14","location":"Route 21"},
    {"id":"518","flag":"EVENT_BEAT_ROUTE_21_TRAINER_7","name":"Swimmer #15","location":"Route 21"},
    {"id":"4C4","flag":"EVENT_BEAT_ROUTE_16_TRAINER_3","name":"Cue Ball #1","location":"Route 16"},
    {"id":"4C5","flag":"EVENT_BEAT_ROUTE_16_TRAINER_4","name":"Cue Ball #2","location":"Route 16"},
    {"id":"4C6","flag":"EVENT_BEAT_ROUTE_16_TRAINER_5","name":"Cue Ball #3","location":"Route 16"},
    {"id":"4D6","flag":"EVENT_BEAT_ROUTE_17_TRAINER_5","name":"Cue Ball #4","location":"Route 17"},
    {"id":"4D7","flag":"EVENT_BEAT_ROUTE_17_TRAINER_6","name":"Cue Ball #5","location":"Route 17"},
    {"id":"4D8","flag":"EVENT_BEAT_ROUTE_17_TRAINER_7","name":"Cue Ball #6","location":"Route 17"},
    {"id":"4D9","flag":"EVENT_BEAT_ROUTE_17_TRAINER_8","name":"Cue Ball #7","location":"Route 17"},
    {"id":"4DA","flag":"EVENT_BEAT_ROUTE_17_TRAINER_9","name":"Cue Ball #8","location":"Route 17"},
    {"id":"519","flag":"EVENT_BEAT_ROUTE_21_TRAINER_8","name":"Cue Ball #9","location":"Route 21"},
    {"id":"477","flag":"EVENT_BEAT_ROUTE_11_TRAINER_6","name":"Gambler #1","location":"Route 11"},
    {"id":"478","flag":"EVENT_BEAT_ROUTE_11_TRAINER_7","name":"Gambler #2","location":"Route 11"},
    {"id":"479","flag":"EVENT_BEAT_ROUTE_11_TRAINER_8","name":"Gambler #3","location":"Route 11"},
    {"id":"47A","flag":"EVENT_BEAT_ROUTE_11_TRAINER_9","name":"Gambler #4","location":"Route 11"},
    {"id":"438","flag":"EVENT_BEAT_ROUTE_8_TRAINER_7","name":"Gambler #5","location":"Route 8"},
    {"name":"Gambler Unused #1","obtainable":-1},
    {"id":"439","flag":"EVENT_BEAT_ROUTE_8_TRAINER_8","name":"Gambler #6","location":"Route 8"},
    {"id":"1AD","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_3","name":"Beauty #1","location":"Celadon Gym"},
    {"id":"1AE","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_4","name":"Beauty #2","location":"Celadon Gym"},
    {"id":"1AF","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_5","name":"Beauty #3","location":"Celadon Gym"},
    {"id":"496","flag":"EVENT_BEAT_ROUTE_13_TRAINER_5","name":"Beauty #4","location":"Route 13"},
    {"id":"497","flag":"EVENT_BEAT_ROUTE_13_TRAINER_6","name":"Beauty #5","location":"Route 13"},
    {"id":"506","flag":"EVENT_BEAT_ROUTE_20_TRAINER_5","name":"Beauty #6","location":"Route 20"},
    {"id":"507","flag":"EVENT_BEAT_ROUTE_20_TRAINER_6","name":"Beauty #7","location":"Route 20"},
    {"id":"508","flag":"EVENT_BEAT_ROUTE_20_TRAINER_7","name":"Beauty #8","location":"Route 20"},
    {"id":"4B7","flag":"EVENT_BEAT_ROUTE_15_TRAINER_6","name":"Beauty #9","location":"Route 15"},
    {"id":"4B8","flag":"EVENT_BEAT_ROUTE_15_TRAINER_7","name":"Beauty #10","location":"Route 15"},
    {"name":"Beauty Unused #1","obtainable":-1},
    {"id":"4F8","flag":"EVENT_BEAT_ROUTE_19_TRAINER_7","name":"Beauty #11","location":"Route 19"},
    {"id":"4F9","flag":"EVENT_BEAT_ROUTE_19_TRAINER_8","name":"Beauty #12","location":"Route 19"},
    {"id":"4FA","flag":"EVENT_BEAT_ROUTE_19_TRAINER_9","name":"Beauty #13","location":"Route 19"},
    {"id":"509","flag":"EVENT_BEAT_ROUTE_20_TRAINER_8","name":"Beauty #14","location":"Route 20"},
    {"id":"362","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_0","name":"Psychic #1","location":"Saffron Gym"},
    {"id":"363","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_1","name":"Psychic #2","location":"Saffron Gym"},
    {"id":"364","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_2","name":"Psychic #3","location":"Saffron Gym"},
    {"id":"365","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_3","name":"Psychic #4","location":"Saffron Gym"},
    {"id":"163","flag":"EVENT_BEAT_VERMILION_GYM_TRAINER_1","name":"Rocker #1","location":"Vermilion Gym"},
    {"id":"488","flag":"EVENT_BEAT_ROUTE_12_TRAINER_6","name":"Rocker #2","location":"Route 12"},
    {"id":"722","flag":"EVENT_BEAT_SILPH_CO_5F_TRAINER_0","name":"Juggler #1","location":"Silph Co. 5F"},
    {"id":"53A","flag":"EVENT_BEAT_VICTORY_ROAD_2_TRAINER_1","name":"Juggler #2","location":"Victory Road 2F"},
    {"id":"25A","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_0","name":"Juggler #3","location":"Fuchsia Gym"},
    {"id":"25B","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_1","name":"Juggler #4","location":"Fuchsia Gym"},
    {"id":"53D","flag":"EVENT_BEAT_VICTORY_ROAD_2_TRAINER_4","name":"Juggler #5","location":"Victory Road 2F"},
    {"name":"Juggler Unused #1","obtainable":-1},
    {"id":"25C","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_2","name":"Juggler #6","location":"Fuchsia Gym"},
    {"id":"25D","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_3","name":"Juggler #7","location":"Fuchsia Gym"},
    {"id":"25E","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_4","name":"Tamer #1","location":"Fuchsia Gym"},
    {"id":"25F","flag":"EVENT_BEAT_FUCHSIA_GYM_TRAINER_5","name":"Tamer #2","location":"Fuchsia Gym"},
    {"id":"052","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_0","name":"Tamer #3","location":"Viridian Gym"},
    {"id":"053","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_1","name":"Tamer #4","location":"Viridian Gym"},
    {"id":"53B","flag":"EVENT_BEAT_VICTORY_ROAD_2_TRAINER_2","name":"Tamer #5","location":"Victory Road 2F"},
    {"name":"Tamer Unused #1","obtainable":-1},
    {"id":"498","flag":"EVENT_BEAT_ROUTE_13_TRAINER_7","name":"Bird Keeper #1","location":"Route 13"},
    {"id":"499","flag":"EVENT_BEAT_ROUTE_13_TRAINER_8","name":"Bird Keeper #2","location":"Route 13"},
    {"id":"49A","flag":"EVENT_BEAT_ROUTE_13_TRAINER_9","name":"Bird Keeper #3","location":"Route 13"},
    {"id":"4A5","flag":"EVENT_BEAT_ROUTE_14_TRAINER_4","name":"Bird Keeper #4","location":"Route 14"},
    {"id":"4A6","flag":"EVENT_BEAT_ROUTE_14_TRAINER_5","name":"Bird Keeper #5","location":"Route 14"},
    {"id":"4B9","flag":"EVENT_BEAT_ROUTE_15_TRAINER_8","name":"Bird Keeper #6","location":"Route 15"},
    {"id":"4BA","flag":"EVENT_BEAT_ROUTE_15_TRAINER_9","name":"Bird Keeper #7","location":"Route 15"},
    {"id":"4E1","flag":"EVENT_BEAT_ROUTE_18_TRAINER_0","name":"Bird Keeper #8","location":"Route 18"},
    {"id":"4E2","flag":"EVENT_BEAT_ROUTE_18_TRAINER_1","name":"Bird Keeper #9","location":"Route 18"},
    {"id":"4E3","flag":"EVENT_BEAT_ROUTE_18_TRAINER_2","name":"Bird Keeper #10","location":"Route 18"},
    {"id":"50A","flag":"EVENT_BEAT_ROUTE_20_TRAINER_9","name":"Bird Keeper #11","location":"Route 20"},
    {"name":"Bird Keeper Unused #1","obtainable":-1},
    {"name":"Bird Keeper Unused #2","obtainable":-1},
    {"id":"4A7","flag":"EVENT_BEAT_ROUTE_14_TRAINER_6","name":"Bird Keeper #12","location":"Route 14"},
    {"id":"4A8","flag":"EVENT_BEAT_ROUTE_14_TRAINER_7","name":"Bird Keeper #13","location":"Route 14"},
    {"id":"4A9","flag":"EVENT_BEAT_ROUTE_14_TRAINER_8","name":"Bird Keeper #14","location":"Route 14"},
    {"id":"4AA","flag":"EVENT_BEAT_ROUTE_14_TRAINER_9","name":"Bird Keeper #15","location":"Route 14"},
    {"id":"352","flag":"EVENT_BEAT_FIGHTING_DOJO_TRAINER_0","name":"Blackbelt #1","location":"Fighting Dojo"},
    {"id":"353","flag":"EVENT_BEAT_FIGHTING_DOJO_TRAINER_1","name":"Blackbelt #2","location":"Fighting Dojo"},
    {"id":"354","flag":"EVENT_BEAT_FIGHTING_DOJO_TRAINER_2","name":"Blackbelt #3","location":"Fighting Dojo"},
    {"id":"355","flag":"EVENT_BEAT_FIGHTING_DOJO_TRAINER_3","name":"Blackbelt #4","location":"Fighting Dojo"},
    {"id":"351","flag":"EVENT_BEAT_KARATE_MASTER","name":"Blackbelt #5","location":"Fighting Dojo"},
    {"id":"054","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_2","name":"Blackbelt #6","location":"Viridian Gym"},
    {"id":"055","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_3","name":"Blackbelt #7","location":"Viridian Gym"},
    {"id":"056","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_4","name":"Blackbelt #8","location":"Viridian Gym"},
    {"id":"539","flag":"EVENT_BEAT_VICTORY_ROAD_2_TRAINER_0","name":"Blackbelt #9","location":"Victory Road 2F"},
    {"id":"RivalOakLab","flag":"","name":"Rival #1","location":"Oak's Lab"},
    {"id":"525","flag":"EVENT_BEAT_ROUTE22_RIVAL_1ST_BATTLE","name":"Rival #2","location":"Route 22"},
    {"id":"098","flag":"EVENT_BEAT_CERULEAN_RIVAL","name":"Rival #3","location":"Cerulean City"},
    {"name":"Prof Oak Unused #1","obtainable":-1},
    {"name":"Prof Oak Unused #2","obtainable":-1},
    {"name":"Prof Oak Unused #3","obtainable":-1},
    {"name":"Scientist Unused #1","obtainable":-1},
    {"id":"6F2","flag":"EVENT_BEAT_SILPH_CO_2F_TRAINER_0","name":"Scientist #1","location":"Silph Co. 2F"},
    {"id":"6F3","flag":"EVENT_BEAT_SILPH_CO_2F_TRAINER_1","name":"Scientist #2","location":"Silph Co. 2F"},
    {"id":"702","flag":"EVENT_BEAT_SILPH_CO_3F_TRAINER_0","name":"Scientist #3","location":"Silph Co. 3F/Mansion 1F"},
    {"id":"712","flag":"EVENT_BEAT_SILPH_CO_4F_TRAINER_0","name":"Scientist #4","location":"Silph Co. 4F"},
    {"id":"723","flag":"EVENT_BEAT_SILPH_CO_5F_TRAINER_1","name":"Scientist #5","location":"Silph Co. 5F"},
    {"id":"736","flag":"EVENT_BEAT_SILPH_CO_6F_TRAINER_0","name":"Scientist #6","location":"Silph Co. 6F"},
    {"id":"745","flag":"EVENT_BEAT_SILPH_CO_7F_TRAINER_0","name":"Scientist #7","location":"Silph Co. 7F"},
    {"id":"752","flag":"EVENT_BEAT_SILPH_CO_8F_TRAINER_0","name":"Scientist #8","location":"Silph Co. 8F"},
    {"id":"762","flag":"EVENT_BEAT_SILPH_CO_9F_TRAINER_0","name":"Scientist #9","location":"Silph Co. 9F"},
    {"id":"771","flag":"EVENT_BEAT_SILPH_CO_10F_TRAINER_0","name":"Scientist #10","location":"Silph Co. 10F"},
    {"id":"812","flag":"EVENT_BEAT_MANSION_3_TRAINER_1","name":"Scientist #11","location":"Mansion 3F"},
    {"id":"822","flag":"EVENT_BEAT_MANSION_4_TRAINER_1","name":"Scientist #12","location":"Mansion B1F"},
    {"id":"289","flag":"EVENT_BEAT_MANSION_1_TRAINER_0","name":"Scientist #13","location":"Mansion 1F"},
    {"id":"6A7","flag":"EVENT_BEAT_ROCKET_HIDEOUT_GIOVANNI","name":"Giovanni #1","location":"Rocket Hideout B4F"},
    {"id":"78F","flag":"EVENT_BEAT_SILPH_CO_GIOVANNI","name":"Giovanni #2","location":"Silph Co. 11F"},
    {"id":"051","flag":"EVENT_BEAT_VIRIDIAN_GYM_GIOVANNI","name":"Giovanni #3","location":"Viridian Gym"},
    {"id":"57B","flag":"EVENT_BEAT_MT_MOON_3_TRAINER_1","name":"Rocket #1","location":"Mt. Moon B2F"},
    {"id":"57C","flag":"EVENT_BEAT_MT_MOON_3_TRAINER_2","name":"Rocket #2","location":"Mt. Moon B2F"},
    {"id":"57D","flag":"EVENT_BEAT_MT_MOON_3_TRAINER_3","name":"Rocket #3","location":"Mt. Moon B2F"},
    {"name":"Rocket Unused #1","obtainable":-1},
    {"id":"0A7","flag":"EVENT_BEAT_CERULEAN_ROCKET_THIEF","name":"Rocket #4","location":"Cerulean City"},
    {"id":"541","flag":"EVENT_BEAT_ROUTE24_ROCKET","name":"Rocket #5","location":"Route 24"},
    {"id":"RocketGameCorner","flag":"","name":"Rocket #6","location":"Game Corner"},
    {"id":"671","flag":"EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_0","name":"Rocket #7","location":"Rocket Hideout B1F"},
    {"id":"672","flag":"EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_1","name":"Rocket #8","location":"Rocket Hideout B1F"},
    {"id":"673","flag":"EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_2","name":"Rocket #9","location":"Rocket Hideout B1F"},
    {"id":"674","flag":"EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_3","name":"Rocket #10","location":"Rocket Hideout B1F"},
    {"id":"675","flag":"EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_4","name":"Rocket #11","location":"Rocket Hideout B1F"},
    {"id":"681","flag":"EVENT_BEAT_ROCKET_HIDEOUT_2_TRAINER_0","name":"Rocket #12","location":"Rocket Hideout B2F"},
    {"id":"691","flag":"EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_0","name":"Rocket #13","location":"Rocket Hideout B3F"},
    {"id":"692","flag":"EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_1","name":"Rocket #14","location":"Rocket Hideout B3F"},
    {"name":"Rocket Unused #2","obtainable":-1},
    {"name":"Rocket Unused #3","obtainable":-1},
    {"id":"6A4","flag":"EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_2","name":"Rocket #15","location":"Rocket Hideout B4F"},
    {"name":"Rocket Unused #4","obtainable":-1},
    {"name":"Rocket Unused #5","obtainable":-1},
    {"name":"Rocket Unused #6","obtainable":-1},
    {"name":"Rocket Unused #7","obtainable":-1},
    {"id":"6F4","flag":"EVENT_BEAT_SILPH_CO_2F_TRAINER_2","name":"Rocket #16","location":"Silph Co. 2F"},
    {"id":"6F5","flag":"EVENT_BEAT_SILPH_CO_2F_TRAINER_3","name":"Rocket #17","location":"Silph Co. 2F"},
    {"id":"703","flag":"EVENT_BEAT_SILPH_CO_3F_TRAINER_1","name":"Rocket #18","location":"Silph Co. 3F"},
    {"id":"713","flag":"EVENT_BEAT_SILPH_CO_4F_TRAINER_1","name":"Rocket #19","location":"Silph Co. 4F"},
    {"id":"714","flag":"EVENT_BEAT_SILPH_CO_4F_TRAINER_2","name":"Rocket #20","location":"Silph Co. 4F"},
    {"id":"724","flag":"EVENT_BEAT_SILPH_CO_5F_TRAINER_2","name":"Rocket #21","location":"Silph Co. 5F"},
    {"id":"725","flag":"EVENT_BEAT_SILPH_CO_5F_TRAINER_3","name":"Rocket #22","location":"Silph Co. 5F"},
    {"id":"737","flag":"EVENT_BEAT_SILPH_CO_6F_TRAINER_1","name":"Rocket #23","location":"Silph Co. 6F"},
    {"id":"738","flag":"EVENT_BEAT_SILPH_CO_6F_TRAINER_2","name":"Rocket #24","location":"Silph Co. 6F"},
    {"id":"746","flag":"EVENT_BEAT_SILPH_CO_7F_TRAINER_1","name":"Rocket #25","location":"Silph Co. 7F"},
    {"id":"747","flag":"EVENT_BEAT_SILPH_CO_7F_TRAINER_2","name":"Rocket #26","location":"Silph Co. 7F"},
    {"id":"748","flag":"EVENT_BEAT_SILPH_CO_7F_TRAINER_3","name":"Rocket #27","location":"Silph Co. 7F"},
    {"id":"753","flag":"EVENT_BEAT_SILPH_CO_8F_TRAINER_1","name":"Rocket #28","location":"Silph Co. 8F"},
    {"id":"754","flag":"EVENT_BEAT_SILPH_CO_8F_TRAINER_2","name":"Rocket #29","location":"Silph Co. 8F"},
    {"id":"763","flag":"EVENT_BEAT_SILPH_CO_9F_TRAINER_1","name":"Rocket #30","location":"Silph Co. 9F"},
    {"id":"764","flag":"EVENT_BEAT_SILPH_CO_9F_TRAINER_2","name":"Rocket #31","location":"Silph Co. 9F"},
    {"id":"772","flag":"EVENT_BEAT_SILPH_CO_10F_TRAINER_1","name":"Rocket #32","location":"Silph Co. 10F"},
    {"id":"785","flag":"EVENT_BEAT_SILPH_CO_11F_TRAINER_1","name":"Rocket #33","location":"Silph Co. 11F"},
    {"name":"Rocket Unused #8","obtainable":-1},
    {"id":"111","flag":"EVENT_BEAT_POKEMONTOWER_7_TRAINER_0","name":"Jessie & James #1","location":"Pokémon Tower 7F"},
    {"id":"57A","flag":"EVENT_BEAT_MT_MOON_3_TRAINER_0","name":"Jessie & James #2","location":"Mt. Moon B2F"},
    {"id":"6A2","flag":"EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_0","name":"Jessie & James #3","location":"Rocket Hideout B4F"},
    {"id":"784","flag":"EVENT_BEAT_SILPH_CO_11F_TRAINER_0","name":"Jessie & James #4","location":"Silph Co. 11F"},
    {"name":"Rocket Unused #9","obtainable":-1},
    {"name":"Rocket Unused #10","obtainable":-1},
    {"name":"Rocket Unused #11","obtainable":-1},
    {"name":"Rocket Unused #12","obtainable":-1},
    {"id":"057","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_5","name":"Cooltrainer (M) #1","location":"Viridian Gym"},
    {"id":"661","flag":"EVENT_BEAT_VICTORY_ROAD_3_TRAINER_0","name":"Cooltrainer (M) #2","location":"Victory Road 3F"},
    {"id":"662","flag":"EVENT_BEAT_VICTORY_ROAD_3_TRAINER_1","name":"Cooltrainer (M) #3","location":"Victory Road 3F"},
    {"name":"Cooltrainer (M) Unused #1","obtainable":-1},
    {"id":"911","flag":"EVENT_BEAT_VICTORY_ROAD_1_TRAINER_0","name":"Cooltrainer (M) #4","location":"Victory Road 1F"},
    {"name":"Cooltrainer (M) Unused #2","obtainable":-1},
    {"name":"Cooltrainer (M) Unused #3","obtainable":-1},
    {"name":"Cooltrainer (M) Unused #4","obtainable":-1},
    {"id":"058","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_6","name":"Cooltrainer (M) #5","location":"Viridian Gym"},
    {"id":"059","flag":"EVENT_BEAT_VIRIDIAN_GYM_TRAINER_7","name":"Cooltrainer (M) #6","location":"Viridian Gym"},
    {"id":"1B0","flag":"EVENT_BEAT_CELADON_GYM_TRAINER_6","name":"Cooltrainer (F) #1","location":"Celadon Gym"},
    {"id":"663","flag":"EVENT_BEAT_VICTORY_ROAD_3_TRAINER_2","name":"Cooltrainer (F) #2","location":"Victory Road 3F"},
    {"id":"664","flag":"EVENT_BEAT_VICTORY_ROAD_3_TRAINER_3","name":"Cooltrainer (F) #3","location":"Victory Road 3F"},
    {"name":"Cooltrainer (F) Unused #1","obtainable":-1},
    {"id":"912","flag":"EVENT_BEAT_VICTORY_ROAD_1_TRAINER_1","name":"Cooltrainer (F) #4","location":"Victory Road 1F"},
    {"name":"Cooltrainer (F) Unused #2","obtainable":-1},
    {"name":"Cooltrainer (F) Unused #3","obtainable":-1},
    {"name":"Cooltrainer (F) Unused #4","obtainable":-1},
    {"id":"8E9","flag":"EVENT_BEAT_BRUNOS_ROOM_TRAINER_0","name":"Bruno","location":""},
    {"id":"077","flag":"EVENT_BEAT_BROCK","name":"Brock","location":""},
    {"id":"0BF","flag":"EVENT_BEAT_MISTY","name":"Misty","location":""},
    {"id":"167","flag":"EVENT_BEAT_LT_SURGE","name":"LtSurge","location":""},
    {"id":"1A9","flag":"EVENT_BEAT_ERIKA","name":"Erika","location":"Celadon Gym"},
    {"id":"259","flag":"EVENT_BEAT_KOGA","name":"Koga","location":""},
    {"id":"299","flag":"EVENT_BEAT_BLAINE","name":"Blaine","location":""},
    {"id":"361","flag":"EVENT_BEAT_SABRINA","name":"Sabrina","location":""},
    {"id":"5F3","flag":"EVENT_BEAT_SS_ANNE_8_TRAINER_2","name":"Gentleman #1","location":"S.S. Anne 1F Rooms"},
    {"id":"5F4","flag":"EVENT_BEAT_SS_ANNE_8_TRAINER_3","name":"Gentleman #2","location":"S.S. Anne 1F Rooms"},
    {"id":"603","flag":"EVENT_BEAT_SS_ANNE_9_TRAINER_2","name":"Gentleman #3","location":"S.S. Anne 2F Rooms"},
    {"name":"Gentleman Unused #1","obtainable":-1},
    {"id":"604","flag":"EVENT_BEAT_SS_ANNE_9_TRAINER_3","name":"Gentleman #4","location":"S.S. Anne 2F Rooms"},
    {"id":"164","flag":"EVENT_BEAT_VERMILION_GYM_TRAINER_2","name":"Gentleman #5","location":"Vermilion Gym"},
    {"id":"RivalSSAnne","flag":"","name":"Rival #4","location":"S.S. Anne 2F"},
    {"id":"0EF","flag":"EVENT_BEAT_POKEMON_TOWER_RIVAL","name":"Rival #5 (Jolteon)","location":"Pokémon Tower 2F"},
    {"id":"0EF","flag":"EVENT_BEAT_POKEMON_TOWER_RIVAL","name":"Rival #5 (Flareon)","location":"Pokémon Tower 2F"},
    {"id":"0EF","flag":"EVENT_BEAT_POKEMON_TOWER_RIVAL","name":"Rival #5 (Vaporeon)","location":"Pokémon Tower 2F"},
    {"id":"740","flag":"EVENT_BEAT_SILPH_CO_RIVAL","name":"Rival #6 (Jolteon)","location":"Silph Co. 7F"},
    {"id":"740","flag":"EVENT_BEAT_SILPH_CO_RIVAL","name":"Rival #6 (Flareon)","location":"Silph Co. 7F"},
    {"id":"740","flag":"EVENT_BEAT_SILPH_CO_RIVAL","name":"Rival #6 (Vaporeon)","location":"Silph Co. 7F"},
    {"id":"526","flag":"EVENT_BEAT_ROUTE22_RIVAL_2ND_BATTLE","name":"Rival #7 (Jolteon)","location":"Route 22"},
    {"id":"526","flag":"EVENT_BEAT_ROUTE22_RIVAL_2ND_BATTLE","name":"Rival #7 (Flareon)","location":"Route 22"},
    {"id":"526","flag":"EVENT_BEAT_ROUTE22_RIVAL_2ND_BATTLE","name":"Rival #7 (Vaporeon)","location":"Route 22"},
    {"id":"901","flag":"EVENT_BEAT_CHAMPION_RIVAL","name":"Rival #8 (Jolteon)","location":"Indigo Plateau"},
    {"id":"901","flag":"EVENT_BEAT_CHAMPION_RIVAL","name":"Rival #8 (Flareon)","location":"Indigo Plateau"},
    {"id":"901","flag":"EVENT_BEAT_CHAMPION_RIVAL","name":"Rival #8 (Vaporeon)","location":"Indigo Plateau"},
    {"id":"8E1","flag":"EVENT_BEAT_LORELEIS_ROOM_TRAINER_0","name":"Lorelei","location":"Indigo Plateau"},
    {"name":"Channeler Unused #1","obtainable":-1},
    {"name":"Channeler Unused #2","obtainable":-1},
    {"name":"Channeler Unused #3","obtainable":-1},
    {"name":"Channeler Unused #4","obtainable":-1},
    {"id":"0F1","flag":"EVENT_BEAT_POKEMONTOWER_3_TRAINER_0","name":"Channeler #1","location":"Pokémon Tower 3F"},
    {"id":"0F2","flag":"EVENT_BEAT_POKEMONTOWER_3_TRAINER_1","name":"Channeler #2","location":"Pokémon Tower 3F"},
    {"name":"Channeler Unused #5","obtainable":-1},
    {"id":"0F3","flag":"EVENT_BEAT_POKEMONTOWER_3_TRAINER_2","name":"Channeler #3","location":"Pokémon Tower 3F"},
    {"id":"0F9","flag":"EVENT_BEAT_POKEMONTOWER_4_TRAINER_0","name":"Channeler #4","location":"Pokémon Tower 4F"},
    {"id":"0FA","flag":"EVENT_BEAT_POKEMONTOWER_4_TRAINER_1","name":"Channeler #5","location":"Pokémon Tower 4F"},
    {"name":"Channeler Unused #6","obtainable":-1},
    {"id":"0FB","flag":"EVENT_BEAT_POKEMONTOWER_4_TRAINER_2","name":"Channeler #6","location":"Pokémon Tower 4F"},
    {"name":"Channeler Unused #7","obtainable":-1},
    {"id":"102","flag":"EVENT_BEAT_POKEMONTOWER_5_TRAINER_0","name":"Channeler #7","location":"Pokémon Tower 5F"},
    {"name":"Channeler Unused #8","obtainable":-1},
    {"id":"103","flag":"EVENT_BEAT_POKEMONTOWER_5_TRAINER_1","name":"Channeler #8","location":"Pokémon Tower 5F"},
    {"id":"104","flag":"EVENT_BEAT_POKEMONTOWER_5_TRAINER_2","name":"Channeler #9","location":"Pokémon Tower 5F"},
    {"id":"105","flag":"EVENT_BEAT_POKEMONTOWER_5_TRAINER_3","name":"Channeler #10","location":"Pokémon Tower 5F"},
    {"id":"109","flag":"EVENT_BEAT_POKEMONTOWER_6_TRAINER_0","name":"Channeler #11","location":"Pokémon Tower 6F"},
    {"id":"10A","flag":"EVENT_BEAT_POKEMONTOWER_6_TRAINER_1","name":"Channeler #12","location":"Pokémon Tower 6F"},
    {"id":"10B","flag":"EVENT_BEAT_POKEMONTOWER_6_TRAINER_2","name":"Channeler #13","location":"Pokémon Tower 6F"},
    {"id":"366","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_4","name":"Channeler #14","location":"Saffron Gym"},
    {"id":"367","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_5","name":"Channeler #15","location":"Saffron Gym"},
    {"id":"368","flag":"EVENT_BEAT_SAFFRON_GYM_TRAINER_6","name":"Channeler #16","location":"Saffron Gym"},
    {"id":"8F1","flag":"EVENT_BEAT_AGATHAS_ROOM_TRAINER_0","name":"Agatha","location":"Indigo Plateau"},
    {"id":"8F9","flag":"EVENT_BEAT_LANCES_ROOM_TRAINER_0","name":"Lance","location":"Indigo Plateau"},
    {"id":"10F","flag":"EVENT_BEAT_GHOST_MAROWAK","name":"Ghost Marowak","location":"Pokémon Tower 6F"},
    {"id":"9DA","flag":"EVENT_BEAT_ARTICUNO","name":"Articuno","location":"Seafoam Islands B4F"},
    {"id":"469","flag":"EVENT_BEAT_ZAPDOS","name":"Zapdos","location":"Power Plant"},
    {"id":"53E","flag":"EVENT_BEAT_MOLTRES","name":"Moltres","location":"Victory Road 2F"},
    {"id":"8C1","flag":"EVENT_BEAT_MEWTWO","name":"Mewtwo","location":"Cerulean Cave B1F"},
    {"id":"461","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_0","name":"Voltorb #1","location":"Power Plant"},
    {"id":"462","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_1","name":"Voltorb #2","location":"Power Plant"},
    {"id":"463","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_2","name":"Voltorb #3","location":"Power Plant"},
    {"id":"464","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_3","name":"Voltorb #4","location":"Power Plant"},
    {"id":"465","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_4","name":"Voltorb #5","location":"Power Plant"},
    {"id":"466","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_5","name":"Voltorb #6","location":"Power Plant"},
    {"id":"467","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_6","name":"Voltorb #7","location":"Power Plant"},
    {"id":"468","flag":"EVENT_BEAT_POWER_PLANT_VOLTORB_7","name":"Voltorb #8","location":"Power Plant"},
    {"id":"48F","flag":"EVENT_BEAT_ROUTE12_SNORLAX","name":"Snorlax #1","location":"Route 12"},
    {"id":"4C9","flag":"EVENT_BEAT_ROUTE16_SNORLAX","name":"Snorlax #2","location":"Route 16"}
].map(a => {
    if(!a.id) return a;
   a.flagHex =  '0x' + a.id
   a.id = '' + (+('0x' + a.id));
   return a;
})).replace(/\},/g,'},\n');