import fs from "fs";

const b = ["PKM Trainer",
"PKM Trainer",
"Youngster",
"Lass",
"Camper",
"Picnicker",
"Bug Catcher",
"Aroma Lady",
"Twins",
"Hiker",
"Battle Girl",
"Fisherman",
"Cyclist",
"Cyclist",
"Black Belt",
"Artist",
"PKM Breeder",
"PKM Breeder",
"Cowgirl",
"Jogger",
"Pokéfan",
"Pokéfan",
"Poké Kid",
"Young Couple",
"Ace Trainer",
"Ace Trainer",
"Waitress",
"Veteran",
"Ninja Boy",
"Dragon Tamer",
"Bird Keeper",
"Double Team",
"Rich Boy",
"Lady",
"Gentleman",
"Socialite",
"Beauty",
"Collector",
"Policeman",
"PKM Ranger",
"PKM Ranger",
"Scientist",
"Swimmer♂",
"Swimmer♀",
"Tuber",
"Tuber",
"Sailor",
"Sis and Bro",
"Ruin Maniac",
"Psychic",
"Psychic",
"PI",
"Guitarist",
"Ace Trainer",
"Ace Trainer",
"Skier",
"Skier",
"Roughneck",
"Clown",
"Worker",
"School Kid",
"School Kid",
"Leader",
"PKM Trainer",
"Leader",
"Elite Four",
"Elite Four",
"Elite Four",
"Elite Four",
"Champion",
"Belle &amp; Pa",
"Rancher",
"Commander",
"Galactic",
"Leader",
"Leader",
"Leader",
"Leader",
"Leader",
"Leader",
"Parasol Lady",
"Waiter",
"Interviewers",
"Cameraman",
"Reporter",
"Idol",
"Galactic Boss",
"Commander",
"Commander",
"Galactic",
"PKM Trainer",
"PKM Trainer",
"PKM Trainer",
"PKM Trainer",
"PKM Trainer",
"PKM Trainer",
"PKM Trainer",
"Tower Tycoon",
"Maid",
"Hall Matron",
"Factory Head",
"Arcade Star",
"Castle Valet",
"PKM Trainer",
"PKM Trainer"
];

const c = [
"TRAINER_CLASS_PLAYER_MALE",
"TRAINER_CLASS_PLAYER_FEMALE",
"TRAINER_CLASS_YOUNGSTER",
"TRAINER_CLASS_LASS",
"TRAINER_CLASS_CAMPER",
"TRAINER_CLASS_PICNICKER",
"TRAINER_CLASS_BUG_CATCHER",
"TRAINER_CLASS_AROMA_LADY",
"TRAINER_CLASS_TWINS",
"TRAINER_CLASS_HIKER",
"TRAINER_CLASS_BATTLE_GIRL",
"TRAINER_CLASS_FISHERMAN",
"TRAINER_CLASS_CYCLIST_MALE",
"TRAINER_CLASS_CYCLIST_FEMALE",
"TRAINER_CLASS_BLACK_BELT",
"TRAINER_CLASS_ARTIST",
"TRAINER_CLASS_BREEDER_MALE",
"TRAINER_CLASS_BREEDER_FEMALE",
"TRAINER_CLASS_COWGIRL",
"TRAINER_CLASS_JOGGER",
"TRAINER_CLASS_POKEFAN_MALE",
"TRAINER_CLASS_POKEFAN_FEMALE",
"TRAINER_CLASS_POKE_KID",
"TRAINER_CLASS_YOUNG_COUPLE",
"TRAINER_CLASS_ACE_TRAINER_MALE",
"TRAINER_CLASS_ACE_TRAINER_FEMALE",
"TRAINER_CLASS_WAITRESS",
"TRAINER_CLASS_VETERAN",
"TRAINER_CLASS_NINJA_BOY",
"TRAINER_CLASS_DRAGON_TAMER",
"TRAINER_CLASS_BIRD_KEEPER",
"TRAINER_CLASS_DOUBLE_TEAM",
"TRAINER_CLASS_RICH_BOY",
"TRAINER_CLASS_LADY",
"TRAINER_CLASS_GENTLEMAN",
"TRAINER_CLASS_SOCIALITE",
"TRAINER_CLASS_BEAUTY",
"TRAINER_CLASS_COLLECTOR",
"TRAINER_CLASS_POLICEMAN",
"TRAINER_CLASS_RANGER_MALE",
"TRAINER_CLASS_RANGER_FEMALE",
"TRAINER_CLASS_SCIENTIST",
"TRAINER_CLASS_SWIMMER_MALE",
"TRAINER_CLASS_SWIMMER_FEMALE",
"TRAINER_CLASS_TUBER_MALE",
"TRAINER_CLASS_TUBER_FEMALE",
"TRAINER_CLASS_SAILOR",
"TRAINER_CLASS_SIS_AND_BRO",
"TRAINER_CLASS_RUIN_MANIAC",
"TRAINER_CLASS_PSYCHIC_MALE",
"TRAINER_CLASS_PSYCHIC_FEMALE",
"TRAINER_CLASS_PI",
"TRAINER_CLASS_GUITARIST",
"TRAINER_CLASS_ACE_TRAINER_SNOW_MALE",
"TRAINER_CLASS_ACE_TRAINER_SNOW_FEMALE",
"TRAINER_CLASS_SKIER_MALE",
"TRAINER_CLASS_SKIER_FEMALE",
"TRAINER_CLASS_ROUGHNECK",
"TRAINER_CLASS_CLOWN",
"TRAINER_CLASS_WORKER",
"TRAINER_CLASS_SCHOOL_KID_MALE",
"TRAINER_CLASS_SCHOOL_KID_FEMALE",
"TRAINER_CLASS_LEADER_ROARK",
"TRAINER_CLASS_RIVAL",
"TRAINER_CLASS_LEADER_BYRON",
"TRAINER_CLASS_ELITE_FOUR_AARON",
"TRAINER_CLASS_ELITE_FOUR_BERTHA",
"TRAINER_CLASS_ELITE_FOUR_FLINT",
"TRAINER_CLASS_ELITE_FOUR_LUCIAN",
"TRAINER_CLASS_CHAMPION_CYNTHIA",
"TRAINER_CLASS_BELLE_AND_PA",
"TRAINER_CLASS_RANCHER",
"TRAINER_CLASS_COMMANDER_MARS",
"TRAINER_CLASS_GALACTIC_GRUNT_MALE",
"TRAINER_CLASS_LEADER_GARDENIA",
"TRAINER_CLASS_LEADER_WAKE",
"TRAINER_CLASS_LEADER_MAYLENE",
"TRAINER_CLASS_LEADER_FANTINA",
"TRAINER_CLASS_LEADER_CANDICE",
"TRAINER_CLASS_LEADER_VOLKNER",
"TRAINER_CLASS_PARASOL_LADY",
"TRAINER_CLASS_WAITER",
"TRAINER_CLASS_INTERVIEWERS",
"TRAINER_CLASS_CAMERAMAN",
"TRAINER_CLASS_REPORTERS",
"TRAINER_CLASS_IDOL",
"TRAINER_CLASS_GALACTIC_BOSS",
"TRAINER_CLASS_COMMANDER_JUPITER",
"TRAINER_CLASS_COMMANDER_SATURN",
"TRAINER_CLASS_GALACTIC_GRUNT_FEMALE",
"TRAINER_CLASS_TRAINER_CHERYL",
"TRAINER_CLASS_TRAINER_RILEY",
"TRAINER_CLASS_TRAINER_MARLEY",
"TRAINER_CLASS_TRAINER_BUCK",
"TRAINER_CLASS_TRAINER_MIRA",
"TRAINER_CLASS_DP_PLAYER_MALE",
"TRAINER_CLASS_DP_PLAYER_FEMALE",
"TRAINER_CLASS_TOWER_TYCOON",
"TRAINER_CLASS_MAID",
"TRAINER_CLASS_HALL_MATRON",
"TRAINER_CLASS_FACTORY_HEAD",
"TRAINER_CLASS_ARCADE_STAR",
"TRAINER_CLASS_CASTLE_VALET",
"TRAINER_CLASS_DP_PLAYER_MALE_2",
"TRAINER_CLASS_DP_PLAYER_FEMALE_2",
]


/*
"name": "Carlos",
"class": "TRAINER_CLASS_PI",
*/

let count = new Map();
for(let idx = 0; idx < 928; idx++){
  const f = `C:\\Users\\Samuel\\source\\repos\\pokeplatinum\\res\\trainers\\${('' + idx).padStart(4, '0')}.json`;
  const f2 = JSON.parse(fs.readFileSync(f, 'utf8').trim());

  const type = b[c.indexOf(f2.class)] || 'error';
  const what = `${f2.name} (${type})`;
  let list = count.get(what);
  if (list === undefined)
    count.set(what, []);
  list = count.get(what);

  let num = list.length + 1;

  let numStr = num === 1 ? '' : ' #' + num;
  const s = `{"id":"${+idx}","name":"${what}${numStr}","location":"?"},`;
  list.push(s);
}

const list2 = Array.from(count.entries()).sort((a,b) => a[0] < b[0] ? -1 : 1);
let s = [];
for(const a of list2)
  s.push(...a[1]);
let s22 = s.join('\n');

console.log(s22);