//extract sky item location from
// https://gamefaqs.gamespot.com/ds/955859-pokemon-mystery-dungeon-explorers-of-sky/faqs/58190

// C:\rc\rainingchain\src\pokemonCompletion\utils\skyDungeon.txt
setTimeout(async () => {
  let res = new Map();
  let items2 = Array.from(new Set(items.filter(a => a.obtainable !== -1).map(a => a.name)));

  const lines = a.replace(/  +/g,' ').split('\n')
  let currentMap = '';

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    const m = line.match(/\d+\#\#\. (.*)/);
    if (m) {
      currentMap = m[1].trim();
      console.log(currentMap);
      continue;
    }
    if (!currentMap)
      continue;

    items2.forEach(item => {
      if(!line.includes(item + ' ('))
        return;

      let resList = res.get(item);
      if(!resList){
        resList = [];
        res.set(item, resList);
      }
      if (!resList.includes(currentMap))
        resList.push(currentMap);
    });
  }

  str = '';
  res.forEach((mapList,item) => {
    str += JSON.stringify({name:item, location:mapList.join(', ')}) + ',\n';
  });
  console.log(str);
}, 1000);

// dungeon location
setTimeout(async () => {
  let res = [];

  const lines = a.replace(/  +/g,' ').split('\n');
  let currentMap = '';

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    const m = line.match(/\d+\#\#\. (.*)/);
    if (m) {
      currentMap = m[1].trim();
      for (var j = i + 1; j < lines.length; j++) {
        if (lines[j][0] && lines[j][0].match(/\d/)){
          res.push({name:currentMap, location:lines.slice(i + 1, j).join(' ').replace('Requirements: ','').replace(/  +/g,' ')});
          break;
        }
      }
      continue;
    }
  }

  str = '';
  res.forEach((what,item) => {
    str += JSON.stringify(what) + ',\n';
  });
  console.log(str);
}, 1000);

setTimeout(async () => {
  let res = [];

  const lines = a.replace(/  +/g,' ').split('\n');
  let currentMap = '';

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    const m = line.match(/\d+\#\#\. (.*)/);
    if (m) {
      currentMap = m[1].trim();
      for (var j = i + 1; j < lines.length; j++) {
        if (lines[j][0] && lines[j][0].match(/\d/)){
          res.push({name:currentMap, location:lines.slice(i + 1, j).join(' ').replace('Requirements: ','').replace(/  +/g,' ')});
          break;
        }
      }
      continue;
    }
  }

  str = '';
  res.forEach((what,item) => {
    str += JSON.stringify(what) + ',\n';
  });
  console.log(str);
}, 1000);


let items = [
  {"id":"1","name":"Stick","location":"TODO"},
  {"id":"2","name":"Iron Thorn","location":"TODO"},
  {"id":"3","name":"Silver Spike","location":"TODO"},
  {"id":"4","name":"Gold Fang","location":"TODO"},
  {"id":"5","name":"Cacnea Spike","location":"TODO"},
  {"id":"6","name":"Corsola Twig","location":"TODO"},
  {"id":"7","name":"Gravelerock","location":"TODO"},
  {"id":"8","name":"Geo Pebble","location":"Various dungeons, Treasure Town shop"},
  {"id":"9","name":"Gold Thorn","location":"TODO"},
  {"id":"10","name":"Rare Fossil","location":"TODO"},
  {"id":"11","name":"$$","obtainable":-1},
  {"id":"12","name":"$$","obtainable":-1},
  {"id":"13","name":"No-Slip Cap","location":"TODO"},
  {"id":"14","name":"Y-Ray Specs","location":"TODO"},
  {"id":"15","name":"Gaggle Specs","location":"TODO"},
  {"id":"16","name":"Mobile Scarf","location":"TODO"},
  {"id":"17","name":"Heal Ribbon","location":"TODO"},
  {"id":"18","name":"Twist Band","location":"TODO"},
  {"id":"19","name":"Scope Lens","location":"TODO"},
  {"id":"20","name":"Patsy Band","location":"TODO"},
  {"id":"21","name":"No-Stick Cap","location":"TODO"},
  {"id":"22","name":"Pierce Band","location":"TODO"},
  {"id":"23","name":"Joy Ribbon","location":"TODO"},
  {"id":"24","name":"X-Ray Specs","location":"TODO"},
  {"id":"25","name":"Persim Band","location":"TODO"},
  {"id":"26","name":"Power Band","location":"TODO"},
  {"id":"27","name":"Pecha Scarf","location":"TODO"},
  {"id":"28","name":"Insomniscope","location":"TODO"},
  {"id":"29","name":"Warp Scarf","location":"TODO"},
  {"id":"30","name":"Tight Belt","location":"TODO"},
  {"id":"31","name":"Sneak Scarf","location":"TODO"},
  {"id":"32","name":"Gold Ribbon","location":"TODO"},
  {"id":"33","name":"Goggle Specs","location":"TODO"},
  {"id":"34","name":"Diet Ribbon","location":"TODO"},
  {"id":"35","name":"Trap Scarf","location":"TODO"},
  {"id":"36","name":"Racket Band","location":"TODO"},
  {"id":"37","name":"Def. Scarf","location":"TODO"},
  {"id":"38","name":"Stamina Band","location":"TODO"},
  {"id":"39","name":"Plain Ribbon","location":"TODO"},
  {"id":"40","name":"Special Band","location":"TODO"},
  {"id":"41","name":"Zinc Band","location":"TODO"},
  {"id":"42","name":"Detect Band","location":"TODO"},
  {"id":"43","name":"Space Globe","location":"TODO"},
  {"id":"44","name":"Dodge Scarf","location":"TODO"},
  {"id":"45","name":"Bounce Band","location":"TODO"},
  {"id":"46","name":"Curve Band","location":"TODO"},
  {"id":"47","name":"Whiff Specs","location":"TODO"},
  {"id":"48","name":"No-Aim Scope","location":"TODO"},
  {"id":"49","name":"Lockon Specs","location":"TODO"},
  {"id":"50","name":"Munch Belt","location":"TODO"},
  {"id":"51","name":"Pass Scarf","location":"TODO"},
  {"id":"52","name":"Weather Band","location":"TODO"},
  {"id":"53","name":"Friend Bow","location":"TODO"},
  {"id":"54","name":"Beauty Scarf","location":"TODO"},
  {"id":"55","name":"Sun Ribbon","location":"TODO"},
  {"id":"56","name":"Lunar Ribbon","location":"TODO"},
  {"id":"57","name":"Golden Mask","location":"TODO"},
  {"id":"58","name":"Amber Tear","location":"TODO"},
  {"id":"59","name":"Icy Flute","location":"Mt. Avalanche"},
  {"id":"60","name":"Fiery Drum","location":"Giant Volcano"},
  {"id":"61","name":"Terra Cymbal","location":"Shimmer Desert"},
  {"id":"62","name":"Aqua-Monica","location":"Bottomless Sea"},
  {"id":"63","name":"Rock Horn","location":"World Abyss"},
  {"id":"64","name":"Grass Cornet","location":"Mystery Jungle"},
  {"id":"65","name":"Sky Melodica","location":"Sky Stairway"},
  {"id":"66","name":"Miracle Chest","location":"TODO"},
  {"id":"67","name":"Wonder Chest","location":"TODO"},
  {"id":"68","name":"IQ Booster","location":"TODO"},
  {"id":"69","name":"Heal Seed","location":"TODO"},
  {"id":"70","name":"Oran Berry","location":"TODO"},
  {"id":"71","name":"Sitrus Berry","location":"TODO"},
  {"id":"72","name":"Eyedrop Seed","location":"TODO"},
  {"id":"73","name":"Reviver Seed","location":"TODO"},
  {"id":"74","name":"Blinker Seed","location":"TODO"},
  {"id":"75","name":"Doom Seed","location":"TODO"},
  {"id":"76","name":"X-Eye Seed","location":"TODO"},
  {"id":"77","name":"Life Seed","location":"TODO"},
  {"id":"78","name":"Rawst Berry","location":"TODO"},
  {"id":"79","name":"Hunger Seed","location":"TODO"},
  {"id":"80","name":"Quick Seed","location":"TODO"},
  {"id":"81","name":"Pecha Berry","location":"TODO"},
  {"id":"82","name":"Cheri Berry","location":"TODO"},
  {"id":"83","name":"Totter Seed","location":"TODO"},
  {"id":"84","name":"Sleep Seed","location":"TODO"},
  {"id":"85","name":"Plain Seed","location":"TODO"},
  {"id":"86","name":"Warp Seed","location":"TODO"},
  {"id":"87","name":"Blast Seed","location":"TODO"},
  {"id":"88","name":"Ginseng","location":"TODO"},
  {"id":"89","name":"Joy Seed","location":"TODO"},
  {"id":"90","name":"Chesto Berry","location":"TODO"},
  {"id":"91","name":"Stun Seed","location":"TODO"},
  {"id":"92","name":"Gabite Scale","location":"TODO"},
  {"id":"93","name":"Golden Seed","location":"TODO"},
  {"id":"94","name":"Vile Seed","location":"TODO"},
  {"id":"95","name":"Pure Seed","location":"TODO"},
  {"id":"96","name":"Violent Seed","location":"TODO"},
  {"id":"97","name":"Vanish Seed","location":"TODO"},
  {"id":"98","name":"$$","obtainable":-1},
  {"id":"99","name":"Max Elixir","location":"TODO"},
  {"id":"100","name":"Protein","location":"TODO"},
  {"id":"101","name":"Calcium","location":"TODO"},
  {"id":"102","name":"Iron","location":"TODO"},
  {"id":"103","name":"Nectar","location":"TODO"},
  {"id":"104","name":"Dropeye Seed","location":"TODO"},
  {"id":"105","name":"Reviser Seed","location":"TODO"},
  {"id":"106","name":"Slip Seed","location":"TODO"},
  {"id":"107","name":"Via Seed","location":"TODO"},
  {"id":"108","name":"Zinc","location":"TODO"},
  {"id":"109","name":"Apple","location":"TODO"},
  {"id":"110","name":"Big Apple","location":"TODO"},
  {"id":"111","name":"Grimy Food","location":"TODO"},
  {"id":"112","name":"Huge Apple","location":"TODO"},
  {"id":"113","name":"$$","obtainable":-1},
  {"id":"114","name":"$$","obtainable":-1},
  {"id":"115","name":"Golden Apple","location":"TODO"},
  {"id":"116","name":"Mix Elixir","location":"TODO"},
  {"id":"117","name":"Oren Berry","location":"TODO"},
  {"id":"118","name":"Dough Seed","location":"TODO"},
  {"id":"119","name":"White Gummi","location":"TODO"},
  {"id":"120","name":"Red Gummi","location":"TODO"},
  {"id":"121","name":"Blue Gummi","location":"TODO"},
  {"id":"122","name":"Grass Gummi","location":"TODO"},
  {"id":"123","name":"Yellow Gummi","location":"TODO"},
  {"id":"124","name":"Clear Gummi","location":"TODO"},
  {"id":"125","name":"Orange Gummi","location":"TODO"},
  {"id":"126","name":"Pink Gummi","location":"TODO"},
  {"id":"127","name":"Brown Gummi","location":"TODO"},
  {"id":"128","name":"Sky Gummi","location":"TODO"},
  {"id":"129","name":"Gold Gummi","location":"TODO"},
  {"id":"130","name":"Green Gummi","location":"TODO"},
  {"id":"131","name":"Gray Gummi","location":"TODO"},
  {"id":"132","name":"Purple Gummi","location":"TODO"},
  {"id":"133","name":"Royal Gummi","location":"TODO"},
  {"id":"134","name":"Black Gummi","location":"TODO"},
  {"id":"135","name":"Silver Gummi","location":"TODO"},
  {"id":"136","name":"Wonder Gummi","location":"TODO"},
  {"id":"137","name":"Gravelyrock","location":"TODO"},
  {"id":"138","name":"$$","obtainable":-1},
  {"id":"139","name":"Upgrade","location":"TODO"},
  {"id":"140","name":"King's Rock","location":"TODO"},
  {"id":"141","name":"Thunderstone","location":"TODO"},
  {"id":"142","name":"Deepseascale","location":"TODO"},
  {"id":"143","name":"Deepseatooth","location":"TODO"},
  {"id":"144","name":"Sun Stone","location":"TODO"},
  {"id":"145","name":"Moon Stone","location":"Treasure Boxes, Job requests (★3-★9), Mystifying Forest (Kecleon Shop: 5F, 7F, 9F, 11F, 13F), Lake Afar (Kecleon Shop: B3F, B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F), Midnight Forest (Kecleon Shop: B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F)"},
  {"id":"146","name":"Fire Stone","location":"Treasure Boxes, Job requests (★3-★9), Mystifying Forest (Kecleon Shop: 5F, 7F, 9F, 11F, 13F), Lake Afar (Kecleon Shop: B3F, B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F), Midnight Forest (Kecleon Shop: B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F)"},
  {"id":"147","name":"Water Stone","location":"Treasure Boxes, Job requests (★3-★9), Mystifying Forest (Kecleon Shop: 5F, 7F, 9F, 11F, 13F), Lake Afar (Kecleon Shop: B3F, B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F), Midnight Forest (Kecleon Shop: B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F)"},
  {"id":"148","name":"Metal Coat","location":"Treasure Boxes, Job requests (★3-★9), Mystifying Forest (Kecleon Shop: 5F, 7F, 9F, 11F, 13F), Lake Afar (Kecleon Shop: B3F, B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F), Midnight Forest (Kecleon Shop: B5F, B7F, B9F, B11F, B13F, B15F, B17F, B19F, B21F, B23F)"},
  {"id":"149","name":"Leaf Stone","location":"TODO"},
  {"id":"150","name":"Dragon Scale","location":"TODO"},
  {"id":"151","name":"Link Cable","location":"TODO"},
  {"id":"152","name":"Dubious Disc","location":"TODO"},
  {"id":"153","name":"Protector","location":"TODO"},
  {"id":"154","name":"Reaper Cloth","location":"TODO"},
  {"id":"155","name":"Razor Fang","location":"TODO"},
  {"id":"156","name":"Razor Claw","location":"TODO"},
  {"id":"157","name":"Electirizer","location":"TODO"},
  {"id":"158","name":"Magmarizer","location":"TODO"},
  {"id":"159","name":"Oval Stone","location":"TODO"},
  {"id":"160","name":"Dawn Stone","location":"TODO"},
  {"id":"161","name":"Shiny Stone","location":"TODO"},
  {"id":"162","name":"Dusk Stone","location":"TODO"},
  {"id":"163","name":"Coronet Rock","location":"TODO"},
  {"id":"164","name":"Mossy Rock","location":"TODO"},
  {"id":"165","name":"Frozen Rock","location":"TODO"},
  {"id":"166","name":"$$","obtainable":-1},
  {"id":"167","name":"Gone Pebble","location":"TODO"},
  {"id":"168","name":"Wander Gummi","location":"TODO"},
  {"id":"169","name":"Prize Ticket","location":"Spinda's Cafe"},
  {"id":"170","name":"Silver Ticket","location":"Spinda's Cafe"},
  {"id":"171","name":"Gold Ticket","location":"Spinda's Cafe"},
  {"id":"172","name":"Prism Ticket","location":"Spinda's Cafe"},
  {"id":"173","name":"Mystery Part","location":"Rewards from random missions after the player's team reaches Diamond Rank"},
  {"id":"174","name":"Secret Slab","location":"Rewards from random missions after the player's team reaches Diamond Rank"},
  {"id":"175","name":"$$","obtainable":-1},
  {"id":"176","name":"$$","obtainable":-1},
  {"id":"177","name":"$$","obtainable":-1},
  {"id":"178","name":"Wonder Egg","location":"TODO"},
  {"id":"179","name":"Gracidea","location":"TODO"},
  {"id":"180","name":"Sky Gift","location":"TODO"},
  {"id":"181","name":"$$","obtainable":-1},
  {"id":"182","name":"Key","location":"TODO"},
  {"id":"183","name":"Poké","location":"TODO"},
  {"id":"184","name":"$$","obtainable":-1},
  {"id":"185","name":"$$","obtainable":-1},
  {"id":"186","name":"Lost Loot","location":"TODO"},
  {"id":"187","name":"Used TM","location":"TODO"},
  {"id":"188","name":"Focus Punch","location":"TODO"},
  {"id":"189","name":"Dragon Claw","location":"TODO"},
  {"id":"190","name":"Water Pulse","location":"TODO"},
  {"id":"191","name":"Calm Mind","location":"TODO"},
  {"id":"192","name":"Roar","location":"TODO"},
  {"id":"193","name":"Toxic","location":"TODO"},
  {"id":"194","name":"Hail","location":"TODO"},
  {"id":"195","name":"Bulk Up","location":"TODO"},
  {"id":"196","name":"Bullet Seed","location":"TODO"},
  {"id":"197","name":"Hidden Power","location":"TODO"},
  {"id":"198","name":"$$","obtainable":-1},
  {"id":"199","name":"Taunt","location":"TODO"},
  {"id":"200","name":"Ice Beam","location":"TODO"},
  {"id":"201","name":"Blizzard","location":"TODO"},
  {"id":"202","name":"Hyper Beam","location":"TODO"},
  {"id":"203","name":"Light Screen","location":"TODO"},
  {"id":"204","name":"Protect","location":"TODO"},
  {"id":"205","name":"$$","obtainable":-1},
  {"id":"206","name":"Giga Drain","location":"TODO"},
  {"id":"207","name":"Safeguard","location":"TODO"},
  {"id":"208","name":"Frustration","location":"TODO"},
  {"id":"209","name":"SolarBeam","location":"TODO"},
  {"id":"210","name":"Iron Tail","location":"TODO"},
  {"id":"211","name":"Thunderbolt","location":"TODO"},
  {"id":"212","name":"Thunder","location":"TODO"},
  {"id":"213","name":"Earthquake","location":"TODO"},
  {"id":"214","name":"Return","location":"TODO"},
  {"id":"215","name":"Dig","location":"TODO"},
  {"id":"216","name":"Psychic","location":"TODO"},
  {"id":"217","name":"Shadow Ball","location":"TODO"},
  {"id":"218","name":"Brick Break","location":"TODO"},
  {"id":"219","name":"$$","obtainable":-1},
  {"id":"220","name":"Reflect","location":"TODO"},
  {"id":"221","name":"Shock Wave","location":"TODO"},
  {"id":"222","name":"Flamethrower","location":"TODO"},
  {"id":"223","name":"Sludge Bomb","location":"TODO"},
  {"id":"224","name":"$$","obtainable":-1},
  {"id":"225","name":"Fire Blast","location":"TODO"},
  {"id":"226","name":"$$","obtainable":-1},
  {"id":"227","name":"Aerial Ace","location":"TODO"},
  {"id":"228","name":"Torment","location":"TODO"},
  {"id":"229","name":"Facade","location":"TODO"},
  {"id":"230","name":"Secret Power","location":"TODO"},
  {"id":"231","name":"Rest","location":"TODO"},
  {"id":"232","name":"Attract","location":"TODO"},
  {"id":"233","name":"Thief","location":"TODO"},
  {"id":"234","name":"Steel Wing","location":"TODO"},
  {"id":"235","name":"Skill Swap","location":"TODO"},
  {"id":"236","name":"$$","obtainable":-1},
  {"id":"237","name":"Overheat","location":"TODO"},
  {"id":"238","name":"Roost","location":"TODO"},
  {"id":"239","name":"Focus Blast","location":"TODO"},
  {"id":"240","name":"Energy Ball","location":"TODO"},
  {"id":"241","name":"False Swipe","location":"TODO"},
  {"id":"242","name":"Brine","location":"TODO"},
  {"id":"243","name":"Fling","location":"TODO"},
  {"id":"244","name":"Charge Beam","location":"TODO"},
  {"id":"245","name":"Endure","location":"TODO"},
  {"id":"246","name":"Dragon Pulse","location":"TODO"},
  {"id":"247","name":"Drain Punch","location":"TODO"},
  {"id":"248","name":"Will-O-Wisp","location":"TODO"},
  {"id":"249","name":"Silver Wind","location":"TODO"},
  {"id":"250","name":"Embargo","location":"TODO"},
  {"id":"251","name":"Explosion","location":"TODO"},
  {"id":"252","name":"Shadow Claw","location":"TODO"},
  {"id":"253","name":"Payback","location":"TODO"},
  {"id":"254","name":"Recycle","location":"TODO"},
  {"id":"255","name":"Giga Impact","location":"TODO"},
  {"id":"256","name":"Rock Polish","location":"TODO"},
  {"id":"257","name":"Wide Slash","location":"TODO"},
  {"id":"258","name":"$$","obtainable":-1},
  {"id":"259","name":"$$","obtainable":-1},
  {"id":"260","name":"Vacuum-Cut","location":"TODO"},
  {"id":"261","name":"Dive","location":"TODO"},
  {"id":"262","name":"Flash","location":"TODO"},
  {"id":"263","name":"Stone Edge","location":"TODO"},
  {"id":"264","name":"Avalanche","location":"TODO"},
  {"id":"265","name":"Thunder Wave","location":"TODO"},
  {"id":"266","name":"Gyro Ball","location":"TODO"},
  {"id":"267","name":"Swords Dance","location":"TODO"},
  {"id":"268","name":"Stealth Rock","location":"TODO"},
  {"id":"269","name":"Psych Up","location":"TODO"},
  {"id":"270","name":"Captivate","location":"TODO"},
  {"id":"271","name":"Dark Pulse","location":"TODO"},
  {"id":"272","name":"Rock Slide","location":"TODO"},
  {"id":"273","name":"X-Scissor","location":"TODO"},
  {"id":"274","name":"Sleep Talk","location":"TODO"},
  {"id":"275","name":"Natural Gift","location":"TODO"},
  {"id":"276","name":"Poison Jab","location":"TODO"},
  {"id":"277","name":"Dream Eater","location":"TODO"},
  {"id":"278","name":"Grass Knot","location":"TODO"},
  {"id":"279","name":"Swagger","location":"TODO"},
  {"id":"280","name":"Pluck","location":"TODO"},
  {"id":"281","name":"U-turn","location":"TODO"},
  {"id":"282","name":"Substitute","location":"TODO"},
  {"id":"283","name":"Flash Cannon","location":"TODO"},
  {"id":"284","name":"Trick Room","location":"TODO"},
  {"id":"285","name":"Cut","location":"TODO"},
  {"id":"286","name":"Fly","location":"TODO"},
  {"id":"287","name":"Surf","location":"TODO"},
  {"id":"288","name":"Strength","location":"TODO"},
  {"id":"289","name":"Defog","location":"TODO"},
  {"id":"290","name":"Rock Smash","location":"TODO"},
  {"id":"291","name":"Waterfall","location":"TODO"},
  {"id":"292","name":"Rock Climb","location":"TODO"},
  {"id":"293","name":"$$","obtainable":-1},
  {"id":"294","name":"$$","obtainable":-1},
  {"id":"295","name":"$$","obtainable":-1},
  {"id":"296","name":"$$","obtainable":-1},
  {"id":"297","name":"$$","obtainable":-1},
  {"id":"298","name":"$$","obtainable":-1},
  {"id":"299","name":"$$","obtainable":-1},
  {"id":"300","name":"$$","obtainable":-1},
  {"id":"301","name":"Hail Orb","location":"TODO"},
  {"id":"302","name":"Sunny Orb","location":"TODO"},
  {"id":"303","name":"Rainy Orb","location":"TODO"},
  {"id":"304","name":"Evasion Orb","location":"TODO"},
  {"id":"305","name":"Sandy Orb","location":"TODO"},
  {"id":"306","name":"Rocky Orb","location":"TODO"},
  {"id":"307","name":"Snatch Orb","location":"TODO"},
  {"id":"308","name":"See-Trap Orb","location":"TODO"},
  {"id":"309","name":"Mug Orb","location":"TODO"},
  {"id":"310","name":"Rebound Orb","location":"TODO"},
  {"id":"311","name":"Lob Orb","location":"TODO"},
  {"id":"312","name":"Switcher Orb","location":"TODO"},
  {"id":"313","name":"Blowback Orb","location":"TODO"},
  {"id":"314","name":"Warp Orb","location":"TODO"},
  {"id":"315","name":"Transfer Orb","location":"TODO"},
  {"id":"316","name":"Slow Orb","location":"TODO"},
  {"id":"317","name":"Quick Orb","location":"TODO"},
  {"id":"318","name":"Luminous Orb","location":"TODO"},
  {"id":"319","name":"Petrify Orb","location":"TODO"},
  {"id":"320","name":"Stayaway Orb","location":"TODO"},
  {"id":"321","name":"Pounce Orb","location":"TODO"},
  {"id":"322","name":"Trawl Orb","location":"TODO"},
  {"id":"323","name":"Cleanse Orb","location":"TODO"},
  {"id":"324","name":"$$","obtainable":-1},
  {"id":"325","name":"Decoy Orb","location":"TODO"},
  {"id":"326","name":"Slumber Orb","location":"TODO"},
  {"id":"327","name":"Totter Orb","location":"TODO"},
  {"id":"328","name":"Two-Edge Orb","location":"TODO"},
  {"id":"329","name":"Silence Orb","location":"TODO"},
  {"id":"330","name":"Escape Orb","location":"TODO"},
  {"id":"331","name":"Scanner Orb","location":"TODO"},
  {"id":"332","name":"Radar Orb","location":"TODO"},
  {"id":"333","name":"Drought Orb","location":"TODO"},
  {"id":"334","name":"Trapbust Orb","location":"TODO"},
  {"id":"335","name":"Rollcall Orb","location":"TODO"},
  {"id":"336","name":"Invisify Orb","location":"TODO"},
  {"id":"337","name":"One-Shot Orb","location":"TODO"},
  {"id":"338","name":"Identify Orb","location":"TODO"},
  {"id":"339","name":"$$","obtainable":-1},
  {"id":"340","name":"Shocker Orb","location":"TODO"},
  {"id":"341","name":"Sizebust Orb","location":"TODO"},
  {"id":"342","name":"One-Room Orb","location":"TODO"},
  {"id":"343","name":"Fill-In Orb","location":"TODO"},
  {"id":"344","name":"Trapper Orb","location":"TODO"},
  {"id":"345","name":"$$","obtainable":-1},
  {"id":"346","name":"Itemizer Orb","location":"TODO"},
  {"id":"347","name":"Hurl Orb","location":"TODO"},
  {"id":"348","name":"Mobile Orb","location":"TODO"},
  {"id":"349","name":"$$","obtainable":-1},
  {"id":"350","name":"Stairs Orb","location":"TODO"},
  {"id":"351","name":"Longtoss Orb","location":"TODO"},
  {"id":"352","name":"Pierce Orb","location":"TODO"},
  {"id":"353","name":"$$","obtainable":-1},
  {"id":"354","name":"Spurn Orb","location":"TODO"},
  {"id":"355","name":"Foe-Hold Orb","location":"TODO"},
  {"id":"356","name":"All-Mach Orb","location":"TODO"},
  {"id":"357","name":"Foe-Fear Orb","location":"TODO"},
  {"id":"358","name":"All-Hit Orb","location":"TODO"},
  {"id":"359","name":"Foe-Seal Orb","location":"TODO"},
  {"id":"360","name":"$$","obtainable":-1},
  {"id":"361","name":"$$","obtainable":-1},
  {"id":"362","name":"Link Box","location":"TODO"},
  {"id":"363","name":"$$","obtainable":-1},
  {"id":"364","name":"Gorgeous Box","location":"TODO"},
  {"id":"365","name":"Gorgeous Box (2)","location":"TODO"},
  {"id":"366","name":"Gorgeous Box (3)","location":"TODO"},
  {"id":"367","name":"Heavy Box","location":"TODO"},
  {"id":"368","name":"Heavy Box (2)","location":"TODO"},
  {"id":"369","name":"Heavy Box (3)","location":"TODO"},
  {"id":"370","name":"Shiny Box","location":"TODO"},
  {"id":"371","name":"Shiny Box (2)","location":"TODO"},
  {"id":"372","name":"Shiny Box (3)","location":"TODO"},
  {"id":"373","name":"Nifty Box","location":"TODO"},
  {"id":"374","name":"Nifty Box (2)","location":"TODO"},
  {"id":"375","name":"Nifty Box (3)","location":"TODO"},
  {"id":"376","name":"Dainty Box","location":"TODO"},
  {"id":"377","name":"Dainty Box (2)","location":"TODO"},
  {"id":"378","name":"Dainty Box (3)","location":"TODO"},
  {"id":"379","name":"Glittery Box","location":"TODO"},
  {"id":"380","name":"Glittery Box (2)","location":"TODO"},
  {"id":"381","name":"Glittery Box (3)","location":"TODO"},
  {"id":"382","name":"Pretty Box","location":"TODO"},
  {"id":"383","name":"Pretty Box (2)","location":"TODO"},
  {"id":"384","name":"Pretty Box (3)","location":"TODO"},
  {"id":"385","name":"Deluxe Box","location":"TODO"},
  {"id":"386","name":"Deluxe Box (2)","location":"TODO"},
  {"id":"387","name":"Deluxe Box (3)","location":"TODO"},
  {"id":"388","name":"Light Box","location":"TODO"},
  {"id":"389","name":"Light Box (2)","location":"TODO"},
  {"id":"390","name":"Light Box (3)","location":"TODO"},
  {"id":"391","name":"Cute Box","location":"TODO"},
  {"id":"392","name":"Cute Box (2)","location":"TODO"},
  {"id":"393","name":"Cute Box (3)","location":"TODO"},
  {"id":"394","name":"Hard Box","location":"TODO"},
  {"id":"395","name":"Hard Box (2)","location":"TODO"},
  {"id":"396","name":"Hard Box (3)","location":"TODO"},
  {"id":"397","name":"Sinister Box","location":"TODO"},
  {"id":"398","name":"Sinister Box (2)","location":"TODO"},
  {"id":"399","name":"Sinister Box (3)","location":"TODO"},
  {"id":"400","name":"A-Stone","location":"TODO"},
  {"id":"401","name":"B-Stone","location":"TODO"},
  {"id":"402","name":"C-Stone","location":"TODO"},
  {"id":"403","name":"D-Stone","location":"TODO"},
  {"id":"404","name":"E-Stone","location":"TODO"},
  {"id":"405","name":"F-Stone","location":"TODO"},
  {"id":"406","name":"G-Stone","location":"TODO"},
  {"id":"407","name":"H-Stone","location":"TODO"},
  {"id":"408","name":"I-Stone","location":"TODO"},
  {"id":"409","name":"J-Stone","location":"TODO"},
  {"id":"410","name":"K-Stone","location":"TODO"},
  {"id":"411","name":"L-Stone","location":"TODO"},
  {"id":"412","name":"M-Stone","location":"TODO"},
  {"id":"413","name":"N-Stone","location":"TODO"},
  {"id":"414","name":"O-Stone","location":"TODO"},
  {"id":"415","name":"P-Stone","location":"TODO"},
  {"id":"416","name":"Q-Stone","location":"TODO"},
  {"id":"417","name":"R-Stone","location":"TODO"},
  {"id":"418","name":"S-Stone","location":"TODO"},
  {"id":"419","name":"T-Stone","location":"TODO"},
  {"id":"420","name":"U-Stone","location":"TODO"},
  {"id":"421","name":"V-Stone","location":"TODO"},
  {"id":"422","name":"W-Stone","location":"TODO"},
  {"id":"423","name":"X-Stone","location":"TODO"},
  {"id":"424","name":"Y-Stone","location":"TODO"},
  {"id":"425","name":"Z-Stone","location":"TODO"},
  {"id":"426","name":"!-Stone","location":"TODO"},
  {"id":"427","name":"?-Stone","location":"TODO"},
  {"id":"428","name":"Silver Bow","location":"TODO"},
  {"id":"429","name":"Brown Bow","location":"TODO"},
  {"id":"430","name":"Red Bow","location":"TODO"},
  {"id":"431","name":"Pink Bow","location":"TODO"},
  {"id":"432","name":"Orange Bow","location":"TODO"},
  {"id":"433","name":"Yellow Bow","location":"TODO"},
  {"id":"434","name":"Lime Bow","location":"TODO"},
  {"id":"435","name":"Green Bow","location":"TODO"},
  {"id":"436","name":"Viridian Bow","location":"TODO"},
  {"id":"437","name":"Minty Bow","location":"TODO"},
  {"id":"438","name":"Sky Blue Bow","location":"TODO"},
  {"id":"439","name":"Blue Bow","location":"TODO"},
  {"id":"440","name":"Cobalt Bow","location":"TODO"},
  {"id":"441","name":"Purple Bow","location":"TODO"},
  {"id":"442","name":"Violet Bow","location":"TODO"},
  {"id":"443","name":"Fuchsia Bow","location":"TODO"},
  {"id":"444","name":"Prism Ruff","location":"TODO"},
  {"id":"445","name":"Aqua Collar","location":"TODO"},
  {"id":"446","name":"Volt Collar","location":"TODO"},
  {"id":"447","name":"Fire Collar","location":"TODO"},
  {"id":"448","name":"Light Collar","location":"TODO"},
  {"id":"449","name":"Dusk Collar","location":"TODO"},
  {"id":"450","name":"Virid Collar","location":"TODO"},
  {"id":"451","name":"Icy Collar","location":"TODO"},
  {"id":"452","name":"Pep Sash","location":"TODO"},
  {"id":"453","name":"Counter Ruff","location":"TODO"},
  {"id":"454","name":"Victory Belt","location":"TODO"},
  {"id":"455","name":"Power Bangle","location":"TODO"},
  {"id":"456","name":"Thundershard","location":"TODO"},
  {"id":"457","name":"Fallen Star","location":"TODO"},
  {"id":"458","name":"Fluff Dust","location":"TODO"},
  {"id":"459","name":"Egg Shard","location":"TODO"},
  {"id":"460","name":"Heroic Medal","location":"TODO"},
  {"id":"461","name":"Chic Shard","location":"TODO"},
  {"id":"462","name":"Yellow Jewel","location":"TODO"},
  {"id":"463","name":"Red Jewel","location":"TODO"},
  {"id":"464","name":"Blue Jewel","location":"TODO"},
  {"id":"465","name":"Laugh Dust","location":"TODO"},
  {"id":"466","name":"Guard Sand","location":"TODO"},
  {"id":"467","name":"Purple Jewel","location":"TODO"},
  {"id":"468","name":"White Jewel","location":"TODO"},
  {"id":"469","name":"Brave Dust","location":"TODO"},
  {"id":"470","name":"Heal Dew","location":"TODO"},
  {"id":"471","name":"Marine Cache","location":"TODO"},
  {"id":"472","name":"Freeze Veil","location":"TODO"},
  {"id":"473","name":"Thunder Veil","location":"TODO"},
  {"id":"474","name":"Fire Veil","location":"TODO"},
  {"id":"475","name":"Havoc Robe","location":"TODO"},
  {"id":"476","name":"Life Ring","location":"TODO"},
  {"id":"477","name":"Bolt Fang","location":"TODO"},
  {"id":"478","name":"Flare Fang","location":"TODO"},
  {"id":"479","name":"Aqua Mantle","location":"TODO"},
  {"id":"480","name":"Silver Veil","location":"TODO"},
  {"id":"481","name":"Rainbow Veil","location":"TODO"},
  {"id":"482","name":"Chrono Veil","location":"TODO"},
  {"id":"483","name":"Rock Sash","location":"TODO"},
  {"id":"484","name":"Ice Sash","location":"TODO"},
  {"id":"485","name":"Steel Sash","location":"TODO"},
  {"id":"486","name":"Heart Brooch","location":"TODO"},
  {"id":"487","name":"Eon Veil","location":"TODO"},
  {"id":"488","name":"Seabed Veil","location":"TODO"},
  {"id":"489","name":"Terra Ring","location":"TODO"},
  {"id":"490","name":"SkyHigh Veil","location":"TODO"},
  {"id":"491","name":"Wish Mantle","location":"TODO"},
  {"id":"492","name":"Revive Robe","location":"TODO"},
  {"id":"493","name":"Shadow Veil","location":"TODO"},
  {"id":"494","name":"Plasma Veil","location":"TODO"},
  {"id":"495","name":"Edify Robe","location":"TODO"},
  {"id":"496","name":"Charity Robe","location":"TODO"},
  {"id":"497","name":"Hope Robe","location":"TODO"},
  {"id":"498","name":"Time Shield","location":"TODO"},
  {"id":"499","name":"Air Blade","location":"TODO"},
  {"id":"500","name":"Searing Ring","location":"TODO"},
  {"id":"501","name":"Ancient Ring","location":"TODO"},
  {"id":"502","name":"Nether Veil","location":"TODO"},
  {"id":"503","name":"Lunar Veil","location":"TODO"},
  {"id":"504","name":"Tidal Cape","location":"TODO"},
  {"id":"505","name":"Eclipse Robe","location":"TODO"},
  {"id":"506","name":"White Silk","location":"TODO"},
  {"id":"507","name":"Normal Dust","location":"TODO"},
  {"id":"508","name":"White Gem","location":"TODO"},
  {"id":"509","name":"Joy Globe","location":"TODO"},
  {"id":"510","name":"Red Silk","location":"TODO"},
  {"id":"511","name":"Fire Dust","location":"TODO"},
  {"id":"512","name":"Fiery Gem","location":"TODO"},
  {"id":"513","name":"Fiery Globe","location":"TODO"},
  {"id":"514","name":"Blue Silk","location":"TODO"},
  {"id":"515","name":"Water Dust","location":"TODO"},
  {"id":"516","name":"Aqua Gem","location":"TODO"},
  {"id":"517","name":"Aqua Globe","location":"TODO"},
  {"id":"518","name":"Grass Silk","location":"TODO"},
  {"id":"519","name":"Grass Dust","location":"TODO"},
  {"id":"520","name":"Grass Gem","location":"TODO"},
  {"id":"521","name":"Soothe Globe","location":"TODO"},
  {"id":"522","name":"Yellow Silk","location":"TODO"},
  {"id":"523","name":"Thunder Dust","location":"TODO"},
  {"id":"524","name":"Thunder Gem","location":"TODO"},
  {"id":"525","name":"Volt Globe","location":"TODO"},
  {"id":"526","name":"Clear Silk","location":"TODO"},
  {"id":"527","name":"Icy Dust","location":"TODO"},
  {"id":"528","name":"Icy Gem","location":"TODO"},
  {"id":"529","name":"Icy Globe","location":"TODO"},
  {"id":"530","name":"Orange Silk","location":"TODO"},
  {"id":"531","name":"Courage Dust","location":"TODO"},
  {"id":"532","name":"Fight Gem","location":"TODO"},
  {"id":"533","name":"Power Globe","location":"TODO"},
  {"id":"534","name":"Pink Silk","location":"TODO"},
  {"id":"535","name":"Poison Dust","location":"TODO"},
  {"id":"536","name":"Poison Gem","location":"TODO"},
  {"id":"537","name":"Poison Globe","location":"TODO"},
  {"id":"538","name":"Brown Silk","location":"TODO"},
  {"id":"539","name":"Ground Dust","location":"TODO"},
  {"id":"540","name":"Earth Gem","location":"TODO"},
  {"id":"541","name":"Terra Globe","location":"TODO"},
  {"id":"542","name":"Sky Silk","location":"TODO"},
  {"id":"543","name":"Sky Dust","location":"TODO"},
  {"id":"544","name":"Sky Gem","location":"TODO"},
  {"id":"545","name":"Sky Globe","location":"TODO"},
  {"id":"546","name":"Gold Silk","location":"TODO"},
  {"id":"547","name":"Psyche Dust","location":"TODO"},
  {"id":"548","name":"Psyche Gem","location":"TODO"},
  {"id":"549","name":"Psyche Globe","location":"TODO"},
  {"id":"550","name":"Green Silk","location":"TODO"},
  {"id":"551","name":"Wonder Dust","location":"TODO"},
  {"id":"552","name":"Guard Gem","location":"TODO"},
  {"id":"553","name":"Defend Globe","location":"TODO"},
  {"id":"554","name":"Gray Silk","location":"TODO"},
  {"id":"555","name":"Rock Dust","location":"TODO"},
  {"id":"556","name":"Stone Gem","location":"TODO"},
  {"id":"557","name":"Rock Globe","location":"TODO"},
  {"id":"558","name":"Purple Silk","location":"TODO"},
  {"id":"559","name":"Shady Dust","location":"TODO"},
  {"id":"560","name":"Shadow Gem","location":"TODO"},
  {"id":"561","name":"Nether Globe","location":"TODO"},
  {"id":"562","name":"Royal Silk","location":"TODO"},
  {"id":"563","name":"Dragon Dust","location":"TODO"},
  {"id":"564","name":"Dragon Gem","location":"TODO"},
  {"id":"565","name":"Dragon Globe","location":"TODO"},
  {"id":"566","name":"Black Silk","location":"TODO"},
  {"id":"567","name":"Dark Dust","location":"TODO"},
  {"id":"568","name":"Dark Gem","location":"TODO"},
  {"id":"569","name":"Dusk Globe","location":"TODO"},
  {"id":"570","name":"Iron Silk","location":"TODO"},
  {"id":"571","name":"Steel Dust","location":"TODO"},
  {"id":"572","name":"Metal Gem","location":"TODO"},
  {"id":"573","name":"Steel Globe","location":"TODO"},
  {"id":"574","name":"Bulba-Claw","location":"TODO"},
  {"id":"575","name":"Bulba-Fang","location":"TODO"},
  {"id":"576","name":"Grass-Guard","location":"TODO"},
  {"id":"577","name":"Leafy Tie","location":"TODO"},
  {"id":"578","name":"Ivy-Claw","location":"TODO"},
  {"id":"579","name":"Ivy-Fang","location":"TODO"},
  {"id":"580","name":"Ivy-Crest","location":"TODO"},
  {"id":"581","name":"Plant Torc","location":"TODO"},
  {"id":"582","name":"Venus-Claw","location":"TODO"},
  {"id":"583","name":"Venus-Fang","location":"TODO"},
  {"id":"584","name":"Venus-Seal","location":"TODO"},
  {"id":"585","name":"Solar Sash","location":"TODO"},
  {"id":"586","name":"Char-Claw","location":"TODO"},
  {"id":"587","name":"Char-Fang","location":"TODO"},
  {"id":"588","name":"Fiery Heart","location":"TODO"},
  {"id":"589","name":"Heat Armlet","location":"TODO"},
  {"id":"590","name":"Charme-Claw","location":"TODO"},
  {"id":"591","name":"Charme-Fang","location":"TODO"},
  {"id":"592","name":"Charme-Crest","location":"TODO"},
  {"id":"593","name":"Kindle Scarf","location":"TODO"},
  {"id":"594","name":"Chariz-Claw","location":"TODO"},
  {"id":"595","name":"Chariz-Fang","location":"TODO"},
  {"id":"596","name":"Chariz-Seal","location":"TODO"},
  {"id":"597","name":"Flame Bangle","location":"TODO"},
  {"id":"598","name":"Squirt-Foam","location":"TODO"},
  {"id":"599","name":"Squirt-Card","location":"TODO"},
  {"id":"600","name":"Water-Guard","location":"TODO"},
  {"id":"601","name":"Aqua Tie","location":"TODO"},
  {"id":"602","name":"Wartor-Claw","location":"TODO"},
  {"id":"603","name":"Wartor-Fang","location":"TODO"},
  {"id":"604","name":"Wartor-Crest","location":"TODO"},
  {"id":"605","name":"BubbleBangle","location":"TODO"},
  {"id":"606","name":"Blasto-Claw","location":"TODO"},
  {"id":"607","name":"Blasto-Card","location":"TODO"},
  {"id":"608","name":"Blasto-Seal","location":"TODO"},
  {"id":"609","name":"Hydro Band","location":"TODO"},
  {"id":"610","name":"Pichu Hair","location":"TODO"},
  {"id":"611","name":"Pichu Card","location":"TODO"},
  {"id":"612","name":"Express Tag","location":"TODO"},
  {"id":"613","name":"Shocker Cape","location":"TODO"},
  {"id":"614","name":"Pikachu Hair","location":"TODO"},
  {"id":"615","name":"Pikachu Card","location":"TODO"},
  {"id":"616","name":"Volt Charm","location":"TODO"},
  {"id":"617","name":"Volt Torc","location":"TODO"},
  {"id":"618","name":"Raichu Hair","location":"TODO"},
  {"id":"619","name":"Raichu Card","location":"TODO"},
  {"id":"620","name":"Raichu Crest","location":"TODO"},
  {"id":"621","name":"Zapper Scarf","location":"TODO"},
  {"id":"622","name":"Meowth Claw","location":"TODO"},
  {"id":"623","name":"Meowth Fang","location":"TODO"},
  {"id":"624","name":"Coin Charm","location":"TODO"},
  {"id":"625","name":"Bling Ruff","location":"TODO"},
  {"id":"626","name":"Persian Claw","location":"TODO"},
  {"id":"627","name":"Persian Fang","location":"TODO"},
  {"id":"628","name":"Insight Rock","location":"TODO"},
  {"id":"629","name":"Noble Scarf","location":"TODO"},
  {"id":"630","name":"Chiko-Claw","location":"TODO"},
  {"id":"631","name":"Chiko-Card","location":"TODO"},
  {"id":"632","name":"Dawn Jewel","location":"TODO"},
  {"id":"633","name":"Fresh Bow","location":"TODO"},
  {"id":"634","name":"Bayleef Claw","location":"TODO"},
  {"id":"635","name":"Bayleef Card","location":"TODO"},
  {"id":"636","name":"Bayleef Seal","location":"TODO"},
  {"id":"637","name":"Spice Bow","location":"TODO"},
  {"id":"638","name":"Megani-Claw","location":"TODO"},
  {"id":"639","name":"Megani-Card","location":"TODO"},
  {"id":"640","name":"Shiny Charm","location":"TODO"},
  {"id":"641","name":"Bright Veil","location":"TODO"},
  {"id":"642","name":"Cynda-Hair","location":"TODO"},
  {"id":"643","name":"Cynda-Claw","location":"TODO"},
  {"id":"644","name":"Blazing Rock","location":"TODO"},
  {"id":"645","name":"Storm Sash","location":"TODO"},
  {"id":"646","name":"Quila-Hair","location":"TODO"},
  {"id":"647","name":"Quila-Card","location":"TODO"},
  {"id":"648","name":"Quila-Crest","location":"TODO"},
  {"id":"649","name":"Volcano Torc","location":"TODO"},
  {"id":"650","name":"Typhlo-Gasp","location":"TODO"},
  {"id":"651","name":"Typhlo-Fang","location":"TODO"},
  {"id":"652","name":"Typhlo-Seal","location":"TODO"},
  {"id":"653","name":"Blast Bangle","location":"TODO"},
  {"id":"654","name":"Totodi-Dew","location":"TODO"},
  {"id":"655","name":"Totodi-Fang","location":"TODO"},
  {"id":"656","name":"Water Heart","location":"TODO"},
  {"id":"657","name":"Wash Bow","location":"TODO"},
  {"id":"658","name":"Croco-Fang","location":"TODO"},
  {"id":"659","name":"Croco-Card","location":"TODO"},
  {"id":"660","name":"Swirl Rock","location":"TODO"},
  {"id":"661","name":"Anger Scarf","location":"TODO"},
  {"id":"662","name":"Feral-Claw","location":"TODO"},
  {"id":"663","name":"Feral-Fang","location":"TODO"},
  {"id":"664","name":"Feral-Crest","location":"TODO"},
  {"id":"665","name":"Hydro Jaw","location":"TODO"},
  {"id":"666","name":"Treeck-Thorn","location":"TODO"},
  {"id":"667","name":"Treeck-Card","location":"TODO"},
  {"id":"668","name":"Forest Ore","location":"TODO"},
  {"id":"669","name":"Guard Ring","location":"TODO"},
  {"id":"670","name":"Grovy-Shoot","location":"TODO"},
  {"id":"671","name":"Grovy-Card","location":"TODO"},
  {"id":"672","name":"Jungle-Tag","location":"TODO"},
  {"id":"673","name":"Grass Blade","location":"TODO"},
  {"id":"674","name":"Scept-Claw","location":"TODO"},
  {"id":"675","name":"Scept-Card","location":"TODO"},
  {"id":"676","name":"Scept-Seal","location":"TODO"},
  {"id":"677","name":"Drain Bangle","location":"TODO"},
  {"id":"678","name":"Torchic Hair","location":"TODO"},
  {"id":"679","name":"Torchic Card","location":"TODO"},
  {"id":"680","name":"Hot Pebble","location":"TODO"},
  {"id":"681","name":"Fire Cape","location":"TODO"},
  {"id":"682","name":"Combus-Sweat","location":"TODO"},
  {"id":"683","name":"Combus-Claw","location":"TODO"},
  {"id":"684","name":"Charge Tag","location":"TODO"},
  {"id":"685","name":"Gutsy Band","location":"TODO"},
  {"id":"686","name":"Blazi-Claw","location":"TODO"},
  {"id":"687","name":"Blazi-Card","location":"TODO"},
  {"id":"688","name":"Blazi-Seal","location":"TODO"},
  {"id":"689","name":"Blaze Torc","location":"TODO"},
  {"id":"690","name":"Mudkip Mud","location":"TODO"},
  {"id":"691","name":"Mudkip Card","location":"TODO"},
  {"id":"692","name":"Mud Jewel","location":"TODO"},
  {"id":"693","name":"Speed Scarf","location":"TODO"},
  {"id":"694","name":"Marsh-Mud","location":"TODO"},
  {"id":"695","name":"Marsh-Card","location":"TODO"},
  {"id":"696","name":"Marsh-Crest","location":"TODO"},
  {"id":"697","name":"Marsh Torc","location":"TODO"},
  {"id":"698","name":"Swamp-Mud","location":"TODO"},
  {"id":"699","name":"Swamp-Card","location":"TODO"},
  {"id":"700","name":"Swamp-Seal","location":"TODO"},
  {"id":"701","name":"Swamp Bangle","location":"TODO"},
  {"id":"702","name":"Skitty Fang","location":"TODO"},
  {"id":"703","name":"Skitty Card","location":"TODO"},
  {"id":"704","name":"Smile Pebble","location":"TODO"},
  {"id":"705","name":"Heal Pendant","location":"TODO"},
  {"id":"706","name":"Delcat-Hair","location":"TODO"},
  {"id":"707","name":"Delcat-Fang","location":"TODO"},
  {"id":"708","name":"Prim Pebble","location":"TODO"},
  {"id":"709","name":"Guard Collar","location":"TODO"},
  {"id":"710","name":"Lucky Leaf","location":"TODO"},
  {"id":"711","name":"Turtwig Card","location":"TODO"},
  {"id":"712","name":"Sprout Rock","location":"TODO"},
  {"id":"713","name":"Leafy Hat","location":"TODO"},
  {"id":"714","name":"Grotle Twig","location":"TODO"},
  {"id":"715","name":"Grotle Claw","location":"TODO"},
  {"id":"716","name":"Grotle Crest","location":"TODO"},
  {"id":"717","name":"Woody Scarf","location":"TODO"},
  {"id":"718","name":"Tort-Claw","location":"TODO"},
  {"id":"719","name":"Tort-Horn","location":"TODO"},
  {"id":"720","name":"Tort-Seal","location":"TODO"},
  {"id":"721","name":"Forest Torc","location":"TODO"},
  {"id":"722","name":"Chim-Hair","location":"TODO"},
  {"id":"723","name":"Chim-Fang","location":"TODO"},
  {"id":"724","name":"Nimble Charm","location":"TODO"},
  {"id":"725","name":"Ember Cap","location":"TODO"},
  {"id":"726","name":"Monfer-Hair","location":"TODO"},
  {"id":"727","name":"Monfer-Fang","location":"TODO"},
  {"id":"728","name":"Monfer-Crest","location":"TODO"},
  {"id":"729","name":"Burst Sash","location":"TODO"},
  {"id":"730","name":"Infern-Hair","location":"TODO"},
  {"id":"731","name":"Infern-Fang","location":"TODO"},
  {"id":"732","name":"Infern-Seal","location":"TODO"},
  {"id":"733","name":"Blazing Ruff","location":"TODO"},
  {"id":"734","name":"Piplup Foam","location":"TODO"},
  {"id":"735","name":"Piplup Card","location":"TODO"},
  {"id":"736","name":"Sea Ore","location":"TODO"},
  {"id":"737","name":"Water Cape","location":"TODO"},
  {"id":"738","name":"Prin-Foam","location":"TODO"},
  {"id":"739","name":"Prin-Card","location":"TODO"},
  {"id":"740","name":"Prin-Crest","location":"TODO"},
  {"id":"741","name":"Aqua Blade","location":"TODO"},
  {"id":"742","name":"Empol-Claw","location":"TODO"},
  {"id":"743","name":"Empol-Horn","location":"TODO"},
  {"id":"744","name":"Empol-Seal","location":"TODO"},
  {"id":"745","name":"Marine Crown","location":"TODO"},
  {"id":"746","name":"Munch-Drool","location":"TODO"},
  {"id":"747","name":"Munch-Claw","location":"TODO"},
  {"id":"748","name":"Tummy Charm","location":"TODO"},
  {"id":"749","name":"Glutton Cape","location":"TODO"},
  {"id":"750","name":"Snorlax Gasp","location":"TODO"},
  {"id":"751","name":"Snorlax Fang","location":"TODO"},
  {"id":"752","name":"Valor Charm","location":"TODO"},
  {"id":"753","name":"Glee Scarf","location":"TODO"},
  {"id":"754","name":"Scyther Fang","location":"TODO"},
  {"id":"755","name":"Scyther Card","location":"TODO"},
  {"id":"756","name":"Ambush Rock","location":"TODO"},
  {"id":"757","name":"Strike Ruff","location":"TODO"},
  {"id":"758","name":"Scizor Wing","location":"TODO"},
  {"id":"759","name":"Scizor Card","location":"TODO"},
  {"id":"760","name":"Steel Charm","location":"TODO"},
  {"id":"761","name":"Red Armlet","location":"TODO"},
  {"id":"762","name":"Lapras Song","location":"TODO"},
  {"id":"763","name":"Lapras Card","location":"TODO"},
  {"id":"764","name":"Wavy Charm","location":"TODO"},
  {"id":"765","name":"Mystic Scarf","location":"TODO"},
  {"id":"766","name":"Eevee Tail","location":"TODO"},
  {"id":"767","name":"Eevee Card","location":"TODO"},
  {"id":"768","name":"Evolve Charm","location":"TODO"},
  {"id":"769","name":"Eevee","location":"TODO"},
  {"id":"770","name":"Cleffa Dew","location":"TODO"},
  {"id":"771","name":"Cleffa Card","location":"TODO"},
  {"id":"772","name":"Starry Ore","location":"TODO"},
  {"id":"773","name":"Comet Ring","location":"TODO"},
  {"id":"774","name":"Clef-Claw","location":"TODO"},
  {"id":"775","name":"Clef-Fang","location":"TODO"},
  {"id":"776","name":"Moon Jewel","location":"TODO"},
  {"id":"777","name":"Moon Scarf","location":"TODO"},
  {"id":"778","name":"Clefa-Claw","location":"TODO"},
  {"id":"779","name":"Clefa-Card","location":"TODO"},
  {"id":"780","name":"Moon Rock","location":"TODO"},
  {"id":"781","name":"Fairy Bow","location":"TODO"},
  {"id":"782","name":"Iggly-Dew","location":"TODO"},
  {"id":"783","name":"Iggly-Card","location":"TODO"},
  {"id":"784","name":"Bouncy Charm","location":"TODO"},
  {"id":"785","name":"Pretty Bow","location":"TODO"},
  {"id":"786","name":"Jiggly-Song","location":"TODO"},
  {"id":"787","name":"Jiggly-Card","location":"TODO"},
  {"id":"788","name":"Slumber Rock","location":"TODO"},
  {"id":"789","name":"Snooze Ring","location":"TODO"},
  {"id":"790","name":"Wiggly-Hair","location":"TODO"},
  {"id":"791","name":"Wiggly-Card","location":"TODO"},
  {"id":"792","name":"Buddy Rock","location":"TODO"},
  {"id":"793","name":"Friend Torc","location":"TODO"},
  {"id":"794","name":"Togepi Dew","location":"TODO"},
  {"id":"795","name":"Togepi Card","location":"TODO"},
  {"id":"796","name":"Pure Heart","location":"TODO"},
  {"id":"797","name":"Angel Scarf","location":"TODO"},
  {"id":"798","name":"Togetic Wing","location":"TODO"},
  {"id":"799","name":"Togetic Card","location":"TODO"},
  {"id":"800","name":"Happy Rock","location":"TODO"},
  {"id":"801","name":"Luck Brooch","location":"TODO"},
  {"id":"802","name":"Togek-Wing","location":"TODO"},
  {"id":"803","name":"Togek-Card","location":"TODO"},
  {"id":"804","name":"Ovation Rock","location":"TODO"},
  {"id":"805","name":"Glitter Robe","location":"TODO"},
  {"id":"806","name":"Sneasel Claw","location":"TODO"},
  {"id":"807","name":"Sneasel Card","location":"TODO"},
  {"id":"808","name":"Dusk Jewel","location":"TODO"},
  {"id":"809","name":"Cruel Ring","location":"TODO"},
  {"id":"810","name":"Weavile Claw","location":"TODO"},
  {"id":"811","name":"Weavile Fang","location":"TODO"},
  {"id":"812","name":"Vile Tag","location":"TODO"},
  {"id":"813","name":"Ruin Armlet","location":"TODO"},
  {"id":"814","name":"Teddi-Claw","location":"TODO"},
  {"id":"815","name":"Teddi-Card","location":"TODO"},
  {"id":"816","name":"Honey Rock","location":"TODO"},
  {"id":"817","name":"Heal Scarf","location":"TODO"},
  {"id":"818","name":"Ursa-Claw","location":"TODO"},
  {"id":"819","name":"Ursa-Fang","location":"TODO"},
  {"id":"820","name":"Calming Rock","location":"TODO"},
  {"id":"821","name":"Hiber Scarf","location":"TODO"},
  {"id":"822","name":"Tyro-Sweat","location":"TODO"},
  {"id":"823","name":"Tyro-Card","location":"TODO"},
  {"id":"824","name":"Muscle Charm","location":"TODO"},
  {"id":"825","name":"Tyrogue","location":"TODO"},
  {"id":"826","name":"Smooch-Song","location":"TODO"},
  {"id":"827","name":"Smooch-Card","location":"TODO"},
  {"id":"828","name":"Kiss Charm","location":"TODO"},
  {"id":"829","name":"Heart Tiara","location":"TODO"},
  {"id":"830","name":"Jynx Song","location":"TODO"},
  {"id":"831","name":"Jynx Card","location":"TODO"},
  {"id":"832","name":"Frozen Ore","location":"TODO"},
  {"id":"833","name":"Ruin Scarf","location":"TODO"},
  {"id":"834","name":"Elekid Claw","location":"TODO"},
  {"id":"835","name":"Elekid Card","location":"TODO"},
  {"id":"836","name":"Jolt Charm","location":"TODO"},
  {"id":"837","name":"Current Ring","location":"TODO"},
  {"id":"838","name":"Electa-Claw","location":"TODO"},
  {"id":"839","name":"Electa-Fang","location":"TODO"},
  {"id":"840","name":"Charge Seal","location":"TODO"},
  {"id":"841","name":"Volt Bangle","location":"TODO"},
  {"id":"842","name":"Electi-Claw","location":"TODO"},
  {"id":"843","name":"Electi-Card","location":"TODO"},
  {"id":"844","name":"Voltaic Rock","location":"TODO"},
  {"id":"845","name":"Voltaic Band","location":"TODO"},
  {"id":"846","name":"Magby Claw","location":"TODO"},
  {"id":"847","name":"Magby Card","location":"TODO"},
  {"id":"848","name":"Ember Jewel","location":"TODO"},
  {"id":"849","name":"Coal Ring","location":"TODO"},
  {"id":"850","name":"Magmar Claw","location":"TODO"},
  {"id":"851","name":"Magmar Card","location":"TODO"},
  {"id":"852","name":"Erupt Ore","location":"TODO"},
  {"id":"853","name":"Magma Scarf","location":"TODO"},
  {"id":"854","name":"Magmor-Claw","location":"TODO"},
  {"id":"855","name":"Magmor-Card","location":"TODO"},
  {"id":"856","name":"Vulcan Rock","location":"TODO"},
  {"id":"857","name":"Burning Torc","location":"TODO"},
  {"id":"858","name":"Azuri-Dew","location":"TODO"},
  {"id":"859","name":"Azuri-Card","location":"TODO"},
  {"id":"860","name":"Fount Charm","location":"TODO"},
  {"id":"861","name":"Water Float","location":"TODO"},
  {"id":"862","name":"Marill Dew","location":"TODO"},
  {"id":"863","name":"Marill Card","location":"TODO"},
  {"id":"864","name":"Surfer Rock","location":"TODO"},
  {"id":"865","name":"Brine Scarf","location":"TODO"},
  {"id":"866","name":"Azuma-Dew","location":"TODO"},
  {"id":"867","name":"Azuma-Card","location":"TODO"},
  {"id":"868","name":"Stream Charm","location":"TODO"},
  {"id":"869","name":"Dotted Scarf","location":"TODO"},
  {"id":"870","name":"Plusle Tail","location":"TODO"},
  {"id":"871","name":"Plusle Card","location":"TODO"},
  {"id":"872","name":"Cheer Rock","location":"TODO"},
  {"id":"873","name":"Pulse Bow","location":"TODO"},
  {"id":"874","name":"Minun Tail","location":"TODO"},
  {"id":"875","name":"Minun Card","location":"TODO"},
  {"id":"876","name":"Volt Heart","location":"TODO"},
  {"id":"877","name":"Spark Tie","location":"TODO"},
  {"id":"878","name":"Cast-Dew","location":"TODO"},
  {"id":"879","name":"Cast-Card","location":"TODO"},
  {"id":"880","name":"Cloud Rock","location":"TODO"},
  {"id":"881","name":"Weather Cape","location":"TODO"},
  {"id":"882","name":"Wynaut Tail","location":"TODO"},
  {"id":"883","name":"Wynaut Card","location":"TODO"},
  {"id":"884","name":"Grin Charm","location":"TODO"},
  {"id":"885","name":"Cheery Scarf","location":"TODO"},
  {"id":"886","name":"Wobbu-Sweat","location":"TODO"},
  {"id":"887","name":"Wobbu-Card","location":"TODO"},
  {"id":"888","name":"Endure Rock","location":"TODO"},
  {"id":"889","name":"Suffer Scarf","location":"TODO"},
  {"id":"890","name":"Bidoof Tooth","location":"TODO"},
  {"id":"891","name":"Bidoof Card","location":"TODO"},
  {"id":"892","name":"Fall Charm","location":"TODO"},
  {"id":"893","name":"Stolid Scarf","location":"TODO"},
  {"id":"894","name":"Biba-Tooth","location":"TODO"},
  {"id":"895","name":"Biba-Card","location":"TODO"},
  {"id":"896","name":"River Charm","location":"TODO"},
  {"id":"897","name":"Dam Scarf","location":"TODO"},
  {"id":"898","name":"Shinx Claw","location":"TODO"},
  {"id":"899","name":"Shinx Fang","location":"TODO"},
  {"id":"900","name":"Flash Tag","location":"TODO"},
  {"id":"901","name":"Energy Scarf","location":"TODO"},
  {"id":"902","name":"Luxio Claw","location":"TODO"},
  {"id":"903","name":"Luxio Fang","location":"TODO"},
  {"id":"904","name":"Spark Tag","location":"TODO"},
  {"id":"905","name":"Spark Scarf","location":"TODO"},
  {"id":"906","name":"Luxray Claw","location":"TODO"},
  {"id":"907","name":"Luxray Fang","location":"TODO"},
  {"id":"908","name":"Glare Tag","location":"TODO"},
  {"id":"909","name":"Glare Sash","location":"TODO"},
  {"id":"910","name":"Pachi-Tooth","location":"TODO"},
  {"id":"911","name":"Pachi-Card","location":"TODO"},
  {"id":"912","name":"Rouse Charm","location":"TODO"},
  {"id":"913","name":"Miracle Bow","location":"TODO"},
  {"id":"914","name":"Buizel Fang","location":"TODO"},
  {"id":"915","name":"Buizel Card","location":"TODO"},
  {"id":"916","name":"Swimmer Rock","location":"TODO"},
  {"id":"917","name":"Screw Torc","location":"TODO"},
  {"id":"918","name":"Float-Fang","location":"TODO"},
  {"id":"919","name":"Float-Card","location":"TODO"},
  {"id":"920","name":"Rescue Rock","location":"TODO"},
  {"id":"921","name":"Float Aid","location":"TODO"},
  {"id":"922","name":"Drifloo-Gasp","location":"TODO"},
  {"id":"923","name":"Drifloo-Card","location":"TODO"},
  {"id":"924","name":"Wind Heart","location":"TODO"},
  {"id":"925","name":"Draft Ring","location":"TODO"},
  {"id":"926","name":"Drifbli-Gasp","location":"TODO"},
  {"id":"927","name":"Drifbli-Card","location":"TODO"},
  {"id":"928","name":"Easy Charm","location":"TODO"},
  {"id":"929","name":"Breeze Scarf","location":"TODO"},
  {"id":"930","name":"Cherubi Seed","location":"TODO"},
  {"id":"931","name":"Cherubi Card","location":"TODO"},
  {"id":"932","name":"Cute Ore","location":"TODO"},
  {"id":"933","name":"Charm Bow","location":"TODO"},
  {"id":"934","name":"Cherrim Dew","location":"TODO"},
  {"id":"935","name":"Cherrim Card","location":"TODO"},
  {"id":"936","name":"Sweet Aroma","location":"TODO"},
  {"id":"937","name":"Petal Dress","location":"TODO"},
  {"id":"938","name":"Bonsly Dew","location":"TODO"},
  {"id":"939","name":"Bonsly Card","location":"TODO"},
  {"id":"940","name":"Arid Tag","location":"TODO"},
  {"id":"941","name":"Teary Cape","location":"TODO"},
  {"id":"942","name":"Sudo-Sweat","location":"TODO"},
  {"id":"943","name":"Sudo-Card","location":"TODO"},
  {"id":"944","name":"Drain Rock","location":"TODO"},
  {"id":"945","name":"Fake Torc","location":"TODO"},
  {"id":"946","name":"Junior Beam","location":"TODO"},
  {"id":"947","name":"Junior Card","location":"TODO"},
  {"id":"948","name":"Mimic Pebble","location":"TODO"},
  {"id":"949","name":"Copy Mask","location":"TODO"},
  {"id":"950","name":"Mime Key","location":"TODO"},
  {"id":"951","name":"Mime Card","location":"TODO"},
  {"id":"952","name":"Bulwark Rock","location":"TODO"},
  {"id":"953","name":"Barrier Bow","location":"TODO"},
  {"id":"954","name":"Happiny Dew","location":"TODO"},
  {"id":"955","name":"Happiny Card","location":"TODO"},
  {"id":"956","name":"Play Tag","location":"TODO"},
  {"id":"957","name":"Nurture Cape","location":"TODO"},
  {"id":"958","name":"Chansey Song","location":"TODO"},
  {"id":"959","name":"Chansey Card","location":"TODO"},
  {"id":"960","name":"Lucky Charm","location":"TODO"},
  {"id":"961","name":"Lucky Scarf","location":"TODO"},
  {"id":"962","name":"Blissey Song","location":"TODO"},
  {"id":"963","name":"Blissey Card","location":"TODO"},
  {"id":"964","name":"Amity Rock","location":"TODO"},
  {"id":"965","name":"Faith Ring","location":"TODO"},
  {"id":"966","name":"Gible Fang","location":"TODO"},
  {"id":"967","name":"Gible Card","location":"TODO"},
  {"id":"968","name":"Dragon Jewel","location":"TODO"},
  {"id":"969","name":"Dragon Tie","location":"TODO"},
  {"id":"970","name":"Gabite Claw","location":"TODO"},
  {"id":"971","name":"Gabite Fang","location":"TODO"},
  {"id":"972","name":"Star Rock","location":"TODO"},
  {"id":"973","name":"Meteor Torc","location":"TODO"},
  {"id":"974","name":"Gar-Claw","location":"TODO"},
  {"id":"975","name":"Gar-Fang","location":"TODO"},
  {"id":"976","name":"Speed Tag","location":"TODO"},
  {"id":"977","name":"Mach Scarf","location":"TODO"},
  {"id":"978","name":"Riolu Tail","location":"TODO"},
  {"id":"979","name":"Riolu Card","location":"TODO"},
  {"id":"980","name":"Valiant Rock","location":"TODO"},
  {"id":"981","name":"Emit Ring","location":"TODO"},
  {"id":"982","name":"Lucario Fang","location":"TODO"},
  {"id":"983","name":"Lucario Card","location":"TODO"},
  {"id":"984","name":"Pledge Rock","location":"TODO"},
  {"id":"985","name":"Ravage Ring","location":"TODO"},
  {"id":"986","name":"Mantyke Beam","location":"TODO"},
  {"id":"987","name":"Mantyke Card","location":"TODO"},
  {"id":"988","name":"Waft Rock","location":"TODO"},
  {"id":"989","name":"Ocean Bow","location":"TODO"},
  {"id":"990","name":"Mantine Foam","location":"TODO"},
  {"id":"991","name":"Mantine Card","location":"TODO"},
  {"id":"992","name":"Sunset Rock","location":"TODO"},
  {"id":"993","name":"Horizon Bow","location":"TODO"},
  {"id":"994","name":"Phione Song","location":"TODO"},
  {"id":"995","name":"Phione Card","location":"TODO"},
  {"id":"996","name":"Wave Jewel","location":"TODO"},
  {"id":"997","name":"Ripple Cape","location":"TODO"},
  {"id":"998","name":"Vulpix Tail","location":"TODO"},
  {"id":"999","name":"Vulpix Card","location":"TODO"},
  {"id":"1000","name":"Vulpix Tag","location":"TODO"},
  {"id":"1001","name":"Glowing Bow","location":"TODO"},
  {"id":"1002","name":"Nine-Hair","location":"TODO"},
  {"id":"1003","name":"Nine-Card","location":"TODO"},
  {"id":"1004","name":"Nine-Seal","location":"TODO"},
  {"id":"1005","name":"Afire Collar","location":"TODO"},
  {"id":"1006","name":"Phanpy Claw","location":"TODO"},
  {"id":"1007","name":"Phanpy Card","location":"TODO"},
  {"id":"1008","name":"Phanpy Tag","location":"TODO"},
  {"id":"1009","name":"Value Ruff","location":"TODO"},
  {"id":"1010","name":"Donphan Fang","location":"TODO"},
  {"id":"1011","name":"Donphan Card","location":"TODO"},
  {"id":"1012","name":"Don-Crest","location":"TODO"},
  {"id":"1013","name":"Armor Scarf","location":"TODO"},
  {"id":"1014","name":"Cater-Belt","location":"TODO"},
  {"id":"1015","name":"Defense Bow","location":"TODO"},
  {"id":"1016","name":"Glittery Bow","location":"TODO"},
  {"id":"1017","name":"Weedle Bow","location":"TODO"},
  {"id":"1018","name":"Kakuna Scarf","location":"TODO"},
  {"id":"1019","name":"Charge Scarf","location":"TODO"},
  {"id":"1020","name":"Pidgey Bow","location":"TODO"},
  {"id":"1021","name":"Pidgeo-Scarf","location":"TODO"},
  {"id":"1022","name":"Pidgeot Torc","location":"TODO"},
  {"id":"1023","name":"Ratta-Scarf","location":"TODO"},
  {"id":"1024","name":"Overcome Bow","location":"TODO"},
  {"id":"1025","name":"Quirky Bow","location":"TODO"},
  {"id":"1026","name":"Wing Scarf","location":"TODO"},
  {"id":"1027","name":"Leash Bow","location":"TODO"},
  {"id":"1028","name":"Shock Ruff","location":"TODO"},
  {"id":"1029","name":"Sand-Scarf","location":"TODO"},
  {"id":"1030","name":"Sandy Torc","location":"TODO"},
  {"id":"1031","name":"Pointy Scarf","location":"TODO"},
  {"id":"1032","name":"Return Scarf","location":"TODO"},
  {"id":"1033","name":"Impact Torc","location":"TODO"},
  {"id":"1034","name":"Halve Scarf","location":"TODO"},
  {"id":"1035","name":"Thorny Scarf","location":"TODO"},
  {"id":"1036","name":"King Sash","location":"TODO"},
  {"id":"1037","name":"Dodge Bow","location":"TODO"},
  {"id":"1038","name":"Absorb Scarf","location":"TODO"},
  {"id":"1039","name":"Odd Bow","location":"TODO"},
  {"id":"1040","name":"Guard Hat","location":"TODO"},
  {"id":"1041","name":"Aroma Scarf","location":"TODO"},
  {"id":"1042","name":"Moving Scarf","location":"TODO"},
  {"id":"1043","name":"Firm Hat","location":"TODO"},
  {"id":"1044","name":"Gaze Goggles","location":"TODO"},
  {"id":"1045","name":"Venomoth Bow","location":"TODO"},
  {"id":"1046","name":"Diglett Hat","location":"TODO"},
  {"id":"1047","name":"Dugtrio Bow","location":"TODO"},
  {"id":"1048","name":"Psyduck Hat","location":"TODO"},
  {"id":"1049","name":"Paddle Scarf","location":"TODO"},
  {"id":"1050","name":"Mankey Torc","location":"TODO"},
  {"id":"1051","name":"Nullify Belt","location":"TODO"},
  {"id":"1052","name":"Growl-Scarf","location":"TODO"},
  {"id":"1053","name":"Legend Bow","location":"TODO"},
  {"id":"1054","name":"Damp Bow","location":"TODO"},
  {"id":"1055","name":"Poli-Bow","location":"TODO"},
  {"id":"1056","name":"Bold Belt","location":"TODO"},
  {"id":"1057","name":"Predict Torc","location":"TODO"},
  {"id":"1058","name":"Psychic Torc","location":"TODO"},
  {"id":"1059","name":"Sparkle Ruff","location":"TODO"},
  {"id":"1060","name":"Impish Band","location":"TODO"},
  {"id":"1061","name":"Strong Belt","location":"TODO"},
  {"id":"1062","name":"Machamp Belt","location":"TODO"},
  {"id":"1063","name":"Bell-Bow","location":"TODO"},
  {"id":"1064","name":"Digest Scarf","location":"TODO"},
  {"id":"1065","name":"Victree-Torc","location":"TODO"},
  {"id":"1066","name":"Tangle Bow","location":"TODO"},
  {"id":"1067","name":"Tenta-Cape","location":"TODO"},
  {"id":"1068","name":"Geodude Torc","location":"TODO"},
  {"id":"1069","name":"Rocky Torc","location":"TODO"},
  {"id":"1070","name":"Rugged Sash","location":"TODO"},
  {"id":"1071","name":"Heated Bow","location":"TODO"},
  {"id":"1072","name":"Sunlight Bow","location":"TODO"},
  {"id":"1073","name":"Slowpoke Hat","location":"TODO"},
  {"id":"1074","name":"Slow-Scarf","location":"TODO"},
  {"id":"1075","name":"Magne-Torc","location":"TODO"},
  {"id":"1076","name":"Magneton Bow","location":"TODO"},
  {"id":"1077","name":"Bullseye Bow","location":"TODO"},
  {"id":"1078","name":"Buddy Torc","location":"TODO"},
  {"id":"1079","name":"Fight Torc","location":"TODO"},
  {"id":"1080","name":"Gentle Bow","location":"TODO"},
  {"id":"1081","name":"North Torc","location":"TODO"},
  {"id":"1082","name":"Grimy Scarf","location":"TODO"},
  {"id":"1083","name":"Slimy Bow","location":"TODO"},
  {"id":"1084","name":"Shell-Torc","location":"TODO"},
  {"id":"1085","name":"Cover Armor","location":"TODO"},
  {"id":"1086","name":"Gastly Veil","location":"TODO"},
  {"id":"1087","name":"Slip Scarf","location":"TODO"},
  {"id":"1088","name":"Sunglasses","location":"TODO"},
  {"id":"1089","name":"Trust Brooch","location":"TODO"},
  {"id":"1090","name":"Drowzee Tie","location":"TODO"},
  {"id":"1091","name":"Dream Coin","location":"TODO"},
  {"id":"1092","name":"Krabby Bow","location":"TODO"},
  {"id":"1093","name":"Super Sash","location":"TODO"},
  {"id":"1094","name":"Ball Scarf","location":"TODO"},
  {"id":"1095","name":"Electro-Bow","location":"TODO"},
  {"id":"1096","name":"Repel Scarf","location":"TODO"},
  {"id":"1097","name":"Exeggu-Sash","location":"TODO"},
  {"id":"1098","name":"Cubone Scarf","location":"TODO"},
  {"id":"1099","name":"Marowak Torc","location":"TODO"},
  {"id":"1100","name":"Licky Scarf","location":"TODO"},
  {"id":"1101","name":"Koffing Bow","location":"TODO"},
  {"id":"1102","name":"Weez-Scarf","location":"TODO"},
  {"id":"1103","name":"Solid Shield","location":"TODO"},
  {"id":"1104","name":"Pierce Drill","location":"TODO"},
  {"id":"1105","name":"Sticky Bow","location":"TODO"},
  {"id":"1106","name":"Kang-Apron","location":"TODO"},
  {"id":"1107","name":"Horsea Bow","location":"TODO"},
  {"id":"1108","name":"Swirl Scarf","location":"TODO"},
  {"id":"1109","name":"Goldeen Bow","location":"TODO"},
  {"id":"1110","name":"Seaking Bow","location":"TODO"},
  {"id":"1111","name":"Recover Torc","location":"TODO"},
  {"id":"1112","name":"Starmie Belt","location":"TODO"},
  {"id":"1113","name":"Pinsir Sash","location":"TODO"},
  {"id":"1114","name":"Rushing Bow","location":"TODO"},
  {"id":"1115","name":"Magikarp Bow","location":"TODO"},
  {"id":"1116","name":"Tempest Sash","location":"TODO"},
  {"id":"1117","name":"Ditto Torc","location":"TODO"},
  {"id":"1118","name":"AI Brooch","location":"TODO"},
  {"id":"1119","name":"Spike Brooch","location":"TODO"},
  {"id":"1120","name":"Aged Scarf","location":"TODO"},
  {"id":"1121","name":"Kabuto Hat","location":"TODO"},
  {"id":"1122","name":"Kabu-Torc","location":"TODO"},
  {"id":"1123","name":"Old Brooch","location":"TODO"},
  {"id":"1124","name":"Dragon Sash","location":"TODO"},
  {"id":"1125","name":"Aloft Mantle","location":"TODO"},
  {"id":"1126","name":"Mirage Cape","location":"TODO"},
  {"id":"1127","name":"Sentret Ruff","location":"TODO"},
  {"id":"1128","name":"Body Collar","location":"TODO"},
  {"id":"1129","name":"Expose Specs","location":"TODO"},
  {"id":"1130","name":"Noctowl Torc","location":"TODO"},
  {"id":"1131","name":"Morning Bow","location":"TODO"},
  {"id":"1132","name":"Ledian Bow","location":"TODO"},
  {"id":"1133","name":"Spina-Scarf","location":"TODO"},
  {"id":"1134","name":"Ariados Bow","location":"TODO"},
  {"id":"1135","name":"Slash Bow","location":"TODO"},
  {"id":"1136","name":"Shine Torc","location":"TODO"},
  {"id":"1137","name":"Lanturn Bow","location":"TODO"},
  {"id":"1138","name":"Lively Scarf","location":"TODO"},
  {"id":"1139","name":"Xatu Bow","location":"TODO"},
  {"id":"1140","name":"Wool Bow","location":"TODO"},
  {"id":"1141","name":"Fluffy Scarf","location":"TODO"},
  {"id":"1142","name":"Sacred Scarf","location":"TODO"},
  {"id":"1143","name":"Bright Tiara","location":"TODO"},
  {"id":"1144","name":"Rain Crown","location":"TODO"},
  {"id":"1145","name":"Zephyr Bow","location":"TODO"},
  {"id":"1146","name":"Skip-Scarf","location":"TODO"},
  {"id":"1147","name":"Cotton Torc","location":"TODO"},
  {"id":"1148","name":"Revenge Ruff","location":"TODO"},
  {"id":"1149","name":"Hasty Bow","location":"TODO"},
  {"id":"1150","name":"Sun Scarf","location":"TODO"},
  {"id":"1151","name":"Chitin Bow","location":"TODO"},
  {"id":"1152","name":"Wooper Bow","location":"TODO"},
  {"id":"1153","name":"Quag-Torc","location":"TODO"},
  {"id":"1154","name":"Murkrow Hat","location":"TODO"},
  {"id":"1155","name":"King Cap","location":"TODO"},
  {"id":"1156","name":"Misdrea-Cape","location":"TODO"},
  {"id":"1157","name":"Cryptic Sash","location":"TODO"},
  {"id":"1158","name":"Reverse Bow","location":"TODO"},
  {"id":"1159","name":"Robust Bow","location":"TODO"},
  {"id":"1160","name":"Dense Poncho","location":"TODO"},
  {"id":"1161","name":"Escape Scarf","location":"TODO"},
  {"id":"1162","name":"Takeoff Ruff","location":"TODO"},
  {"id":"1163","name":"Quartz Torc","location":"TODO"},
  {"id":"1164","name":"Snub-Cape","location":"TODO"},
  {"id":"1165","name":"Stern Sash","location":"TODO"},
  {"id":"1166","name":"Qwilfish Bow","location":"TODO"},
  {"id":"1167","name":"Shuckle Bow","location":"TODO"},
  {"id":"1168","name":"Horn Torc","location":"TODO"},
  {"id":"1169","name":"Lava Bow","location":"TODO"},
  {"id":"1170","name":"Torrid Scarf","location":"TODO"},
  {"id":"1171","name":"Frigid Bow","location":"TODO"},
  {"id":"1172","name":"Frost Torc","location":"TODO"},
  {"id":"1173","name":"Eager Brooch","location":"TODO"},
  {"id":"1174","name":"Reach Bow","location":"TODO"},
  {"id":"1175","name":"Psy Bow","location":"TODO"},
  {"id":"1176","name":"Snow Brooch","location":"TODO"},
  {"id":"1177","name":"Skar-Cape","location":"TODO"},
  {"id":"1178","name":"Dark Choker","location":"TODO"},
  {"id":"1179","name":"Pit Fang","location":"TODO"},
  {"id":"1180","name":"Tornado Bow","location":"TODO"},
  {"id":"1181","name":"Virtual Bow","location":"TODO"},
  {"id":"1182","name":"Delusion Bow","location":"TODO"},
  {"id":"1183","name":"Paint Scarf","location":"TODO"},
  {"id":"1184","name":"Milky Scarf","location":"TODO"},
  {"id":"1185","name":"Larvitar Bow","location":"TODO"},
  {"id":"1186","name":"Pupita-Scarf","location":"TODO"},
  {"id":"1187","name":"Crash Claw","location":"TODO"},
  {"id":"1188","name":"Pooch-Collar","location":"TODO"},
  {"id":"1189","name":"Dark Fang","location":"TODO"},
  {"id":"1190","name":"Merry Scarf","location":"TODO"},
  {"id":"1191","name":"Linoone Ruff","location":"TODO"},
  {"id":"1192","name":"Wurmple Bow","location":"TODO"},
  {"id":"1193","name":"Tough Scarf","location":"TODO"},
  {"id":"1194","name":"Vivid Silk","location":"TODO"},
  {"id":"1195","name":"Guard Bow","location":"TODO"},
  {"id":"1196","name":"Dustox Bow","location":"TODO"},
  {"id":"1197","name":"Kelp Hat","location":"TODO"},
  {"id":"1198","name":"Jolly Scarf","location":"TODO"},
  {"id":"1199","name":"Ludicolo Hat","location":"TODO"},
  {"id":"1200","name":"Seedot Hat","location":"TODO"},
  {"id":"1201","name":"Nuzleaf Bow","location":"TODO"},
  {"id":"1202","name":"Shiftry Belt","location":"TODO"},
  {"id":"1203","name":"Taillow Bow","location":"TODO"},
  {"id":"1204","name":"Midair Scarf","location":"TODO"},
  {"id":"1205","name":"Wingull Bow","location":"TODO"},
  {"id":"1206","name":"Stock Scarf","location":"TODO"},
  {"id":"1207","name":"Sensing Hat","location":"TODO"},
  {"id":"1208","name":"Magical Bow","location":"TODO"},
  {"id":"1209","name":"Caring Scarf","location":"TODO"},
  {"id":"1210","name":"Bliss Scarf","location":"TODO"},
  {"id":"1211","name":"Blocking Bow","location":"TODO"},
  {"id":"1212","name":"Mobile Bow","location":"TODO"},
  {"id":"1213","name":"Thwart Bow","location":"TODO"},
  {"id":"1214","name":"Slak-Scarf","location":"TODO"},
  {"id":"1215","name":"Vigor Sash","location":"TODO"},
  {"id":"1216","name":"Lazy Ruff","location":"TODO"},
  {"id":"1217","name":"Novice Scarf","location":"TODO"},
  {"id":"1218","name":"Ninja Ruff","location":"TODO"},
  {"id":"1219","name":"Awe Mantle","location":"TODO"},
  {"id":"1220","name":"Good Earring","location":"TODO"},
  {"id":"1221","name":"Nice Bangle","location":"TODO"},
  {"id":"1222","name":"Great Torc","location":"TODO"},
  {"id":"1223","name":"Makuhit-Belt","location":"TODO"},
  {"id":"1224","name":"Thrust Belt","location":"TODO"},
  {"id":"1225","name":"Nose-Torc","location":"TODO"},
  {"id":"1226","name":"Sable-Scope","location":"TODO"},
  {"id":"1227","name":"Deceit Mask","location":"TODO"},
  {"id":"1228","name":"Iron Torc","location":"TODO"},
  {"id":"1229","name":"Metal Bangle","location":"TODO"},
  {"id":"1230","name":"Iron Helmet","location":"TODO"},
  {"id":"1231","name":"Intuit Bow","location":"TODO"},
  {"id":"1232","name":"Ponder Sash","location":"TODO"},
  {"id":"1233","name":"Punish Torc","location":"TODO"},
  {"id":"1234","name":"Protect Mask","location":"TODO"},
  {"id":"1235","name":"Neon Scarf","location":"TODO"},
  {"id":"1236","name":"Evening Bow","location":"TODO"},
  {"id":"1237","name":"Thorned Torc","location":"TODO"},
  {"id":"1238","name":"Gulpin Bow","location":"TODO"},
  {"id":"1239","name":"Swalot Belt","location":"TODO"},
  {"id":"1240","name":"Carva-Sash","location":"TODO"},
  {"id":"1241","name":"Vicious Bow","location":"TODO"},
  {"id":"1242","name":"Spout Scarf","location":"TODO"},
  {"id":"1243","name":"Huge Bow","location":"TODO"},
  {"id":"1244","name":"Numel Bow","location":"TODO"},
  {"id":"1245","name":"Erupt Scarf","location":"TODO"},
  {"id":"1246","name":"Sooty Sash","location":"TODO"},
  {"id":"1247","name":"Spring Bow","location":"TODO"},
  {"id":"1248","name":"Scheme Scarf","location":"TODO"},
  {"id":"1249","name":"Hula Bow","location":"TODO"},
  {"id":"1250","name":"Desert Bow","location":"TODO"},
  {"id":"1251","name":"Vibra Scarf","location":"TODO"},
  {"id":"1252","name":"Red Glasses","location":"TODO"},
  {"id":"1253","name":"Desert Sash","location":"TODO"},
  {"id":"1254","name":"Cacturne Hat","location":"TODO"},
  {"id":"1255","name":"Tuft Bow","location":"TODO"},
  {"id":"1256","name":"Cloud Ruff","location":"TODO"},
  {"id":"1257","name":"Strong Sash","location":"TODO"},
  {"id":"1258","name":"Seviper Bow","location":"TODO"},
  {"id":"1259","name":"Lunaton-Torc","location":"TODO"},
  {"id":"1260","name":"Solrock Bow","location":"TODO"},
  {"id":"1261","name":"Soak Scarf","location":"TODO"},
  {"id":"1262","name":"Whiscash Bow","location":"TODO"},
  {"id":"1263","name":"Bossy Scarf","location":"TODO"},
  {"id":"1264","name":"Cower Sash","location":"TODO"},
  {"id":"1265","name":"Bal-Brooch","location":"TODO"},
  {"id":"1266","name":"Claydol Torc","location":"TODO"},
  {"id":"1267","name":"Bind Scarf","location":"TODO"},
  {"id":"1268","name":"Cradily Bow","location":"TODO"},
  {"id":"1269","name":"Guard Claw","location":"TODO"},
  {"id":"1270","name":"Rigid Cape","location":"TODO"},
  {"id":"1271","name":"Admire Scarf","location":"TODO"},
  {"id":"1272","name":"Grace Scarf","location":"TODO"},
  {"id":"1273","name":"Kecleon Torc","location":"TODO"},
  {"id":"1274","name":"Shuppet Cape","location":"TODO"},
  {"id":"1275","name":"Ominous Torc","location":"TODO"},
  {"id":"1276","name":"Duskull Ruff","location":"TODO"},
  {"id":"1277","name":"Illusion Bow","location":"TODO"},
  {"id":"1278","name":"Tropius Bow","location":"TODO"},
  {"id":"1279","name":"Chime-Scarf","location":"TODO"},
  {"id":"1280","name":"Perish Torc","location":"TODO"},
  {"id":"1281","name":"Chilly Hat","location":"TODO"},
  {"id":"1282","name":"Hail Scarf","location":"TODO"},
  {"id":"1283","name":"Sleet Bow","location":"TODO"},
  {"id":"1284","name":"Safe Scarf","location":"TODO"},
  {"id":"1285","name":"Walrein Torc","location":"TODO"},
  {"id":"1286","name":"Clam-Brooch","location":"TODO"},
  {"id":"1287","name":"Deep Torc","location":"TODO"},
  {"id":"1288","name":"Gore-Scarf","location":"TODO"},
  {"id":"1289","name":"Reli-Torc","location":"TODO"},
  {"id":"1290","name":"Luvdisc Torc","location":"TODO"},
  {"id":"1291","name":"Crag Helmet","location":"TODO"},
  {"id":"1292","name":"Outlast Bow","location":"TODO"},
  {"id":"1293","name":"Sala-Cape","location":"TODO"},
  {"id":"1294","name":"Beldum Torc","location":"TODO"},
  {"id":"1295","name":"Metang Scarf","location":"TODO"},
  {"id":"1296","name":"Meta-Torc","location":"TODO"},
  {"id":"1297","name":"Starly Bow","location":"TODO"},
  {"id":"1298","name":"Regret Torc","location":"TODO"},
  {"id":"1299","name":"Guts Sash","location":"TODO"},
  {"id":"1300","name":"Still Bow","location":"TODO"},
  {"id":"1301","name":"Kricke-Torc","location":"TODO"},
  {"id":"1302","name":"Budew Scarf","location":"TODO"},
  {"id":"1303","name":"Bouquet Cape","location":"TODO"},
  {"id":"1304","name":"Hard Helmet","location":"TODO"},
  {"id":"1305","name":"Skull Helmet","location":"TODO"},
  {"id":"1306","name":"Rebound Bow","location":"TODO"},
  {"id":"1307","name":"Block Brooch","location":"TODO"},
  {"id":"1308","name":"Straw Cape","location":"TODO"},
  {"id":"1309","name":"Worma-Bow","location":"TODO"},
  {"id":"1310","name":"Mothim Bow","location":"TODO"},
  {"id":"1311","name":"Nectar Bow","location":"TODO"},
  {"id":"1312","name":"Vespi-Torc","location":"TODO"},
  {"id":"1313","name":"Awake Bow","location":"TODO"},
  {"id":"1314","name":"Gastro-Torc","location":"TODO"},
  {"id":"1315","name":"Ambipom Bow","location":"TODO"},
  {"id":"1316","name":"Defrost Ruff","location":"TODO"},
  {"id":"1317","name":"Allure Coat","location":"TODO"},
  {"id":"1318","name":"Magic Hat","location":"TODO"},
  {"id":"1319","name":"Honch-Cape","location":"TODO"},
  {"id":"1320","name":"Glameow Bow","location":"TODO"},
  {"id":"1321","name":"Scary Belt","location":"TODO"},
  {"id":"1322","name":"Ching-Torc","location":"TODO"},
  {"id":"1323","name":"Stinky Scarf","location":"TODO"},
  {"id":"1324","name":"Stench Sash","location":"TODO"},
  {"id":"1325","name":"Image Brooch","location":"TODO"},
  {"id":"1326","name":"Mirror Torc","location":"TODO"},
  {"id":"1327","name":"Chatot Scarf","location":"TODO"},
  {"id":"1328","name":"Thick Scarf","location":"TODO"},
  {"id":"1329","name":"Grit Veil","location":"TODO"},
  {"id":"1330","name":"Skorupi Bow","location":"TODO"},
  {"id":"1331","name":"Dust Scarf","location":"TODO"},
  {"id":"1332","name":"Croa-Torc","location":"TODO"},
  {"id":"1333","name":"Toxi-Belt","location":"TODO"},
  {"id":"1334","name":"Carni-Bow","location":"TODO"},
  {"id":"1335","name":"Swim Bow","location":"TODO"},
  {"id":"1336","name":"Lumi-Torc","location":"TODO"},
  {"id":"1337","name":"Snowy Torc","location":"TODO"},
  {"id":"1338","name":"Frozen Cape","location":"TODO"},
  {"id":"1339","name":"Builder Sash","location":"TODO"},
  {"id":"1340","name":"Flabby Belt","location":"TODO"},
  {"id":"1341","name":"Rhyperi-Torc","location":"TODO"},
  {"id":"1342","name":"Clinging Bow","location":"TODO"},
  {"id":"1343","name":"Yanmega Bow","location":"TODO"},
  {"id":"1344","name":"Gliscor Cape","location":"TODO"},
  {"id":"1345","name":"Glacier Cape","location":"TODO"},
  {"id":"1346","name":"Best Scarf","location":"TODO"},
  {"id":"1347","name":"Gallant Torc","location":"TODO"},
  {"id":"1348","name":"Probo-Hat","location":"TODO"},
  {"id":"1349","name":"Unlucky Sash","location":"TODO"},
  {"id":"1350","name":"Froslass Bow","location":"TODO"},
  {"id":"1351","name":"Purify Veil","location":"TODO"},
  {"id":"1352","name":"$$","obtainable":-1},
  {"id":"1353","name":"$$","obtainable":-1},
  {"id":"1354","name":"$$","obtainable":-1},
  {"id":"1355","name":"$$","obtainable":-1},
  {"id":"1356","name":"$$","obtainable":-1},
  {"id":"1357","name":"$$","obtainable":-1},
  {"id":"1358","name":"$$","obtainable":-1},
  {"id":"1359","name":"$$","obtainable":-1},
  {"id":"1360","name":"$$","obtainable":-1},
  {"id":"1361","name":"$$","obtainable":-1},
  {"id":"1362","name":"$$","obtainable":-1},
  {"id":"1363","name":"$$","obtainable":-1},
  {"id":"1364","name":"$$","obtainable":-1},
  {"id":"1365","name":"$$","obtainable":-1},
  {"id":"1366","name":"$$","obtainable":-1},
  {"id":"1367","name":"$$","obtainable":-1},
  {"id":"1368","name":"$$","obtainable":-1},
  {"id":"1369","name":"$$","obtainable":-1},
  {"id":"1370","name":"$$","obtainable":-1},
  {"id":"1371","name":"$$","obtainable":-1},
  {"id":"1372","name":"$$","obtainable":-1},
  {"id":"1373","name":"$$","obtainable":-1},
  {"id":"1374","name":"$$","obtainable":-1},
  {"id":"1375","name":"$$","obtainable":-1},
  {"id":"1376","name":"$$","obtainable":-1},
  {"id":"1377","name":"$$","obtainable":-1},
  {"id":"1378","name":"$$","obtainable":-1},
  {"id":"1379","name":"$$","obtainable":-1},
  {"id":"1380","name":"$$","obtainable":-1},
  {"id":"1381","name":"$$","obtainable":-1},
  {"id":"1382","name":"$$","obtainable":-1},
  {"id":"1383","name":"$$","obtainable":-1},
  {"id":"1384","name":"$$","obtainable":-1},
  {"id":"1385","name":"$$","obtainable":-1},
  {"id":"1386","name":"$$","obtainable":-1},
  {"id":"1387","name":"$$","obtainable":-1},
  {"id":"1388","name":"$$","obtainable":-1},
  {"id":"1389","name":"$$","obtainable":-1},
  {"id":"1390","name":"$$","obtainable":-1},
  {"id":"1391","name":"$$","obtainable":-1},
  {"id":"1392","name":"$$","obtainable":-1},
  {"id":"1393","name":"$$","obtainable":-1},
  {"id":"1394","name":"$$","obtainable":-1},
  {"id":"1395","name":"$$","obtainable":-1},
  {"id":"1396","name":"$$","obtainable":-1},
  {"id":"1397","name":"$$","obtainable":-1},
  {"id":"1398","name":"$$","obtainable":-1},
  {"id":"1399","name":"$$","obtainable":-1}
 ];
